--BEGIN
  --dbms_snapshot.REFRESH('C_CN_EXCLUSIONS');
--END;

CREATE MATERIALIZED VIEW LOG ON H_CN_EXCLUSIONS;

CREATE MATERIALIZED VIEW C_CN_EXCLUSIONS refresh FAST ON demand
AS
  SELECT PIDM
  , BANNER_ID
  , NAME_SORT
  , ENTITY_CODE
  , EXCLUSION_CODE
  , EXCLUSION_DESC
  , ACTIVITY_DATE
  , START_DATE
  , END_DATE
  , EXCLUSION_REASON
  , EXCLUDE_PHONE_IND
  , EXCLUDE_MAIL_IND
  , USER_ID
  , TRUMP_IND
  , RECORD_START_DATE
  FROM h_cn_exclusions
  WHERE record_end_date IS NULL; 
  
  COMMENT ON COLUMN "PENTAHO"."C_CN_EXCLUSIONS"."TRUMP_IND" IS '''Y'' for codes = NOC, INR, INL, DEC, RPD';

  CREATE INDEX "PENTAHO"."C_CN_EXCLUSIONS_BANNER_ID" ON "PENTAHO"."C_CN_EXCLUSIONS" ("BANNER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERSPACE" ;

  CREATE INDEX "PENTAHO"."C_CN_EXCLUSIONS_CODE" ON "PENTAHO"."C_CN_EXCLUSIONS" ("EXCLUSION_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERSPACE" ;

  CREATE INDEX "PENTAHO"."C_CN_EXCLUSIONS_ENTITY_CODE" ON "PENTAHO"."C_CN_EXCLUSIONS" ("ENTITY_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERSPACE" ;

  CREATE INDEX "PENTAHO"."C_CN_EXCLUSIONS_NAME_SORT" ON "PENTAHO"."C_CN_EXCLUSIONS" ("NAME_SORT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERSPACE" ;

 