/*BEGIN
dbms_snapshot.REFRESH('C_CN_DONOR_STATUS_BY_ID');
END;
*/

CREATE MATERIALIZED VIEW LOG ON H_CN_DONOR_STATUS_BY_ID;

CREATE MATERIALIZED VIEW C_CN_DONOR_STATUS_BY_ID refresh fast ON demand
AS
  SELECT
    PIDM
  , BANNER_ID
  , NAME_SORT
  , ENTITY_CODE
  , RECORD_START_DATE
  , DONOR_STATUS_0
  , YEARS_SINCE_0
  , LAST_CASH_CRED_YEAR_0
  , LAST_CASH_CRED_DATE_0
  , LAST_CASH_CRED_NUMBER_0
  , LAST_CASH_CRED_DESG_CODE_0
  , LAST_CASH_CRED_DESG_DESC_0
  , LAST_CASH_CRED_AMOUNT_0
  , FIRST_CASH_CRED_YEAR_0
  , FIRST_CASH_CRED_DATE_0
  , FIRST_CASH_CRED_NUMBER_0
  , FIRST_CASH_CRED_DESG_CODE_0
  , FIRST_CASH_CRED_DESG_DESC_0
  , FIRST_CASH_CRED_AMOUNT_0
  , LARGEST_CASH_CRED_YEAR_0
  , LARGEST_CASH_CRED_DATE_0
  , LARGEST_CASH_CRED_NUMBER_0
  , LARGEST_CASH_CRED_DESG_CODE_0
  , LARGEST_CASH_CRED_DESG_DESC_0
  , LARGEST_CASH_CRED_AMOUNT_0
  , LAST_PLDG_CRED_YEAR_0
  , LAST_PLDG_CRED_DATE_0
  , LAST_PLDG_CRED_NUMBER_0
  , LAST_PLDG_CRED_DESG_CODE_0
  , LAST_PLDG_CRED_DESG_DESC_0
  , LAST_PLDG_CRED_AMOUNT_0
  , FIRST_PLDG_CRED_YEAR_0
  , FIRST_PLDG_CRED_DATE_0
  , FIRST_PLDG_CRED_NUMBER_0
  , FIRST_PLDG_CRED_DESG_CODE_0
  , FIRST_PLDG_CRED_DESG_DESC_0
  , FIRST_PLDG_CRED_AMOUNT_0
  , LARGEST_PLDG_CRED_YEAR_0
  , LARGEST_PLDG_CRED_DATE_0
  , LARGEST_PLDG_CRED_NUMBER_0
  , LARGEST_PLDG_CRED_DESG_CODE_0
  , LARGEST_PLDG_CRED_DESG_DESC_0
  , LARGEST_PLDG_CRED_AMOUNT_0
  , APS_DONOR_STATUS_0
  , APS_YEARS_SINCE_0
  , APS_LAST_YEAR_0
  , APS_LAST_LEVEL_CODE_0
  , APS_LAST_LEVEL_DESC_0
  , SM_DONOR_STATUS_0
  , SM_YEARS_SINCE_0
  , SM_LAST_YEAR_0
  , SM_LAST_LEVEL_CODE_0
  , SM_LAST_LEVEL_DESC_0
  , DONOR_STATUS_1
  , YEARS_SINCE_1
  , LAST_CASH_CRED_YEAR_1
  , LAST_CASH_CRED_DATE_1
  , LAST_CASH_CRED_NUMBER_1
  , LAST_CASH_CRED_DESG_CODE_1
  , LAST_CASH_CRED_DESG_DESC_1
  , LAST_CASH_CRED_AMOUNT_1
  , FIRST_CASH_CRED_YEAR_1
  , FIRST_CASH_CRED_DATE_1
  , FIRST_CASH_CRED_NUMBER_1
  , FIRST_CASH_CRED_DESG_CODE_1
  , FIRST_CASH_CRED_DESG_DESC_1
  , FIRST_CASH_CRED_AMOUNT_1
  , LARGEST_CASH_CRED_YEAR_1
  , LARGEST_CASH_CRED_DATE_1
  , LARGEST_CASH_CRED_NUMBER_1
  , LARGEST_CASH_CRED_DESG_CODE_1
  , LARGEST_CASH_CRED_DESG_DESC_1
  , LARGEST_CASH_CRED_AMOUNT_1
  , LAST_PLDG_CRED_YEAR_1
  , LAST_PLDG_CRED_DATE_1
  , LAST_PLDG_CRED_NUMBER_1
  , LAST_PLDG_CRED_DESG_CODE_1
  , LAST_PLDG_CRED_DESG_DESC_1
  , LAST_PLDG_CRED_AMOUNT_1
  , FIRST_PLDG_CRED_YEAR_1
  , FIRST_PLDG_CRED_DATE_1
  , FIRST_PLDG_CRED_NUMBER_1
  , FIRST_PLDG_CRED_DESG_CODE_1
  , FIRST_PLDG_CRED_DESG_DESC_1
  , FIRST_PLDG_CRED_AMOUNT_1
  , LARGEST_PLDG_CRED_YEAR_1
  , LARGEST_PLDG_CRED_DATE_1
  , LARGEST_PLDG_CRED_NUMBER_1
  , LARGEST_PLDG_CRED_DESG_CODE_1
  , LARGEST_PLDG_CRED_DESG_DESC_1
  , LARGEST_PLDG_CRED_AMOUNT_1
  , APS_DONOR_STATUS_1
  , APS_YEARS_SINCE_1
  , APS_LAST_YEAR_1
  , APS_LAST_LEVEL_CODE_1
  , APS_LAST_LEVEL_DESC_1
  , SM_DONOR_STATUS_1
  , SM_YEARS_SINCE_1
  , SM_LAST_YEAR_1
  , SM_LAST_LEVEL_CODE_1
  , SM_LAST_LEVEL_DESC_1
  , DONOR_STATUS_2
  , YEARS_SINCE_2
  , LAST_CASH_CRED_YEAR_2
  , LAST_CASH_CRED_DATE_2
  , LAST_CASH_CRED_NUMBER_2
  , LAST_CASH_CRED_DESG_CODE_2
  , LAST_CASH_CRED_DESG_DESC_2
  , LAST_CASH_CRED_AMOUNT_2
  , FIRST_CASH_CRED_YEAR_2
  , FIRST_CASH_CRED_DATE_2
  , FIRST_CASH_CRED_NUMBER_2
  , FIRST_CASH_CRED_DESG_CODE_2
  , FIRST_CASH_CRED_DESG_DESC_2
  , FIRST_CASH_CRED_AMOUNT_2
  , LARGEST_CASH_CRED_YEAR_2
  , LARGEST_CASH_CRED_DATE_2
  , LARGEST_CASH_CRED_NUMBER_2
  , LARGEST_CASH_CRED_DESG_CODE_2
  , LARGEST_CASH_CRED_DESG_DESC_2
  , LARGEST_CASH_CRED_AMOUNT_2
  , LAST_PLDG_CRED_YEAR_2
  , LAST_PLDG_CRED_DATE_2
  , LAST_PLDG_CRED_NUMBER_2
  , LAST_PLDG_CRED_DESG_CODE_2
  , LAST_PLDG_CRED_DESG_DESC_2
  , LAST_PLDG_CRED_AMOUNT_2
  , FIRST_PLDG_CRED_YEAR_2
  , FIRST_PLDG_CRED_DATE_2
  , FIRST_PLDG_CRED_NUMBER_2
  , FIRST_PLDG_CRED_DESG_CODE_2
  , FIRST_PLDG_CRED_DESG_DESC_2
  , FIRST_PLDG_CRED_AMOUNT_2
  , LARGEST_PLDG_CRED_YEAR_2
  , LARGEST_PLDG_CRED_DATE_2
  , LARGEST_PLDG_CRED_NUMBER_2
  , LARGEST_PLDG_CRED_DESG_CODE_2
  , LARGEST_PLDG_CRED_DESG_DESC_2
  , LARGEST_PLDG_CRED_AMOUNT_2
  , APS_DONOR_STATUS_2
  , APS_YEARS_SINCE_2
  , APS_LAST_YEAR_2
  , APS_LAST_LEVEL_CODE_2
  , APS_LAST_LEVEL_DESC_2
  , SM_DONOR_STATUS_2
  , SM_YEARS_SINCE_2
  , SM_LAST_YEAR_2
  , SM_LAST_LEVEL_CODE_2
  , SM_LAST_LEVEL_DESC_2
  , DONOR_STATUS_3
  , YEARS_SINCE_3
  , LAST_CASH_CRED_YEAR_3
  , LAST_CASH_CRED_DATE_3
  , LAST_CASH_CRED_NUMBER_3
  , LAST_CASH_CRED_DESG_CODE_3
  , LAST_CASH_CRED_DESG_DESC_3
  , LAST_CASH_CRED_AMOUNT_3
  , FIRST_CASH_CRED_YEAR_3
  , FIRST_CASH_CRED_DATE_3
  , FIRST_CASH_CRED_NUMBER_3
  , FIRST_CASH_CRED_DESG_CODE_3
  , FIRST_CASH_CRED_DESG_DESC_3
  , FIRST_CASH_CRED_AMOUNT_3
  , LARGEST_CASH_CRED_YEAR_3
  , LARGEST_CASH_CRED_DATE_3
  , LARGEST_CASH_CRED_NUMBER_3
  , LARGEST_CASH_CRED_DESG_CODE_3
  , LARGEST_CASH_CRED_DESG_DESC_3
  , LARGEST_CASH_CRED_AMOUNT_3
  , LAST_PLDG_CRED_YEAR_3
  , LAST_PLDG_CRED_DATE_3
  , LAST_PLDG_CRED_NUMBER_3
  , LAST_PLDG_CRED_DESG_CODE_3
  , LAST_PLDG_CRED_DESG_DESC_3
  , LAST_PLDG_CRED_AMOUNT_3
  , FIRST_PLDG_CRED_YEAR_3
  , FIRST_PLDG_CRED_DATE_3
  , FIRST_PLDG_CRED_NUMBER_3
  , FIRST_PLDG_CRED_DESG_CODE_3
  , FIRST_PLDG_CRED_DESG_DESC_3
  , FIRST_PLDG_CRED_AMOUNT_3
  , LARGEST_PLDG_CRED_YEAR_3
  , LARGEST_PLDG_CRED_DATE_3
  , LARGEST_PLDG_CRED_NUMBER_3
  , LARGEST_PLDG_CRED_DESG_CODE_3
  , LARGEST_PLDG_CRED_DESG_DESC_3
  , LARGEST_PLDG_CRED_AMOUNT_3
  , APS_DONOR_STATUS_3
  , APS_YEARS_SINCE_3
  , APS_LAST_YEAR_3
  , APS_LAST_LEVEL_CODE_3
  , APS_LAST_LEVEL_DESC_3
  , SM_DONOR_STATUS_3
  , SM_YEARS_SINCE_3
  , SM_LAST_YEAR_3
  , SM_LAST_LEVEL_CODE_3
  , SM_LAST_LEVEL_DESC_3
  , DONOR_STATUS_4
  , YEARS_SINCE_4
  , LAST_CASH_CRED_YEAR_4
  , LAST_CASH_CRED_DATE_4
  , LAST_CASH_CRED_NUMBER_4
  , LAST_CASH_CRED_DESG_CODE_4
  , LAST_CASH_CRED_DESG_DESC_4
  , LAST_CASH_CRED_AMOUNT_4
  , FIRST_CASH_CRED_YEAR_4
  , FIRST_CASH_CRED_DATE_4
  , FIRST_CASH_CRED_NUMBER_4
  , FIRST_CASH_CRED_DESG_CODE_4
  , FIRST_CASH_CRED_DESG_DESC_4
  , FIRST_CASH_CRED_AMOUNT_4
  , LARGEST_CASH_CRED_YEAR_4
  , LARGEST_CASH_CRED_DATE_4
  , LARGEST_CASH_CRED_NUMBER_4
  , LARGEST_CASH_CRED_DESG_CODE_4
  , LARGEST_CASH_CRED_DESG_DESC_4
  , LARGEST_CASH_CRED_AMOUNT_4
  , LAST_PLDG_CRED_YEAR_4
  , LAST_PLDG_CRED_DATE_4
  , LAST_PLDG_CRED_NUMBER_4
  , LAST_PLDG_CRED_DESG_CODE_4
  , LAST_PLDG_CRED_DESG_DESC_4
  , LAST_PLDG_CRED_AMOUNT_4
  , FIRST_PLDG_CRED_YEAR_4
  , FIRST_PLDG_CRED_DATE_4
  , FIRST_PLDG_CRED_NUMBER_4
  , FIRST_PLDG_CRED_DESG_CODE_4
  , FIRST_PLDG_CRED_DESG_DESC_4
  , FIRST_PLDG_CRED_AMOUNT_4
  , LARGEST_PLDG_CRED_YEAR_4
  , LARGEST_PLDG_CRED_DATE_4
  , LARGEST_PLDG_CRED_NUMBER_4
  , LARGEST_PLDG_CRED_DESG_CODE_4
  , LARGEST_PLDG_CRED_DESG_DESC_4
  , LARGEST_PLDG_CRED_AMOUNT_4
  , APS_DONOR_STATUS_4
  , APS_YEARS_SINCE_4
  , APS_LAST_YEAR_4
  , APS_LAST_LEVEL_CODE_4
  , APS_LAST_LEVEL_DESC_4
  , SM_DONOR_STATUS_4
  , SM_YEARS_SINCE_4
  , SM_LAST_YEAR_4
  , SM_LAST_LEVEL_CODE_4
  , SM_LAST_LEVEL_DESC_4
  , DONOR_STATUS_5
  , YEARS_SINCE_5
  , LAST_CASH_CRED_YEAR_5
  , LAST_CASH_CRED_DATE_5
  , LAST_CASH_CRED_NUMBER_5
  , LAST_CASH_CRED_DESG_CODE_5
  , LAST_CASH_CRED_DESG_DESC_5
  , LAST_CASH_CRED_AMOUNT_5
  , FIRST_CASH_CRED_YEAR_5
  , FIRST_CASH_CRED_DATE_5
  , FIRST_CASH_CRED_NUMBER_5
  , FIRST_CASH_CRED_DESG_CODE_5
  , FIRST_CASH_CRED_DESG_DESC_5
  , FIRST_CASH_CRED_AMOUNT_5
  , LARGEST_CASH_CRED_YEAR_5
  , LARGEST_CASH_CRED_DATE_5
  , LARGEST_CASH_CRED_NUMBER_5
  , LARGEST_CASH_CRED_DESG_CODE_5
  , LARGEST_CASH_CRED_DESG_DESC_5
  , LARGEST_CASH_CRED_AMOUNT_5
  , LAST_PLDG_CRED_YEAR_5
  , LAST_PLDG_CRED_DATE_5
  , LAST_PLDG_CRED_NUMBER_5
  , LAST_PLDG_CRED_DESG_CODE_5
  , LAST_PLDG_CRED_DESG_DESC_5
  , LAST_PLDG_CRED_AMOUNT_5
  , FIRST_PLDG_CRED_YEAR_5
  , FIRST_PLDG_CRED_DATE_5
  , FIRST_PLDG_CRED_NUMBER_5
  , FIRST_PLDG_CRED_DESG_CODE_5
  , FIRST_PLDG_CRED_DESG_DESC_5
  , FIRST_PLDG_CRED_AMOUNT_5
  , LARGEST_PLDG_CRED_YEAR_5
  , LARGEST_PLDG_CRED_DATE_5
  , LARGEST_PLDG_CRED_NUMBER_5
  , LARGEST_PLDG_CRED_DESG_CODE_5
  , LARGEST_PLDG_CRED_DESG_DESC_5
  , LARGEST_PLDG_CRED_AMOUNT_5
  , APS_DONOR_STATUS_5
  , APS_YEARS_SINCE_5
  , APS_LAST_YEAR_5
  , APS_LAST_LEVEL_CODE_5
  , APS_LAST_LEVEL_DESC_5
  , SM_DONOR_STATUS_5
  , SM_YEARS_SINCE_5
  , SM_LAST_YEAR_5
  , SM_LAST_LEVEL_CODE_5
  , SM_LAST_LEVEL_DESC_5
  , DONOR_STATUS_6
  , YEARS_SINCE_6
  , LAST_CASH_CRED_YEAR_6
  , LAST_CASH_CRED_DATE_6
  , LAST_CASH_CRED_NUMBER_6
  , LAST_CASH_CRED_DESG_CODE_6
  , LAST_CASH_CRED_DESG_DESC_6
  , LAST_CASH_CRED_AMOUNT_6
  , FIRST_CASH_CRED_YEAR_6
  , FIRST_CASH_CRED_DATE_6
  , FIRST_CASH_CRED_NUMBER_6
  , FIRST_CASH_CRED_DESG_CODE_6
  , FIRST_CASH_CRED_DESG_DESC_6
  , FIRST_CASH_CRED_AMOUNT_6
  , LARGEST_CASH_CRED_YEAR_6
  , LARGEST_CASH_CRED_DATE_6
  , LARGEST_CASH_CRED_NUMBER_6
  , LARGEST_CASH_CRED_DESG_CODE_6
  , LARGEST_CASH_CRED_DESG_DESC_6
  , LARGEST_CASH_CRED_AMOUNT_6
  , LAST_PLDG_CRED_YEAR_6
  , LAST_PLDG_CRED_DATE_6
  , LAST_PLDG_CRED_NUMBER_6
  , LAST_PLDG_CRED_DESG_CODE_6
  , LAST_PLDG_CRED_DESG_DESC_6
  , LAST_PLDG_CRED_AMOUNT_6
  , FIRST_PLDG_CRED_YEAR_6
  , FIRST_PLDG_CRED_DATE_6
  , FIRST_PLDG_CRED_NUMBER_6
  , FIRST_PLDG_CRED_DESG_CODE_6
  , FIRST_PLDG_CRED_DESG_DESC_6
  , FIRST_PLDG_CRED_AMOUNT_6
  , LARGEST_PLDG_CRED_YEAR_6
  , LARGEST_PLDG_CRED_DATE_6
  , LARGEST_PLDG_CRED_NUMBER_6
  , LARGEST_PLDG_CRED_DESG_CODE_6
  , LARGEST_PLDG_CRED_DESG_DESC_6
  , LARGEST_PLDG_CRED_AMOUNT_6
  , APS_DONOR_STATUS_6
  , APS_YEARS_SINCE_6
  , APS_LAST_YEAR_6
  , APS_LAST_LEVEL_CODE_6
  , APS_LAST_LEVEL_DESC_6
  , SM_DONOR_STATUS_6
  , SM_YEARS_SINCE_6
  , SM_LAST_YEAR_6
  , SM_LAST_LEVEL_CODE_6
  , SM_LAST_LEVEL_DESC_6
  , DONOR_STATUS_7
  , YEARS_SINCE_7
  , LAST_CASH_CRED_YEAR_7
  , LAST_CASH_CRED_DATE_7
  , LAST_CASH_CRED_NUMBER_7
  , LAST_CASH_CRED_DESG_CODE_7
  , LAST_CASH_CRED_DESG_DESC_7
  , LAST_CASH_CRED_AMOUNT_7
  , FIRST_CASH_CRED_YEAR_7
  , FIRST_CASH_CRED_DATE_7
  , FIRST_CASH_CRED_NUMBER_7
  , FIRST_CASH_CRED_DESG_CODE_7
  , FIRST_CASH_CRED_DESG_DESC_7
  , FIRST_CASH_CRED_AMOUNT_7
  , LARGEST_CASH_CRED_YEAR_7
  , LARGEST_CASH_CRED_DATE_7
  , LARGEST_CASH_CRED_NUMBER_7
  , LARGEST_CASH_CRED_DESG_CODE_7
  , LARGEST_CASH_CRED_DESG_DESC_7
  , LARGEST_CASH_CRED_AMOUNT_7
  , LAST_PLDG_CRED_YEAR_7
  , LAST_PLDG_CRED_DATE_7
  , LAST_PLDG_CRED_NUMBER_7
  , LAST_PLDG_CRED_DESG_CODE_7
  , LAST_PLDG_CRED_DESG_DESC_7
  , LAST_PLDG_CRED_AMOUNT_7
  , FIRST_PLDG_CRED_YEAR_7
  , FIRST_PLDG_CRED_DATE_7
  , FIRST_PLDG_CRED_NUMBER_7
  , FIRST_PLDG_CRED_DESG_CODE_7
  , FIRST_PLDG_CRED_DESG_DESC_7
  , FIRST_PLDG_CRED_AMOUNT_7
  , LARGEST_PLDG_CRED_YEAR_7
  , LARGEST_PLDG_CRED_DATE_7
  , LARGEST_PLDG_CRED_NUMBER_7
  , LARGEST_PLDG_CRED_DESG_CODE_7
  , LARGEST_PLDG_CRED_DESG_DESC_7
  , LARGEST_PLDG_CRED_AMOUNT_7
  , APS_DONOR_STATUS_7
  , APS_YEARS_SINCE_7
  , APS_LAST_YEAR_7
  , APS_LAST_LEVEL_CODE_7
  , APS_LAST_LEVEL_DESC_7
  , SM_DONOR_STATUS_7
  , SM_YEARS_SINCE_7
  , SM_LAST_YEAR_7
  , SM_LAST_LEVEL_CODE_7
  , SM_LAST_LEVEL_DESC_7
  , DONOR_STATUS_8
  , YEARS_SINCE_8
  , LAST_CASH_CRED_YEAR_8
  , LAST_CASH_CRED_DATE_8
  , LAST_CASH_CRED_NUMBER_8
  , LAST_CASH_CRED_DESG_CODE_8
  , LAST_CASH_CRED_DESG_DESC_8
  , LAST_CASH_CRED_AMOUNT_8
  , FIRST_CASH_CRED_YEAR_8
  , FIRST_CASH_CRED_DATE_8
  , FIRST_CASH_CRED_NUMBER_8
  , FIRST_CASH_CRED_DESG_CODE_8
  , FIRST_CASH_CRED_DESG_DESC_8
  , FIRST_CASH_CRED_AMOUNT_8
  , LARGEST_CASH_CRED_YEAR_8
  , LARGEST_CASH_CRED_DATE_8
  , LARGEST_CASH_CRED_NUMBER_8
  , LARGEST_CASH_CRED_DESG_CODE_8
  , LARGEST_CASH_CRED_DESG_DESC_8
  , LARGEST_CASH_CRED_AMOUNT_8
  , LAST_PLDG_CRED_YEAR_8
  , LAST_PLDG_CRED_DATE_8
  , LAST_PLDG_CRED_NUMBER_8
  , LAST_PLDG_CRED_DESG_CODE_8
  , LAST_PLDG_CRED_DESG_DESC_8
  , LAST_PLDG_CRED_AMOUNT_8
  , FIRST_PLDG_CRED_YEAR_8
  , FIRST_PLDG_CRED_DATE_8
  , FIRST_PLDG_CRED_NUMBER_8
  , FIRST_PLDG_CRED_DESG_CODE_8
  , FIRST_PLDG_CRED_DESG_DESC_8
  , FIRST_PLDG_CRED_AMOUNT_8
  , LARGEST_PLDG_CRED_YEAR_8
  , LARGEST_PLDG_CRED_DATE_8
  , LARGEST_PLDG_CRED_NUMBER_8
  , LARGEST_PLDG_CRED_DESG_CODE_8
  , LARGEST_PLDG_CRED_DESG_DESC_8
  , LARGEST_PLDG_CRED_AMOUNT_8
  , APS_DONOR_STATUS_8
  , APS_YEARS_SINCE_8
  , APS_LAST_YEAR_8
  , APS_LAST_LEVEL_CODE_8
  , APS_LAST_LEVEL_DESC_8
  , SM_DONOR_STATUS_8
  , SM_YEARS_SINCE_8
  , SM_LAST_YEAR_8
  , SM_LAST_LEVEL_CODE_8
  , SM_LAST_LEVEL_DESC_8
  , DONOR_STATUS_9
  , YEARS_SINCE_9
  , LAST_CASH_CRED_YEAR_9
  , LAST_CASH_CRED_DATE_9
  , LAST_CASH_CRED_NUMBER_9
  , LAST_CASH_CRED_DESG_CODE_9
  , LAST_CASH_CRED_DESG_DESC_9
  , LAST_CASH_CRED_AMOUNT_9
  , FIRST_CASH_CRED_YEAR_9
  , FIRST_CASH_CRED_DATE_9
  , FIRST_CASH_CRED_NUMBER_9
  , FIRST_CASH_CRED_DESG_CODE_9
  , FIRST_CASH_CRED_DESG_DESC_9
  , FIRST_CASH_CRED_AMOUNT_9
  , LARGEST_CASH_CRED_YEAR_9
  , LARGEST_CASH_CRED_DATE_9
  , LARGEST_CASH_CRED_NUMBER_9
  , LARGEST_CASH_CRED_DESG_CODE_9
  , LARGEST_CASH_CRED_DESG_DESC_9
  , LARGEST_CASH_CRED_AMOUNT_9
  , LAST_PLDG_CRED_YEAR_9
  , LAST_PLDG_CRED_DATE_9
  , LAST_PLDG_CRED_NUMBER_9
  , LAST_PLDG_CRED_DESG_CODE_9
  , LAST_PLDG_CRED_DESG_DESC_9
  , LAST_PLDG_CRED_AMOUNT_9
  , FIRST_PLDG_CRED_YEAR_9
  , FIRST_PLDG_CRED_DATE_9
  , FIRST_PLDG_CRED_NUMBER_9
  , FIRST_PLDG_CRED_DESG_CODE_9
  , FIRST_PLDG_CRED_DESG_DESC_9
  , FIRST_PLDG_CRED_AMOUNT_9
  , LARGEST_PLDG_CRED_YEAR_9
  , LARGEST_PLDG_CRED_DATE_9
  , LARGEST_PLDG_CRED_NUMBER_9
  , LARGEST_PLDG_CRED_DESG_CODE_9
  , LARGEST_PLDG_CRED_DESG_DESC_9
  , LARGEST_PLDG_CRED_AMOUNT_9
  , APS_DONOR_STATUS_9
  , APS_YEARS_SINCE_9
  , APS_LAST_YEAR_9
  , APS_LAST_LEVEL_CODE_9
  , APS_LAST_LEVEL_DESC_9
  , SM_DONOR_STATUS_9
  , SM_YEARS_SINCE_9
  , SM_LAST_YEAR_9
  , SM_LAST_LEVEL_CODE_9
  , SM_LAST_LEVEL_DESC_9
  , APS_LEVEL_CODE_0
  , APS_LEVEL_CODE_1
  , APS_LEVEL_CODE_2
  , APS_LEVEL_CODE_3
  , APS_LEVEL_CODE_4
  , APS_LEVEL_CODE_5
  , APS_LEVEL_CODE_6
  , APS_LEVEL_CODE_7
  , APS_LEVEL_CODE_8
  , APS_LEVEL_CODE_9
  , APS_LEVEL_DESC_0
  , APS_LEVEL_DESC_1
  , APS_LEVEL_DESC_2
  , APS_LEVEL_DESC_3
  , APS_LEVEL_DESC_4
  , APS_LEVEL_DESC_5
  , APS_LEVEL_DESC_6
  , APS_LEVEL_DESC_7
  , APS_LEVEL_DESC_8
  , APS_LEVEL_DESC_9
  , SM_LEVEL_CODE_0
  , SM_LEVEL_CODE_1
  , SM_LEVEL_CODE_2
  , SM_LEVEL_CODE_3
  , SM_LEVEL_CODE_4
  , SM_LEVEL_CODE_5
  , SM_LEVEL_CODE_6
  , SM_LEVEL_CODE_7
  , SM_LEVEL_CODE_8
  , SM_LEVEL_CODE_9
  , SM_LEVEL_DESC_0
  , SM_LEVEL_DESC_1
  , SM_LEVEL_DESC_2
  , SM_LEVEL_DESC_3
  , SM_LEVEL_DESC_4
  , SM_LEVEL_DESC_5
  , SM_LEVEL_DESC_6
  , SM_LEVEL_DESC_7
  , SM_LEVEL_DESC_8
  , SM_LEVEL_DESC_9
  FROM
    h_cn_donor_status_by_id
  WHERE
    record_end_date IS NULL;
    
  COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."PIDM" IS 'from CN_CONSTITUENT.PIDM';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."BANNER_ID" IS 'from CN_CONSTITUENT.BANNER_ID';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."NAME_SORT" IS 'from CN_CONSTITUENT.ENTITY_CODE';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."ENTITY_CODE" IS 'from CN_CONSTITUENT.NAME_SORT';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."DONOR_STATUS_0" IS 'Donor status as of close of previous business day (Current FY)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."YEARS_SINCE_0" IS 'Number of fiscal years since last gift (Current FY)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_CASH_CRED_YEAR_0" IS 'FY of most recent gift made (Current FY)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_CASH_CRED_DATE_0" IS 'Date of most recent gift made (Current FY)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_CASH_CRED_NUMBER_0" IS 'Gift number of most recent gift made (Current FY)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_CASH_CRED_DESG_CODE_0" IS 'Designation code of most recent gift made (Current FY)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_CASH_CRED_DESG_DESC_0" IS 'Designation name of most recent gift made (Current FY)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_CASH_CRED_AMOUNT_0" IS 'Amount of most recent gift made (Current FY)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_CASH_CRED_YEAR_0" IS 'FY of first gift recorded in Banner (Current FY)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_CASH_CRED_DATE_0" IS 'Date of first gift recorded in Banner (Current FY)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_CASH_CRED_NUMBER_0" IS 'Gift number of first gift recorded in Banner (Current FY)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_CASH_CRED_DESG_CODE_0" IS 'Designation code of first gift recorded in Banner (Current FY)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_CASH_CRED_DESG_DESC_0" IS 'Designation name of first gift recorded in Banner (Current FY)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_CASH_CRED_AMOUNT_0" IS 'Amount of first gift recorded in Banner (Current FY)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_CASH_CRED_YEAR_0" IS 'FY of largest single gift recorded (Current FY)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_CASH_CRED_DATE_0" IS 'Date of largest single gift recorded (Current FY)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_CASH_CRED_NUMBER_0" IS 'Gift number of largest single gift recorded (Current FY)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_CASH_CRED_DESG_CODE_0" IS 'Designation code of largest single gift recorded (Current FY)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_CASH_CRED_DESG_DESC_0" IS 'Designation name of largest single gift recorded (Current FY)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_CASH_CRED_AMOUNT_0" IS 'Amount of largest single gift recorded (Current FY)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_PLDG_CRED_YEAR_0" IS 'FY of most recent pledge recorded (Current FY)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_PLDG_CRED_DATE_0" IS 'Date of most recent pledge recorded (Current FY)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_PLDG_CRED_NUMBER_0" IS 'Pledge number of most recent pledge recorded (Current FY)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_PLDG_CRED_DESG_CODE_0" IS 'Designation code of most recent pledge recorded (Current FY)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_PLDG_CRED_DESG_DESC_0" IS 'Designation name of most recent pledge recorded (Current FY)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_PLDG_CRED_AMOUNT_0" IS 'Amount of most recent pledge recorded (Current FY)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_PLDG_CRED_YEAR_0" IS 'FY of first pledge recorded in Banner (Current FY)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_PLDG_CRED_DATE_0" IS 'Date of first pledge recorded in Banner (Current FY)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_PLDG_CRED_NUMBER_0" IS 'Pledge number of first pledge recorded in Banner (Current FY)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_PLDG_CRED_DESG_CODE_0" IS 'Designation code of first pledge recorded in Banner (Current FY)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_PLDG_CRED_DESG_DESC_0" IS 'Designation name of first pledge recorded in Banner (Current FY)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_PLDG_CRED_AMOUNT_0" IS 'Amount of first pledge recorded in Banner (Current FY)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_PLDG_CRED_YEAR_0" IS 'FY of largest single pledge recorded (Current FY)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_PLDG_CRED_DATE_0" IS 'Date of largest single pledge recorded (Current FY)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_PLDG_CRED_NUMBER_0" IS 'Pledge number of largest single pledge recorded (Current FY)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_PLDG_CRED_DESG_CODE_0" IS 'Designation code of largest single pledge recorded (Current FY)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_PLDG_CRED_DESG_DESC_0" IS 'Designation name of largest single pledge recorded (Current FY)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_PLDG_CRED_AMOUNT_0" IS 'Amount of largest single pledge recorded (Current FY)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."APS_DONOR_STATUS_0" IS 'APS Donor status as of close of previous business day (Current FY)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."APS_YEARS_SINCE_0" IS 'Number of years since last in Asa Packer Society (Current FY)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."APS_LAST_YEAR_0" IS 'Last fiscal year of APS membership (Current FY)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."APS_LAST_LEVEL_CODE_0" IS 'APS Level code when last in APS Society (Current FY)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."APS_LAST_LEVEL_DESC_0" IS 'APS Level name when last in APS Society (Current FY)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."SM_DONOR_STATUS_0" IS 'SM Donor status as of close of previous business day (Current FY) -- begins where DCNP_CODE >= 02';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."SM_YEARS_SINCE_0" IS 'Number of years since last in South Mtn Society (Current FY)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."SM_LAST_YEAR_0" IS 'Last fiscal year of SM membership (Current FY)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."SM_LAST_LEVEL_CODE_0" IS 'SM Level code when last in SM Society (Current FY) -- excludes 01';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."SM_LAST_LEVEL_DESC_0" IS 'SM Level name when last in SM Society (Current FY) -- excludes Year One';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."DONOR_STATUS_1" IS 'Donor status as of end of FY (Current FY-1)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."YEARS_SINCE_1" IS 'Number of fiscal years since last gift (Current FY-1)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_CASH_CRED_YEAR_1" IS 'FY of most recent gift made (Current FY-1)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_CASH_CRED_DATE_1" IS 'Date of most recent gift made (Current FY-1)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_CASH_CRED_NUMBER_1" IS 'Gift number of most recent gift made (Current FY-1)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_CASH_CRED_DESG_CODE_1" IS 'Designation code of most recent gift made (Current FY-1)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_CASH_CRED_DESG_DESC_1" IS 'Designation name of most recent gift made (Current FY-1)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_CASH_CRED_AMOUNT_1" IS 'Amount of most recent gift made (Current FY-1)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_CASH_CRED_YEAR_1" IS 'FY of first gift recorded in Banner (Current FY-1)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_CASH_CRED_DATE_1" IS 'Date of first gift recorded in Banner (Current FY-1)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_CASH_CRED_NUMBER_1" IS 'Gift number of first gift recorded in Banner (Current FY-1)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_CASH_CRED_DESG_CODE_1" IS 'Designation code of first gift recorded in Banner (Current FY-1)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_CASH_CRED_DESG_DESC_1" IS 'Designation name of first gift recorded in Banner (Current FY-1)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_CASH_CRED_AMOUNT_1" IS 'Amount of first gift recorded in Banner (Current FY-1)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_CASH_CRED_YEAR_1" IS 'FY of largest single gift recorded (Current FY-1)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_CASH_CRED_DATE_1" IS 'Date of largest single gift recorded (Current FY-1)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_CASH_CRED_NUMBER_1" IS 'Gift number of largest single gift recorded (Current FY-1)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_CASH_CRED_DESG_CODE_1" IS 'Designation code of largest single gift recorded (Current FY-1)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_CASH_CRED_DESG_DESC_1" IS 'Designation name of largest single gift recorded (Current FY-1)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_CASH_CRED_AMOUNT_1" IS 'Amount of largest single gift recorded (Current FY-1)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_PLDG_CRED_YEAR_1" IS 'FY of most recent pledge recorded (Current FY-1)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_PLDG_CRED_DATE_1" IS 'Date of most recent pledge recorded (Current FY-1)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_PLDG_CRED_NUMBER_1" IS 'Pledge number of most recent pledge recorded (Current FY-1)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_PLDG_CRED_DESG_CODE_1" IS 'Designation code of most recent pledge recorded (Current FY-1)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_PLDG_CRED_DESG_DESC_1" IS 'Designation name of most recent pledge recorded (Current FY-1)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_PLDG_CRED_AMOUNT_1" IS 'Amount of most recent pledge recorded (Current FY-1)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_PLDG_CRED_YEAR_1" IS 'FY of first pledge recorded in Banner (Current FY-1)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_PLDG_CRED_DATE_1" IS 'Date of first pledge recorded in Banner (Current FY-1)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_PLDG_CRED_NUMBER_1" IS 'Pledge number of first pledge recorded in Banner (Current FY-1)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_PLDG_CRED_DESG_CODE_1" IS 'Designation code of first pledge recorded in Banner (Current FY-1)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_PLDG_CRED_DESG_DESC_1" IS 'Designation name of first pledge recorded in Banner (Current FY-1)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_PLDG_CRED_AMOUNT_1" IS 'Amount of first pledge recorded in Banner (Current FY-1)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_PLDG_CRED_YEAR_1" IS 'FY of largest single pledge recorded (Current FY-1)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_PLDG_CRED_DATE_1" IS 'Date of largest single pledge recorded (Current FY-1)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_PLDG_CRED_NUMBER_1" IS 'Pledge number of largest single pledge recorded (Current FY-1)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_PLDG_CRED_DESG_CODE_1" IS 'Designation code of largest single pledge recorded (Current FY-1)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_PLDG_CRED_DESG_DESC_1" IS 'Designation name of largest single pledge recorded (Current FY-1)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_PLDG_CRED_AMOUNT_1" IS 'Amount of largest single pledge recorded (Current FY-1)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."APS_DONOR_STATUS_1" IS 'APS Donor status at end of FY (Current FY-1)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."APS_YEARS_SINCE_1" IS 'Number of years since last in Asa Packer Society (Current FY-1)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."APS_LAST_YEAR_1" IS 'Last fiscal year of Asa Packer membership (Current FY-1)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."APS_LAST_LEVEL_CODE_1" IS 'APS Level code when last in Asa Packer Society (Current FY-1)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."APS_LAST_LEVEL_DESC_1" IS 'APS Level name when last in Asa Packer Society (Current FY-1)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."SM_DONOR_STATUS_1" IS 'SM Donor status at end of FY (Current FY-1) -- begins where DCNP_CODE >= 02';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."SM_YEARS_SINCE_1" IS 'Number of years since last in South Mtn Society (Current FY-1)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."SM_LAST_YEAR_1" IS 'Last fiscal year of Asa Packer membership (Current FY-1)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."SM_LAST_LEVEL_CODE_1" IS 'SM Level code when last in South Mtn Society (Current FY-1) -- excludes 01';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."SM_LAST_LEVEL_DESC_1" IS 'SM Level name when last in South Mtn Society (Current FY-1) -- excludes Year One';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."DONOR_STATUS_2" IS 'Donor status as of end of FY (Current FY-2)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."YEARS_SINCE_2" IS 'Number of fiscal years since last gift (Current FY-2)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_CASH_CRED_YEAR_2" IS 'FY of most recent gift made (Current FY-2)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_CASH_CRED_DATE_2" IS 'Date of most recent gift made (Current FY-2)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_CASH_CRED_NUMBER_2" IS 'Gift number of most recent gift made (Current FY-2)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_CASH_CRED_DESG_CODE_2" IS 'Designation code of most recent gift made (Current FY-2)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_CASH_CRED_DESG_DESC_2" IS 'Designation name of most recent gift made (Current FY-2)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_CASH_CRED_AMOUNT_2" IS 'Amount of most recent gift made (Current FY-2)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_CASH_CRED_YEAR_2" IS 'FY of first gift recorded in Banner (Current FY-2)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_CASH_CRED_DATE_2" IS 'Date of first gift recorded in Banner (Current FY-2)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_CASH_CRED_NUMBER_2" IS 'Gift number of first gift recorded in Banner (Current FY-2)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_CASH_CRED_DESG_CODE_2" IS 'Designation code of first gift recorded in Banner (Current FY-2)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_CASH_CRED_DESG_DESC_2" IS 'Designation name of first gift recorded in Banner (Current FY-2)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_CASH_CRED_AMOUNT_2" IS 'Amount of first gift recorded in Banner (Current FY-2)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_CASH_CRED_YEAR_2" IS 'FY of largest single gift recorded (Current FY-2)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_CASH_CRED_DATE_2" IS 'Date of largest single gift recorded (Current FY-2)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_CASH_CRED_NUMBER_2" IS 'Gift number of largest single gift recorded (Current FY-2)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_CASH_CRED_DESG_CODE_2" IS 'Designation code of largest single gift recorded (Current FY-2)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_CASH_CRED_DESG_DESC_2" IS 'Designation name of largest single gift recorded (Current FY-2)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_CASH_CRED_AMOUNT_2" IS 'Amount of largest single gift recorded (Current FY-2)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_PLDG_CRED_YEAR_2" IS 'FY of most recent pledge recorded (Current FY-2)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_PLDG_CRED_DATE_2" IS 'Date of most recent pledge recorded (Current FY-2)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_PLDG_CRED_NUMBER_2" IS 'Pledge number of most recent pledge recorded (Current FY-2)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_PLDG_CRED_DESG_CODE_2" IS 'Designation code of most recent pledge recorded (Current FY-2)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_PLDG_CRED_DESG_DESC_2" IS 'Designation name of most recent pledge recorded (Current FY-2)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_PLDG_CRED_AMOUNT_2" IS 'Amount of most recent pledge recorded (Current FY-2)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_PLDG_CRED_YEAR_2" IS 'FY of first pledge recorded in Banner (Current FY-2)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_PLDG_CRED_DATE_2" IS 'Date of first pledge recorded in Banner (Current FY-2)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_PLDG_CRED_NUMBER_2" IS 'Pledge number of first pledge recorded in Banner (Current FY-2)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_PLDG_CRED_DESG_CODE_2" IS 'Designation code of first pledge recorded in Banner (Current FY-2)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_PLDG_CRED_DESG_DESC_2" IS 'Designation name of first pledge recorded in Banner (Current FY-2)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_PLDG_CRED_AMOUNT_2" IS 'Amount of first pledge recorded in Banner (Current FY-2)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_PLDG_CRED_YEAR_2" IS 'FY of largest single pledge recorded (Current FY-2)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_PLDG_CRED_DATE_2" IS 'Date of largest single pledge recorded (Current FY-2)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_PLDG_CRED_NUMBER_2" IS 'Pledge number of largest single pledge recorded (Current FY-2)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_PLDG_CRED_DESG_CODE_2" IS 'Designation code of largest single pledge recorded (Current FY-2)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_PLDG_CRED_DESG_DESC_2" IS 'Designation name of largest single pledge recorded (Current FY-2)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_PLDG_CRED_AMOUNT_2" IS 'Amount of largest single pledge recorded (Current FY-2)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."APS_DONOR_STATUS_2" IS 'APS Donor status at end of FY (Current FY-2)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."APS_YEARS_SINCE_2" IS 'Number of years since last in Asa Packer Society (Current FY-2)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."APS_LAST_YEAR_2" IS 'Last fiscal year of Asa Packer membership (Current FY-2)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."APS_LAST_LEVEL_CODE_2" IS 'APS Level code when last in Asa Packer Society (Current FY-2)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."APS_LAST_LEVEL_DESC_2" IS 'APS Level name when last in Asa Packer Society (Current FY-2)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."SM_DONOR_STATUS_2" IS 'SM Donor status at end of FY (Current FY-2) -- begins where DCNP_CODE >= 02';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."SM_YEARS_SINCE_2" IS 'Number of years since last in South Mtn Society (Current FY-2)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."SM_LAST_YEAR_2" IS 'Last fiscal year of Asa Packer membership (Current FY-2)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."SM_LAST_LEVEL_CODE_2" IS 'SM Level code when last in South Mtn Society (Current FY-2) -- excludes 01';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."SM_LAST_LEVEL_DESC_2" IS 'SM Level name when last in South Mtn Society (Current FY-2) -- excludes Year One';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."DONOR_STATUS_3" IS 'Donor status as of end of FY (Current FY-3)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."YEARS_SINCE_3" IS 'Number of fiscal years since last gift (Current FY-3)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_CASH_CRED_YEAR_3" IS 'FY of most recent gift made (Current FY-3)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_CASH_CRED_DATE_3" IS 'Date of most recent gift made (Current FY-3)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_CASH_CRED_NUMBER_3" IS 'Gift number of most recent gift made (Current FY-3)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_CASH_CRED_DESG_CODE_3" IS 'Designation code of most recent gift made (Current FY-3)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_CASH_CRED_DESG_DESC_3" IS 'Designation name of most recent gift made (Current FY-3)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_CASH_CRED_AMOUNT_3" IS 'Amount of most recent gift made (Current FY-3)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_CASH_CRED_YEAR_3" IS 'FY of first gift recorded in Banner (Current FY-3)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_CASH_CRED_DATE_3" IS 'Date of first gift recorded in Banner (Current FY-3)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_CASH_CRED_NUMBER_3" IS 'Gift number of first gift recorded in Banner (Current FY-3)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_CASH_CRED_DESG_CODE_3" IS 'Designation code of first gift recorded in Banner (Current FY-3)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_CASH_CRED_DESG_DESC_3" IS 'Designation name of first gift recorded in Banner (Current FY-3)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_CASH_CRED_AMOUNT_3" IS 'Amount of first gift recorded in Banner (Current FY-3)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_CASH_CRED_YEAR_3" IS 'FY of largest single gift recorded (Current FY-3)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_CASH_CRED_DATE_3" IS 'Date of largest single gift recorded (Current FY-3)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_CASH_CRED_NUMBER_3" IS 'Gift number of largest single gift recorded (Current FY-3)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_CASH_CRED_DESG_CODE_3" IS 'Designation code of largest single gift recorded (Current FY-3)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_CASH_CRED_DESG_DESC_3" IS 'Designation name of largest single gift recorded (Current FY-3)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_CASH_CRED_AMOUNT_3" IS 'Amount of largest single gift recorded (Current FY-3)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_PLDG_CRED_YEAR_3" IS 'FY of most recent pledge recorded (Current FY-3)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_PLDG_CRED_DATE_3" IS 'Date of most recent pledge recorded (Current FY-3)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_PLDG_CRED_NUMBER_3" IS 'Pledge number of most recent pledge recorded (Current FY-3)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_PLDG_CRED_DESG_CODE_3" IS 'Designation code of most recent pledge recorded (Current FY-3)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_PLDG_CRED_DESG_DESC_3" IS 'Designation name of most recent pledge recorded (Current FY-3)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_PLDG_CRED_AMOUNT_3" IS 'Amount of most recent pledge recorded (Current FY-3)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_PLDG_CRED_YEAR_3" IS 'FY of first pledge recorded in Banner (Current FY-3)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_PLDG_CRED_DATE_3" IS 'Date of first pledge recorded in Banner (Current FY-3)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_PLDG_CRED_NUMBER_3" IS 'Pledge number of first pledge recorded in Banner (Current FY-3)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_PLDG_CRED_DESG_CODE_3" IS 'Designation code of first pledge recorded in Banner (Current FY-3)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_PLDG_CRED_DESG_DESC_3" IS 'Designation name of first pledge recorded in Banner (Current FY-3)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_PLDG_CRED_AMOUNT_3" IS 'Amount of first pledge recorded in Banner (Current FY-3)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_PLDG_CRED_YEAR_3" IS 'FY of largest single pledge recorded (Current FY-3)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_PLDG_CRED_DATE_3" IS 'Date of largest single pledge recorded (Current FY-3)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_PLDG_CRED_NUMBER_3" IS 'Pledge number of largest single pledge recorded (Current FY-3)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_PLDG_CRED_DESG_CODE_3" IS 'Designation code of largest single pledge recorded (Current FY-3)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_PLDG_CRED_DESG_DESC_3" IS 'Designation name of largest single pledge recorded (Current FY-3)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_PLDG_CRED_AMOUNT_3" IS 'Amount of largest single pledge recorded (Current FY-3)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."APS_DONOR_STATUS_3" IS 'APS Donor status at end of FY (Current FY-3)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."APS_YEARS_SINCE_3" IS 'Number of years since last in Asa Packer Society (Current FY-3)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."APS_LAST_YEAR_3" IS 'Last fiscal year of Asa Packer membership (Current FY-3)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."APS_LAST_LEVEL_CODE_3" IS 'APS Level code when last in Asa Packer Society (Current FY-3)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."APS_LAST_LEVEL_DESC_3" IS 'APS Level name when last in Asa Packer Society (Current FY-3)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."SM_DONOR_STATUS_3" IS 'SM Donor status at end of FY (Current FY-3) -- begins where DCNP_CODE >= 02';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."SM_YEARS_SINCE_3" IS 'Number of years since last in South Mtn Society (Current FY-3)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."SM_LAST_YEAR_3" IS 'Last fiscal year of Asa Packer membership (Current FY-3)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."SM_LAST_LEVEL_CODE_3" IS 'SM Level code when last in South Mtn Society (Current FY-3) -- excludes 01';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."SM_LAST_LEVEL_DESC_3" IS 'SM Level name when last in South Mtn Society (Current FY-3) -- excludes Year One';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."DONOR_STATUS_4" IS 'Donor status as of end of FY (Current FY-4)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."YEARS_SINCE_4" IS 'Number of fiscal years since last gift (Current FY-4)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_CASH_CRED_YEAR_4" IS 'FY of most recent gift made (Current FY-4)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_CASH_CRED_DATE_4" IS 'Date of most recent gift made (Current FY-4)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_CASH_CRED_NUMBER_4" IS 'Gift number of most recent gift made (Current FY-4)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_CASH_CRED_DESG_CODE_4" IS 'Designation code of most recent gift made (Current FY-4)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_CASH_CRED_DESG_DESC_4" IS 'Designation name of most recent gift made (Current FY-4)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_CASH_CRED_AMOUNT_4" IS 'Amount of most recent gift made (Current FY-4)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_CASH_CRED_YEAR_4" IS 'FY of first gift recorded in Banner (Current FY-4)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_CASH_CRED_DATE_4" IS 'Date of first gift recorded in Banner (Current FY-4)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_CASH_CRED_NUMBER_4" IS 'Gift number of first gift recorded in Banner (Current FY-4)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_CASH_CRED_DESG_CODE_4" IS 'Designation code of first gift recorded in Banner (Current FY-4)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_CASH_CRED_DESG_DESC_4" IS 'Designation name of first gift recorded in Banner (Current FY-4)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_CASH_CRED_AMOUNT_4" IS 'Amount of first gift recorded in Banner (Current FY-4)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_CASH_CRED_YEAR_4" IS 'FY of largest single gift recorded (Current FY-4)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_CASH_CRED_DATE_4" IS 'Date of largest single gift recorded (Current FY-4)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_CASH_CRED_NUMBER_4" IS 'Gift number of largest single gift recorded (Current FY-4)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_CASH_CRED_DESG_CODE_4" IS 'Designation code of largest single gift recorded (Current FY-4)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_CASH_CRED_DESG_DESC_4" IS 'Designation name of largest single gift recorded (Current FY-4)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_CASH_CRED_AMOUNT_4" IS 'Amount of largest single gift recorded (Current FY-4)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_PLDG_CRED_YEAR_4" IS 'FY of most recent pledge recorded (Current FY-4)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_PLDG_CRED_DATE_4" IS 'Date of most recent pledge recorded (Current FY-4)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_PLDG_CRED_NUMBER_4" IS 'Pledge number of most recent pledge recorded (Current FY-4)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_PLDG_CRED_DESG_CODE_4" IS 'Designation code of most recent pledge recorded (Current FY-4)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_PLDG_CRED_DESG_DESC_4" IS 'Designation name of most recent pledge recorded (Current FY-4)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_PLDG_CRED_AMOUNT_4" IS 'Amount of most recent pledge recorded (Current FY-4)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_PLDG_CRED_YEAR_4" IS 'FY of first pledge recorded in Banner (Current FY-4)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_PLDG_CRED_DATE_4" IS 'Date of first pledge recorded in Banner (Current FY-4)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_PLDG_CRED_NUMBER_4" IS 'Pledge number of first pledge recorded in Banner (Current FY-4)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_PLDG_CRED_DESG_CODE_4" IS 'Designation code of first pledge recorded in Banner (Current FY-4)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_PLDG_CRED_DESG_DESC_4" IS 'Designation name of first pledge recorded in Banner (Current FY-4)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_PLDG_CRED_AMOUNT_4" IS 'Amount of first pledge recorded in Banner (Current FY-4)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_PLDG_CRED_YEAR_4" IS 'FY of largest single pledge recorded (Current FY-4)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_PLDG_CRED_DATE_4" IS 'Date of largest single pledge recorded (Current FY-4)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_PLDG_CRED_NUMBER_4" IS 'Pledge number of largest single pledge recorded (Current FY-4)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_PLDG_CRED_DESG_CODE_4" IS 'Designation code of largest single pledge recorded (Current FY-4)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_PLDG_CRED_DESG_DESC_4" IS 'Designation name of largest single pledge recorded (Current FY-4)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_PLDG_CRED_AMOUNT_4" IS 'Amount of largest single pledge recorded (Current FY-4)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."APS_DONOR_STATUS_4" IS 'APS Donor status at end of FY (Current FY-4)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."APS_YEARS_SINCE_4" IS 'Number of years since last in Asa Packer Society (Current FY-4)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."APS_LAST_YEAR_4" IS 'Last fiscal year of Asa Packer membership (Current FY-4)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."APS_LAST_LEVEL_CODE_4" IS 'APS Level code when last in Asa Packer Society (Current FY-4)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."APS_LAST_LEVEL_DESC_4" IS 'APS Level name when last in Asa Packer Society (Current FY-4)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."SM_DONOR_STATUS_4" IS 'SM Donor status at end of FY (Current FY-4) -- begins where DCNP_CODE >= 02';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."SM_YEARS_SINCE_4" IS 'Number of years since last in South Mtn Society (Current FY-4)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."SM_LAST_YEAR_4" IS 'Last fiscal year of Asa Packer membership (Current FY-4)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."SM_LAST_LEVEL_CODE_4" IS 'SM Level code when last in South Mtn Society (Current FY-4) -- excludes 01';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."SM_LAST_LEVEL_DESC_4" IS 'SM Level name when last in South Mtn Society (Current FY-4) -- excludes Year One';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."DONOR_STATUS_5" IS 'Donor status as of end of FY (Current FY-5)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."YEARS_SINCE_5" IS 'Number of fiscal years since last gift (Current FY-5)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_CASH_CRED_YEAR_5" IS 'FY of most recent gift made (Current FY-5)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_CASH_CRED_DATE_5" IS 'Date of most recent gift made (Current FY-5)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_CASH_CRED_NUMBER_5" IS 'Gift number of most recent gift made (Current FY-5)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_CASH_CRED_DESG_CODE_5" IS 'Designation code of most recent gift made (Current FY-5)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_CASH_CRED_DESG_DESC_5" IS 'Designation name of most recent gift made (Current FY-5)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_CASH_CRED_AMOUNT_5" IS 'Amount of most recent gift made (Current FY-5)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_CASH_CRED_YEAR_5" IS 'FY of first gift recorded in Banner (Current FY-5)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_CASH_CRED_DATE_5" IS 'Date of first gift recorded in Banner (Current FY-5)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_CASH_CRED_NUMBER_5" IS 'Gift number of first gift recorded in Banner (Current FY-5)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_CASH_CRED_DESG_CODE_5" IS 'Designation code of first gift recorded in Banner (Current FY-5)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_CASH_CRED_DESG_DESC_5" IS 'Designation name of first gift recorded in Banner (Current FY-5)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_CASH_CRED_AMOUNT_5" IS 'Amount of first gift recorded in Banner (Current FY-5)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_CASH_CRED_YEAR_5" IS 'FY of largest single gift recorded (Current FY-5)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_CASH_CRED_DATE_5" IS 'Date of largest single gift recorded (Current FY-5)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_CASH_CRED_NUMBER_5" IS 'Gift number of largest single gift recorded (Current FY-5)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_CASH_CRED_DESG_CODE_5" IS 'Designation code of largest single gift recorded (Current FY-5)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_CASH_CRED_DESG_DESC_5" IS 'Designation name of largest single gift recorded (Current FY-5)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_CASH_CRED_AMOUNT_5" IS 'Amount of largest single gift recorded (Current FY-5)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_PLDG_CRED_YEAR_5" IS 'FY of most recent pledge recorded (Current FY-5)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_PLDG_CRED_DATE_5" IS 'Date of most recent pledge recorded (Current FY-5)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_PLDG_CRED_NUMBER_5" IS 'Pledge number of most recent pledge recorded (Current FY-5)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_PLDG_CRED_DESG_CODE_5" IS 'Designation code of most recent pledge recorded (Current FY-5)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_PLDG_CRED_DESG_DESC_5" IS 'Designation name of most recent pledge recorded (Current FY-5)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_PLDG_CRED_AMOUNT_5" IS 'Amount of most recent pledge recorded (Current FY-5)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_PLDG_CRED_YEAR_5" IS 'FY of first pledge recorded in Banner (Current FY-5)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_PLDG_CRED_DATE_5" IS 'Date of first pledge recorded in Banner (Current FY-5)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_PLDG_CRED_NUMBER_5" IS 'Pledge number of first pledge recorded in Banner (Current FY-5)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_PLDG_CRED_DESG_CODE_5" IS 'Designation code of first pledge recorded in Banner (Current FY-5)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_PLDG_CRED_DESG_DESC_5" IS 'Designation name of first pledge recorded in Banner (Current FY-5)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_PLDG_CRED_AMOUNT_5" IS 'Amount of first pledge recorded in Banner (Current FY-5)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_PLDG_CRED_YEAR_5" IS 'FY of largest single pledge recorded (Current FY-5)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_PLDG_CRED_DATE_5" IS 'Date of largest single pledge recorded (Current FY-5)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_PLDG_CRED_NUMBER_5" IS 'Pledge number of largest single pledge recorded (Current FY-5)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_PLDG_CRED_DESG_CODE_5" IS 'Designation code of largest single pledge recorded (Current FY-5)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_PLDG_CRED_DESG_DESC_5" IS 'Designation name of largest single pledge recorded (Current FY-5)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_PLDG_CRED_AMOUNT_5" IS 'Amount of largest single pledge recorded (Current FY-5)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."APS_DONOR_STATUS_5" IS 'APS Donor status at end of FY (Current FY-5)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."APS_YEARS_SINCE_5" IS 'Number of years since last in Asa Packer Society (Current FY-5)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."APS_LAST_YEAR_5" IS 'Last fiscal year of Asa Packer membership (Current FY-5)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."APS_LAST_LEVEL_CODE_5" IS 'APS Level code when last in Asa Packer Society (Current FY-5)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."APS_LAST_LEVEL_DESC_5" IS 'APS Level name when last in Asa Packer Society (Current FY-5)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."SM_DONOR_STATUS_5" IS 'SM Donor status at end of FY (Current FY-5) -- begins where DCNP_CODE >= 02';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."SM_YEARS_SINCE_5" IS 'Number of years since last in South Mtn Society (Current FY-5)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."SM_LAST_YEAR_5" IS 'Last fiscal year of Asa Packer membership (Current FY-5)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."SM_LAST_LEVEL_CODE_5" IS 'SM Level code when last in South Mtn Society (Current FY-5) -- excludes 01';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."SM_LAST_LEVEL_DESC_5" IS 'SM Level name when last in South Mtn Society (Current FY-5) -- excludes Year One';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."DONOR_STATUS_6" IS 'Donor status as of end of FY (Current FY-6)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."YEARS_SINCE_6" IS 'Number of fiscal years since last gift (Current FY-6)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_CASH_CRED_YEAR_6" IS 'FY of most recent gift made (Current FY-6)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_CASH_CRED_DATE_6" IS 'Date of most recent gift made (Current FY-6)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_CASH_CRED_NUMBER_6" IS 'Gift number of most recent gift made (Current FY-6)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_CASH_CRED_DESG_CODE_6" IS 'Designation code of most recent gift made (Current FY-6)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_CASH_CRED_DESG_DESC_6" IS 'Designation name of most recent gift made (Current FY-6)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_CASH_CRED_AMOUNT_6" IS 'Amount of most recent gift made (Current FY-6)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_CASH_CRED_YEAR_6" IS 'FY of first gift recorded in Banner (Current FY-6)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_CASH_CRED_DATE_6" IS 'Date of first gift recorded in Banner (Current FY-6)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_CASH_CRED_NUMBER_6" IS 'Gift number of first gift recorded in Banner (Current FY-6)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_CASH_CRED_DESG_CODE_6" IS 'Designation code of first gift recorded in Banner (Current FY-6)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_CASH_CRED_DESG_DESC_6" IS 'Designation name of first gift recorded in Banner (Current FY-6)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_CASH_CRED_AMOUNT_6" IS 'Amount of first gift recorded in Banner (Current FY-6)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_CASH_CRED_YEAR_6" IS 'FY of largest single gift recorded (Current FY-6)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_CASH_CRED_DATE_6" IS 'Date of largest single gift recorded (Current FY-6)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_CASH_CRED_NUMBER_6" IS 'Gift number of largest single gift recorded (Current FY-6)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_CASH_CRED_DESG_CODE_6" IS 'Designation code of largest single gift recorded (Current FY-6)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_CASH_CRED_DESG_DESC_6" IS 'Designation name of largest single gift recorded (Current FY-6)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_CASH_CRED_AMOUNT_6" IS 'Amount of largest single gift recorded (Current FY-6)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_PLDG_CRED_YEAR_6" IS 'FY of most recent pledge recorded (Current FY-6)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_PLDG_CRED_DATE_6" IS 'Date of most recent pledge recorded (Current FY-6)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_PLDG_CRED_NUMBER_6" IS 'Pledge number of most recent pledge recorded (Current FY-6)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_PLDG_CRED_DESG_CODE_6" IS 'Designation code of most recent pledge recorded (Current FY-6)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_PLDG_CRED_DESG_DESC_6" IS 'Designation name of most recent pledge recorded (Current FY-6)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_PLDG_CRED_AMOUNT_6" IS 'Amount of most recent pledge recorded (Current FY-6)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_PLDG_CRED_YEAR_6" IS 'FY of first pledge recorded in Banner (Current FY-6)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_PLDG_CRED_DATE_6" IS 'Date of first pledge recorded in Banner (Current FY-6)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_PLDG_CRED_NUMBER_6" IS 'Pledge number of first pledge recorded in Banner (Current FY-6)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_PLDG_CRED_DESG_CODE_6" IS 'Designation code of first pledge recorded in Banner (Current FY-6)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_PLDG_CRED_DESG_DESC_6" IS 'Designation name of first pledge recorded in Banner (Current FY-6)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_PLDG_CRED_AMOUNT_6" IS 'Amount of first pledge recorded in Banner (Current FY-6)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_PLDG_CRED_YEAR_6" IS 'FY of largest single pledge recorded (Current FY-6)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_PLDG_CRED_DATE_6" IS 'Date of largest single pledge recorded (Current FY-6)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_PLDG_CRED_NUMBER_6" IS 'Pledge number of largest single pledge recorded (Current FY-6)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_PLDG_CRED_DESG_CODE_6" IS 'Designation code of largest single pledge recorded (Current FY-6)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_PLDG_CRED_DESG_DESC_6" IS 'Designation name of largest single pledge recorded (Current FY-6)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_PLDG_CRED_AMOUNT_6" IS 'Amount of largest single pledge recorded (Current FY-6)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."APS_DONOR_STATUS_6" IS 'APS Donor status at end of FY (Current FY-6)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."APS_YEARS_SINCE_6" IS 'Number of years since last in Asa Packer Society (Current FY-6)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."APS_LAST_YEAR_6" IS 'Last fiscal year of Asa Packer membership (Current FY-6)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."APS_LAST_LEVEL_CODE_6" IS 'APS Level code when last in Asa Packer Society (Current FY-6)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."APS_LAST_LEVEL_DESC_6" IS 'APS Level name when last in Asa Packer Society (Current FY-6)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."SM_DONOR_STATUS_6" IS 'SM Donor status at end of FY (Current FY-6) -- begins where DCNP_CODE >= 02';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."SM_YEARS_SINCE_6" IS 'Number of years since last in South Mtn Society (Current FY-6)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."SM_LAST_YEAR_6" IS 'Last fiscal year of Asa Packer membership (Current FY-6)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."SM_LAST_LEVEL_CODE_6" IS 'SM Level code when last in South Mtn Society (Current FY-6) -- excludes 01';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."SM_LAST_LEVEL_DESC_6" IS 'SM Level name when last in South Mtn Society (Current FY-6) -- excludes Year One';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."DONOR_STATUS_7" IS 'Donor status as of end of FY (Current FY-7)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."YEARS_SINCE_7" IS 'Number of fiscal years since last gift (Current FY-7)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_CASH_CRED_YEAR_7" IS 'FY of most recent gift made (Current FY-7)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_CASH_CRED_DATE_7" IS 'Date of most recent gift made (Current FY-7)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_CASH_CRED_NUMBER_7" IS 'Gift number of most recent gift made (Current FY-7)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_CASH_CRED_DESG_CODE_7" IS 'Designation code of most recent gift made (Current FY-7)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_CASH_CRED_DESG_DESC_7" IS 'Designation name of most recent gift made (Current FY-7)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_CASH_CRED_AMOUNT_7" IS 'Amount of most recent gift made (Current FY-7)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_CASH_CRED_YEAR_7" IS 'FY of first gift recorded in Banner (Current FY-7)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_CASH_CRED_DATE_7" IS 'Date of first gift recorded in Banner (Current FY-7)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_CASH_CRED_NUMBER_7" IS 'Gift number of first gift recorded in Banner (Current FY-7)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_CASH_CRED_DESG_CODE_7" IS 'Designation code of first gift recorded in Banner (Current FY-7)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_CASH_CRED_DESG_DESC_7" IS 'Designation name of first gift recorded in Banner (Current FY-7)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_CASH_CRED_AMOUNT_7" IS 'Amount of first gift recorded in Banner (Current FY-7)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_CASH_CRED_YEAR_7" IS 'FY of largest single gift recorded (Current FY-7)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_CASH_CRED_DATE_7" IS 'Date of largest single gift recorded (Current FY-7)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_CASH_CRED_NUMBER_7" IS 'Gift number of largest single gift recorded (Current FY-7)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_CASH_CRED_DESG_CODE_7" IS 'Designation code of largest single gift recorded (Current FY-7)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_CASH_CRED_DESG_DESC_7" IS 'Designation name of largest single gift recorded (Current FY-7)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_CASH_CRED_AMOUNT_7" IS 'Amount of largest single gift recorded (Current FY-7)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_PLDG_CRED_YEAR_7" IS 'FY of most recent pledge recorded (Current FY-7)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_PLDG_CRED_DATE_7" IS 'Date of most recent pledge recorded (Current FY-7)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_PLDG_CRED_NUMBER_7" IS 'Pledge number of most recent pledge recorded (Current FY-7)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_PLDG_CRED_DESG_CODE_7" IS 'Designation code of most recent pledge recorded (Current FY-7)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_PLDG_CRED_DESG_DESC_7" IS 'Designation name of most recent pledge recorded (Current FY-7)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_PLDG_CRED_AMOUNT_7" IS 'Amount of most recent pledge recorded (Current FY-7)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_PLDG_CRED_YEAR_7" IS 'FY of first pledge recorded in Banner (Current FY-7)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_PLDG_CRED_DATE_7" IS 'Date of first pledge recorded in Banner (Current FY-7)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_PLDG_CRED_NUMBER_7" IS 'Pledge number of first pledge recorded in Banner (Current FY-7)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_PLDG_CRED_DESG_CODE_7" IS 'Designation code of first pledge recorded in Banner (Current FY-7)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_PLDG_CRED_DESG_DESC_7" IS 'Designation name of first pledge recorded in Banner (Current FY-7)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_PLDG_CRED_AMOUNT_7" IS 'Amount of first pledge recorded in Banner (Current FY-7)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_PLDG_CRED_YEAR_7" IS 'FY of largest single pledge recorded (Current FY-7)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_PLDG_CRED_DATE_7" IS 'Date of largest single pledge recorded (Current FY-7)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_PLDG_CRED_NUMBER_7" IS 'Pledge number of largest single pledge recorded (Current FY-7)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_PLDG_CRED_DESG_CODE_7" IS 'Designation code of largest single pledge recorded (Current FY-7)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_PLDG_CRED_DESG_DESC_7" IS 'Designation name of largest single pledge recorded (Current FY-7)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_PLDG_CRED_AMOUNT_7" IS 'Amount of largest single pledge recorded (Current FY-7)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."APS_DONOR_STATUS_7" IS 'APS Donor status at end of FY (Current FY-7)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."APS_YEARS_SINCE_7" IS 'Number of years since last in Asa Packer Society (Current FY-7)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."APS_LAST_YEAR_7" IS 'Last fiscal year of Asa Packer membership (Current FY-7)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."APS_LAST_LEVEL_CODE_7" IS 'APS Level code when last in Asa Packer Society (Current FY-7)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."APS_LAST_LEVEL_DESC_7" IS 'APS Level name when last in Asa Packer Society (Current FY-7)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."SM_DONOR_STATUS_7" IS 'SM Donor status at end of FY (Current FY-7) -- begins where DCNP_CODE >= 02';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."SM_YEARS_SINCE_7" IS 'Number of years since last in South Mtn Society (Current FY-7)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."SM_LAST_YEAR_7" IS 'Last fiscal year of Asa Packer membership (Current FY-7)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."SM_LAST_LEVEL_CODE_7" IS 'SM Level code when last in South Mtn Society (Current FY-7) -- excludes 01';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."SM_LAST_LEVEL_DESC_7" IS 'SM Level name when last in South Mtn Society (Current FY-7) -- excludes Year One';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."DONOR_STATUS_8" IS 'Donor status as of end of FY (Current FY-8)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."YEARS_SINCE_8" IS 'Number of fiscal years since last gift (Current FY-8)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_CASH_CRED_YEAR_8" IS 'FY of most recent gift made (Current FY-8)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_CASH_CRED_DATE_8" IS 'Date of most recent gift made (Current FY-8)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_CASH_CRED_NUMBER_8" IS 'Gift number of most recent gift made (Current FY-8)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_CASH_CRED_DESG_CODE_8" IS 'Designation code of most recent gift made (Current FY-8)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_CASH_CRED_DESG_DESC_8" IS 'Designation name of most recent gift made (Current FY-8)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_CASH_CRED_AMOUNT_8" IS 'Amount of most recent gift made (Current FY-8)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_CASH_CRED_YEAR_8" IS 'FY of first gift recorded in Banner (Current FY-8)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_CASH_CRED_DATE_8" IS 'Date of first gift recorded in Banner (Current FY-8)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_CASH_CRED_NUMBER_8" IS 'Gift number of first gift recorded in Banner (Current FY-8)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_CASH_CRED_DESG_CODE_8" IS 'Designation code of first gift recorded in Banner (Current FY-8)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_CASH_CRED_DESG_DESC_8" IS 'Designation name of first gift recorded in Banner (Current FY-8)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_CASH_CRED_AMOUNT_8" IS 'Amount of first gift recorded in Banner (Current FY-8)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_CASH_CRED_YEAR_8" IS 'FY of largest single gift recorded (Current FY-8)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_CASH_CRED_DATE_8" IS 'Date of largest single gift recorded (Current FY-8)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_CASH_CRED_NUMBER_8" IS 'Gift number of largest single gift recorded (Current FY-8)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_CASH_CRED_DESG_CODE_8" IS 'Designation code of largest single gift recorded (Current FY-8)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_CASH_CRED_DESG_DESC_8" IS 'Designation name of largest single gift recorded (Current FY-8)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_CASH_CRED_AMOUNT_8" IS 'Amount of largest single gift recorded (Current FY-8)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_PLDG_CRED_YEAR_8" IS 'FY of most recent pledge recorded (Current FY-8)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_PLDG_CRED_DATE_8" IS 'Date of most recent pledge recorded (Current FY-8)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_PLDG_CRED_NUMBER_8" IS 'Pledge number of most recent pledge recorded (Current FY-8)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_PLDG_CRED_DESG_CODE_8" IS 'Designation code of most recent pledge recorded (Current FY-8)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_PLDG_CRED_DESG_DESC_8" IS 'Designation name of most recent pledge recorded (Current FY-8)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_PLDG_CRED_AMOUNT_8" IS 'Amount of most recent pledge recorded (Current FY-8)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_PLDG_CRED_YEAR_8" IS 'FY of first pledge recorded in Banner (Current FY-8)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_PLDG_CRED_DATE_8" IS 'Date of first pledge recorded in Banner (Current FY-8)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_PLDG_CRED_NUMBER_8" IS 'Pledge number of first pledge recorded in Banner (Current FY-8)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_PLDG_CRED_DESG_CODE_8" IS 'Designation code of first pledge recorded in Banner (Current FY-8)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_PLDG_CRED_DESG_DESC_8" IS 'Designation name of first pledge recorded in Banner (Current FY-8)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_PLDG_CRED_AMOUNT_8" IS 'Amount of first pledge recorded in Banner (Current FY-8)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_PLDG_CRED_YEAR_8" IS 'FY of largest single pledge recorded (Current FY-8)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_PLDG_CRED_DATE_8" IS 'Date of largest single pledge recorded (Current FY-8)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_PLDG_CRED_NUMBER_8" IS 'Pledge number of largest single pledge recorded (Current FY-8)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_PLDG_CRED_DESG_CODE_8" IS 'Designation code of largest single pledge recorded (Current FY-8)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_PLDG_CRED_DESG_DESC_8" IS 'Designation name of largest single pledge recorded (Current FY-8)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_PLDG_CRED_AMOUNT_8" IS 'Amount of largest single pledge recorded (Current FY-8)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."APS_DONOR_STATUS_8" IS 'APS Donor status at end of FY (Current FY-8)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."APS_YEARS_SINCE_8" IS 'Number of years since last in Asa Packer Society (Current FY-8)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."APS_LAST_YEAR_8" IS 'Last fiscal year of Asa Packer membership (Current FY-8)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."APS_LAST_LEVEL_CODE_8" IS 'APS Level code when last in Asa Packer Society (Current FY-8)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."APS_LAST_LEVEL_DESC_8" IS 'APS Level name when last in Asa Packer Society (Current FY-8)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."SM_DONOR_STATUS_8" IS 'SM Donor status at end of FY (Current FY-8) -- begins where DCNP_CODE >= 02';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."SM_YEARS_SINCE_8" IS 'Number of years since last in South Mtn Society (Current FY-8)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."SM_LAST_YEAR_8" IS 'Last fiscal year of Asa Packer membership (Current FY-8)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."SM_LAST_LEVEL_CODE_8" IS 'SM Level code when last in South Mtn Society (Current FY-8) -- excludes 01';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."SM_LAST_LEVEL_DESC_8" IS 'SM Level name when last in South Mtn Society (Current FY-8) -- excludes Year One';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."DONOR_STATUS_9" IS 'Donor status as of end of FY (Current FY-9)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."YEARS_SINCE_9" IS 'Number of fiscal years since last gift (Current FY-9)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_CASH_CRED_YEAR_9" IS 'FY of most recent gift made (Current FY-9)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_CASH_CRED_DATE_9" IS 'Date of most recent gift made (Current FY-9)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_CASH_CRED_NUMBER_9" IS 'Gift number of most recent gift made (Current FY-9)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_CASH_CRED_DESG_CODE_9" IS 'Designation code of most recent gift made (Current FY-9)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_CASH_CRED_DESG_DESC_9" IS 'Designation name of most recent gift made (Current FY-9)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_CASH_CRED_AMOUNT_9" IS 'Amount of most recent gift made (Current FY-9)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_CASH_CRED_YEAR_9" IS 'FY of first gift recorded in Banner (Current FY-9)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_CASH_CRED_DATE_9" IS 'Date of first gift recorded in Banner (Current FY-9)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_CASH_CRED_NUMBER_9" IS 'Gift number of first gift recorded in Banner (Current FY-9)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_CASH_CRED_DESG_CODE_9" IS 'Designation code of first gift recorded in Banner (Current FY-9)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_CASH_CRED_DESG_DESC_9" IS 'Designation name of first gift recorded in Banner (Current FY-9)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_CASH_CRED_AMOUNT_9" IS 'Amount of first gift recorded in Banner (Current FY-9)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_CASH_CRED_YEAR_9" IS 'FY of largest single gift recorded (Current FY-9)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_CASH_CRED_DATE_9" IS 'Date of largest single gift recorded (Current FY-9)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_CASH_CRED_NUMBER_9" IS 'Gift number of largest single gift recorded (Current FY-9)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_CASH_CRED_DESG_CODE_9" IS 'Designation code of largest single gift recorded (Current FY-9)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_CASH_CRED_DESG_DESC_9" IS 'Designation name of largest single gift recorded (Current FY-9)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_CASH_CRED_AMOUNT_9" IS 'Amount of largest single gift recorded (Current FY-9)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_PLDG_CRED_YEAR_9" IS 'FY of most recent pledge recorded (Current FY-9)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_PLDG_CRED_DATE_9" IS 'Date of most recent pledge recorded (Current FY-9)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_PLDG_CRED_NUMBER_9" IS 'Pledge number of most recent pledge recorded (Current FY-9)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_PLDG_CRED_DESG_CODE_9" IS 'Designation code of most recent pledge recorded (Current FY-9)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_PLDG_CRED_DESG_DESC_9" IS 'Designation name of most recent pledge recorded (Current FY-9)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LAST_PLDG_CRED_AMOUNT_9" IS 'Amount of most recent pledge recorded (Current FY-9)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_PLDG_CRED_YEAR_9" IS 'FY of first pledge recorded in Banner (Current FY-9)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_PLDG_CRED_DATE_9" IS 'Date of first pledge recorded in Banner (Current FY-9)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_PLDG_CRED_NUMBER_9" IS 'Pledge number of first pledge recorded in Banner (Current FY-9)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_PLDG_CRED_DESG_CODE_9" IS 'Designation code of first pledge recorded in Banner (Current FY-9)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_PLDG_CRED_DESG_DESC_9" IS 'Designation name of first pledge recorded in Banner (Current FY-9)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."FIRST_PLDG_CRED_AMOUNT_9" IS 'Amount of first pledge recorded in Banner (Current FY-9)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_PLDG_CRED_YEAR_9" IS 'FY of largest single pledge recorded (Current FY-9)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_PLDG_CRED_DATE_9" IS 'Date of largest single pledge recorded (Current FY-9)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_PLDG_CRED_NUMBER_9" IS 'Pledge number of largest single pledge recorded (Current FY-9)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_PLDG_CRED_DESG_CODE_9" IS 'Designation code of largest single pledge recorded (Current FY-9)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_PLDG_CRED_DESG_DESC_9" IS 'Designation name of largest single pledge recorded (Current FY-9)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."LARGEST_PLDG_CRED_AMOUNT_9" IS 'Amount of largest single pledge recorded (Current FY-9)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."APS_DONOR_STATUS_9" IS 'Number of years since last in Asa Packer Society (Current FY-9)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."APS_YEARS_SINCE_9" IS 'APS Donor status at end of FY (Current FY-9)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."APS_LAST_YEAR_9" IS 'Last fiscal year of Asa Packer membership (Current FY-9)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."APS_LAST_LEVEL_CODE_9" IS 'APS Level code when last in Asa Packer Society (Current FY-9)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."APS_LAST_LEVEL_DESC_9" IS 'APS Level name when last in Asa Packer Society (Current FY-9)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."SM_DONOR_STATUS_9" IS 'SM Donor status at end of FY (Current FY-9) -- begins where DCNP_CODE >= 02';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."SM_YEARS_SINCE_9" IS 'Number of years since last in South Mtn Society (Current FY-9)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."SM_LAST_YEAR_9" IS 'Last fiscal year of Asa Packer membership (Current FY-9)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."SM_LAST_LEVEL_CODE_9" IS 'SM Level code when last in South Mtn Society (Current FY-9) -- excludes 01';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS_BY_ID"."SM_LAST_LEVEL_DESC_9" IS 'SM Level name when last in South Mtn Society (Current FY-9) -- excludes Year One';

  CREATE INDEX "PENTAHO"."C_CN_DNR_STAT_ID_APS_STATUS" ON "PENTAHO"."C_CN_DONOR_STATUS_BY_ID" ("APS_DONOR_STATUS_0") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERSPACE" ;

  CREATE INDEX "PENTAHO"."C_CN_DNR_STAT_ID_BANNER_ID" ON "PENTAHO"."C_CN_DONOR_STATUS_BY_ID" ("BANNER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERSPACE" ;

  CREATE INDEX "PENTAHO"."C_CN_DNR_STAT_ID_DONOR_STATUS" ON "PENTAHO"."C_CN_DONOR_STATUS_BY_ID" ("DONOR_STATUS_0") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERSPACE" ;

  CREATE INDEX "PENTAHO"."C_CN_DNR_STAT_ID_ENTITY_CODE" ON "PENTAHO"."C_CN_DONOR_STATUS_BY_ID" ("ENTITY_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERSPACE" ;

  CREATE UNIQUE INDEX "PENTAHO"."C_CN_DNR_STAT_ID_IDENTITY" ON "PENTAHO"."C_CN_DONOR_STATUS_BY_ID" ("PIDM", "BANNER_ID", "NAME_SORT", "ENTITY_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERSPACE" ;

  CREATE INDEX "PENTAHO"."C_CN_DNR_STAT_ID_NAME_SORT" ON "PENTAHO"."C_CN_DONOR_STATUS_BY_ID" ("NAME_SORT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERSPACE" ;

  CREATE INDEX "PENTAHO"."C_CN_DNR_STAT_ID_SM_STATUS" ON "PENTAHO"."C_CN_DONOR_STATUS_BY_ID" ("SM_DONOR_STATUS_0") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERSPACE" ;