/*BEGIN
  dbms_snapshot.REFRESH('C_CN_CHIILDREN_BY_ID');
END; */

CREATE MATERIALIZED VIEW LOG ON H_CN_CHILDREN_BY_ID;

CREATE MATERIALIZED VIEW C_CN_CHILDREN_BY_ID refresh FORCE ON demand
AS
  SELECT PIDM
  , BANNER_ID
  , NAME_SORT
  , ENTITY_CODE
  , RECORD_START_DATE
  , RECORD_END_DATE
  , CHILD_01_SEQNO
  , CHILD_01_PIDM
  , CHILD_01_BANNER_ID
  , CHILD_01_LAST_NAME
  , CHILD_01_FIRST_NAME
  , CHILD_01_MIDDLE_NAME
  , CHILD_01_NAME_PREFIX
  , CHILD_01_GENDER
  , CHILD_01_GENDER_DESC
  , CHILD_01_DATE_BIRTH
  , (CASE
        WHEN CHILD_01_DATE_DECEASED IS NULL THEN TRUNC((sysdate - CHILD_01_DATE_BIRTH)/365.25)
        ELSE TRUNC((CHILD_01_DATE_DECEASED                      - CHILD_01_DATE_BIRTH)/365.25)
      END) AS CHILD_01_AGE
  , CHILD_01_DEAD_IND
  , CHILD_01_DATE_DECEASED
  , CHILD_01_XREF_CODE
  , CHILD_01_XREF_DESC
  , CHILD_02_SEQNO
  , CHILD_02_PIDM
  , CHILD_02_BANNER_ID
  , CHILD_02_LAST_NAME
  , CHILD_02_FIRST_NAME
  , CHILD_02_MIDDLE_NAME
  , CHILD_02_NAME_PREFIX
  , CHILD_02_GENDER
  , CHILD_02_GENDER_DESC
  , CHILD_02_DATE_BIRTH
  , (CASE
        WHEN CHILD_02_DATE_DECEASED IS NULL THEN TRUNC((sysdate - CHILD_02_DATE_BIRTH)/365.25)
        ELSE TRUNC((CHILD_02_DATE_DECEASED                      - CHILD_02_DATE_BIRTH)/365.25)
      END) AS CHILD_02_AGE
  , CHILD_02_DEAD_IND
  , CHILD_02_DATE_DECEASED
  , CHILD_02_XREF_CODE
  , CHILD_02_XREF_DESC
  , CHILD_03_SEQNO
  , CHILD_03_PIDM
  , CHILD_03_BANNER_ID
  , CHILD_03_LAST_NAME
  , CHILD_03_FIRST_NAME
  , CHILD_03_MIDDLE_NAME
  , CHILD_03_NAME_PREFIX
  , CHILD_03_GENDER
  , CHILD_03_GENDER_DESC
  , CHILD_03_DATE_BIRTH
  , (CASE
        WHEN CHILD_03_DATE_DECEASED IS NULL THEN TRUNC((sysdate - CHILD_03_DATE_BIRTH)/365.25)
        ELSE TRUNC((CHILD_03_DATE_DECEASED                      - CHILD_03_DATE_BIRTH)/365.25)
      END) AS CHILD_03_AGE
  , CHILD_03_DEAD_IND
  , CHILD_03_DATE_DECEASED
  , CHILD_03_XREF_CODE
  , CHILD_03_XREF_DESC
  , CHILD_04_SEQNO
  , CHILD_04_PIDM
  , CHILD_04_BANNER_ID
  , CHILD_04_LAST_NAME
  , CHILD_04_FIRST_NAME
  , CHILD_04_MIDDLE_NAME
  , CHILD_04_NAME_PREFIX
  , CHILD_04_GENDER
  , CHILD_04_GENDER_DESC
  , CHILD_04_DATE_BIRTH
  , (CASE
        WHEN CHILD_04_DATE_DECEASED IS NULL THEN TRUNC((sysdate - CHILD_04_DATE_BIRTH)/365.25)
        ELSE TRUNC((CHILD_04_DATE_DECEASED                      - CHILD_04_DATE_BIRTH)/365.25)
      END) AS CHILD_04_AGE
  , CHILD_04_DEAD_IND
  , CHILD_04_DATE_DECEASED
  , CHILD_04_XREF_CODE
  , CHILD_04_XREF_DESC
  , CHILD_05_SEQNO
  , CHILD_05_PIDM
  , CHILD_05_BANNER_ID
  , CHILD_05_LAST_NAME
  , CHILD_05_FIRST_NAME
  , CHILD_05_MIDDLE_NAME
  , CHILD_05_NAME_PREFIX
  , CHILD_05_GENDER
  , CHILD_05_GENDER_DESC
  , CHILD_05_DATE_BIRTH
  , (CASE
        WHEN CHILD_05_DATE_DECEASED IS NULL THEN TRUNC((sysdate - CHILD_05_DATE_BIRTH)/365.25)
        ELSE TRUNC((CHILD_05_DATE_DECEASED                      - CHILD_05_DATE_BIRTH)/365.25)
      END) AS CHILD_05_AGE
  , CHILD_05_DEAD_IND
  , CHILD_05_DATE_DECEASED
  , CHILD_05_XREF_CODE
  , CHILD_05_XREF_DESC
  , CHILD_06_SEQNO
  , CHILD_06_PIDM
  , CHILD_06_BANNER_ID
  , CHILD_06_LAST_NAME
  , CHILD_06_FIRST_NAME
  , CHILD_06_MIDDLE_NAME
  , CHILD_06_NAME_PREFIX
  , CHILD_06_GENDER
  , CHILD_06_GENDER_DESC
  , CHILD_06_DATE_BIRTH
  , (CASE
        WHEN CHILD_06_DATE_DECEASED IS NULL THEN TRUNC((sysdate - CHILD_06_DATE_BIRTH)/365.25)
        ELSE TRUNC((CHILD_06_DATE_DECEASED                      - CHILD_06_DATE_BIRTH)/365.25)
      END) AS CHILD_06_AGE
  , CHILD_06_DEAD_IND
  , CHILD_06_DATE_DECEASED
  , CHILD_06_XREF_CODE
  , CHILD_06_XREF_DESC
  , CHILD_07_SEQNO
  , CHILD_07_PIDM
  , CHILD_07_BANNER_ID
  , CHILD_07_LAST_NAME
  , CHILD_07_FIRST_NAME
  , CHILD_07_MIDDLE_NAME
  , CHILD_07_NAME_PREFIX
  , CHILD_07_GENDER
  , CHILD_07_GENDER_DESC
  , CHILD_07_DATE_BIRTH
  , (CASE
        WHEN CHILD_07_DATE_DECEASED IS NULL THEN TRUNC((sysdate - CHILD_07_DATE_BIRTH)/365.25)
        ELSE TRUNC((CHILD_07_DATE_DECEASED                      - CHILD_07_DATE_BIRTH)/365.25)
      END) AS CHILD_07_AGE
  , CHILD_07_DEAD_IND
  , CHILD_07_DATE_DECEASED
  , CHILD_07_XREF_CODE
  , CHILD_07_XREF_DESC
  , CHILD_08_SEQNO
  , CHILD_08_PIDM
  , CHILD_08_BANNER_ID
  , CHILD_08_LAST_NAME
  , CHILD_08_FIRST_NAME
  , CHILD_08_MIDDLE_NAME
  , CHILD_08_NAME_PREFIX
  , CHILD_08_GENDER
  , CHILD_08_GENDER_DESC
  , CHILD_08_DATE_BIRTH
  , (CASE
        WHEN CHILD_08_DATE_DECEASED IS NULL THEN TRUNC((sysdate - CHILD_08_DATE_BIRTH)/365.25)
        ELSE TRUNC((CHILD_08_DATE_DECEASED                      - CHILD_08_DATE_BIRTH)/365.25)
      END) AS CHILD_08_AGE
  , CHILD_08_DEAD_IND
  , CHILD_08_DATE_DECEASED
  , CHILD_08_XREF_CODE
  , CHILD_08_XREF_DESC
  , CHILD_09_SEQNO
  , CHILD_09_PIDM
  , CHILD_09_BANNER_ID
  , CHILD_09_LAST_NAME
  , CHILD_09_FIRST_NAME
  , CHILD_09_MIDDLE_NAME
  , CHILD_09_NAME_PREFIX
  , CHILD_09_GENDER
  , CHILD_09_GENDER_DESC
  , CHILD_09_DATE_BIRTH
  , (CASE
        WHEN CHILD_09_DATE_DECEASED IS NULL THEN TRUNC((sysdate - CHILD_09_DATE_BIRTH)/365.25)
        ELSE TRUNC((CHILD_09_DATE_DECEASED                      - CHILD_09_DATE_BIRTH)/365.25)
      END) AS CHILD_09_AGE
  , CHILD_09_DEAD_IND
  , CHILD_09_DATE_DECEASED
  , CHILD_09_XREF_CODE
  , CHILD_09_XREF_DESC
  , CHILD_10_SEQNO
  , CHILD_10_PIDM
  , CHILD_10_BANNER_ID
  , CHILD_10_LAST_NAME
  , CHILD_10_FIRST_NAME
  , CHILD_10_MIDDLE_NAME
  , CHILD_10_NAME_PREFIX
  , CHILD_10_GENDER
  , CHILD_10_GENDER_DESC
  , CHILD_10_DATE_BIRTH
  , (CASE
        WHEN CHILD_10_DATE_DECEASED IS NULL THEN TRUNC((sysdate - CHILD_10_DATE_BIRTH)/365.25)
        ELSE TRUNC((CHILD_10_DATE_DECEASED                      - CHILD_10_DATE_BIRTH)/365.25)
      END) AS CHILD_10_AGE
  , CHILD_10_DEAD_IND
  , CHILD_10_DATE_DECEASED
  , CHILD_10_XREF_CODE
  , CHILD_10_XREF_DESC
  , CHILD_11_SEQNO
  , CHILD_11_PIDM
  , CHILD_11_BANNER_ID
  , CHILD_11_LAST_NAME
  , CHILD_11_FIRST_NAME
  , CHILD_11_MIDDLE_NAME
  , CHILD_11_NAME_PREFIX
  , CHILD_11_GENDER
  , CHILD_11_GENDER_DESC
  , CHILD_11_DATE_BIRTH
  , (CASE
        WHEN CHILD_11_DATE_DECEASED IS NULL THEN TRUNC((sysdate - CHILD_11_DATE_BIRTH)/365.25)
        ELSE TRUNC((CHILD_11_DATE_DECEASED                      - CHILD_11_DATE_BIRTH)/365.25)
      END) AS CHILD_11_AGE
  , CHILD_11_DEAD_IND
  , CHILD_11_DATE_DECEASED
  , CHILD_11_XREF_CODE
  , CHILD_11_XREF_DESC
  , CHILD_12_SEQNO
  , CHILD_12_PIDM
  , CHILD_12_BANNER_ID
  , CHILD_12_LAST_NAME
  , CHILD_12_FIRST_NAME
  , CHILD_12_MIDDLE_NAME
  , CHILD_12_NAME_PREFIX
  , CHILD_12_GENDER
  , CHILD_12_GENDER_DESC
  , CHILD_12_DATE_BIRTH
  , (CASE
        WHEN CHILD_12_DATE_DECEASED IS NULL THEN TRUNC((sysdate - CHILD_12_DATE_BIRTH)/365.25)
        ELSE TRUNC((CHILD_12_DATE_DECEASED                      - CHILD_12_DATE_BIRTH)/365.25)
      END) AS CHILD_12_AGE
  , CHILD_12_DEAD_IND
  , CHILD_12_DATE_DECEASED
  , CHILD_12_XREF_CODE
  , CHILD_12_XREF_DESC
  , CHILD_13_SEQNO
  , CHILD_13_PIDM
  , CHILD_13_BANNER_ID
  , CHILD_13_LAST_NAME
  , CHILD_13_FIRST_NAME
  , CHILD_13_MIDDLE_NAME
  , CHILD_13_NAME_PREFIX
  , CHILD_13_GENDER
  , CHILD_13_GENDER_DESC
  , CHILD_13_DATE_BIRTH
  , (CASE
        WHEN CHILD_13_DATE_DECEASED IS NULL THEN TRUNC((sysdate - CHILD_13_DATE_BIRTH)/365.25)
        ELSE TRUNC((CHILD_13_DATE_DECEASED                      - CHILD_13_DATE_BIRTH)/365.25)
      END) AS CHILD_13_AGE
  , CHILD_13_DEAD_IND
  , CHILD_13_DATE_DECEASED
  , CHILD_13_XREF_CODE
  , CHILD_13_XREF_DESC
  , CHILD_14_SEQNO
  , CHILD_14_PIDM
  , CHILD_14_BANNER_ID
  , CHILD_14_LAST_NAME
  , CHILD_14_FIRST_NAME
  , CHILD_14_MIDDLE_NAME
  , CHILD_14_NAME_PREFIX
  , CHILD_14_GENDER
  , CHILD_14_GENDER_DESC
  , CHILD_14_DATE_BIRTH
  , (CASE
        WHEN CHILD_14_DATE_DECEASED IS NULL THEN TRUNC((sysdate - CHILD_14_DATE_BIRTH)/365.25)
        ELSE TRUNC((CHILD_14_DATE_DECEASED                      - CHILD_14_DATE_BIRTH)/365.25)
      END) AS CHILD_14_AGE
  , CHILD_14_DEAD_IND
  , CHILD_14_DATE_DECEASED
  , CHILD_14_XREF_CODE
  , CHILD_14_XREF_DESC
  FROM h_cn_children_by_id
  WHERE record_end_date IS NULL;
  
  
  CREATE INDEX C_CN_CHILDREN_ID_BANNER_ID ON C_CN_CHILDREN_BY_ID (BANNER_ID) ;
  CREATE INDEX C_CN_CHILDREN_ID_NAME_SORT ON C_CN_CHILDREN_BY_ID (NAME_SORT) ;
  CREATE INDEX C_CN_CHILDREN_ID_ENTITY ON C_CN_CHILDREN_BY_ID (ENTITY_CODE) ;
  CREATE INDEX C_CN_CHILDREN_ID_CHD_01_ID ON C_CN_CHILDREN_BY_ID (CHILD_01_BANNER_ID) ;
  CREATE INDEX C_CN_CHILDREN_ID_CHD_02_ID ON C_CN_CHILDREN_BY_ID (CHILD_02_BANNER_ID) ;
  CREATE INDEX C_CN_CHILDREN_ID_CHD_03_ID ON C_CN_CHILDREN_BY_ID (CHILD_03_BANNER_ID) ;
  CREATE INDEX C_CN_CHILDREN_ID_CHD_04_ID ON C_CN_CHILDREN_BY_ID (CHILD_04_BANNER_ID) ;
  CREATE INDEX C_CN_CHILDREN_ID_CHD_05_ID ON C_CN_CHILDREN_BY_ID (CHILD_05_BANNER_ID) ;
  CREATE INDEX C_CN_CHILDREN_ID_CHD_06_ID ON C_CN_CHILDREN_BY_ID (CHILD_06_BANNER_ID) ;
  CREATE INDEX C_CN_CHILDREN_ID_CHD_07_ID ON C_CN_CHILDREN_BY_ID (CHILD_07_BANNER_ID) ;
  CREATE INDEX C_CN_CHILDREN_ID_CHD_08_ID ON C_CN_CHILDREN_BY_ID (CHILD_08_BANNER_ID) ;
  CREATE INDEX C_CN_CHILDREN_ID_CHD_09_ID ON C_CN_CHILDREN_BY_ID (CHILD_09_BANNER_ID) ;
  CREATE INDEX C_CN_CHILDREN_ID_CHD_10_ID ON C_CN_CHILDREN_BY_ID (CHILD_10_BANNER_ID) ;
  CREATE INDEX C_CN_CHILDREN_ID_CHD_11_ID ON C_CN_CHILDREN_BY_ID (CHILD_11_BANNER_ID) ;
  CREATE INDEX C_CN_CHILDREN_ID_CHD_12_ID ON C_CN_CHILDREN_BY_ID (CHILD_12_BANNER_ID) ;
  CREATE INDEX C_CN_CHILDREN_ID_CHD_13_ID ON C_CN_CHILDREN_BY_ID (CHILD_13_BANNER_ID) ;
  CREATE INDEX C_CN_CHILDREN_ID_CHD_14_ID ON C_CN_CHILDREN_BY_ID (CHILD_14_BANNER_ID) ;
  CREATE INDEX C_CN_CHILDREN_ID_CHD_01_PIDM ON C_CN_CHILDREN_BY_ID (CHILD_01_PIDM) ;
  CREATE INDEX C_CN_CHILDREN_ID_CHD_02_PIDM ON C_CN_CHILDREN_BY_ID (CHILD_02_PIDM) ;
  CREATE INDEX C_CN_CHILDREN_ID_CHD_03_PIDM ON C_CN_CHILDREN_BY_ID (CHILD_03_PIDM) ;
  CREATE INDEX C_CN_CHILDREN_ID_CHD_04_PIDM ON C_CN_CHILDREN_BY_ID (CHILD_04_PIDM) ;
  CREATE INDEX C_CN_CHILDREN_ID_CHD_05_PIDM ON C_CN_CHILDREN_BY_ID (CHILD_05_PIDM) ;
  CREATE INDEX C_CN_CHILDREN_ID_CHD_06_PIDM ON C_CN_CHILDREN_BY_ID (CHILD_06_PIDM) ;
  CREATE INDEX C_CN_CHILDREN_ID_CHD_07_PIDM ON C_CN_CHILDREN_BY_ID (CHILD_07_PIDM) ;
  CREATE INDEX C_CN_CHILDREN_ID_CHD_08_PIDM ON C_CN_CHILDREN_BY_ID (CHILD_08_PIDM) ;
  CREATE INDEX C_CN_CHILDREN_ID_CHD_09_PIDM ON C_CN_CHILDREN_BY_ID (CHILD_09_PIDM) ;
  CREATE INDEX C_CN_CHILDREN_ID_CHD_10_PIDM ON C_CN_CHILDREN_BY_ID (CHILD_10_PIDM) ;
  CREATE INDEX C_CN_CHILDREN_ID_CHD_11_PIDM ON C_CN_CHILDREN_BY_ID (CHILD_11_PIDM) ;
  CREATE INDEX C_CN_CHILDREN_ID_CHD_12_PIDM ON C_CN_CHILDREN_BY_ID (CHILD_12_PIDM) ;
  CREATE INDEX C_CN_CHILDREN_ID_CHD_13_PIDM ON C_CN_CHILDREN_BY_ID (CHILD_13_PIDM) ;
  CREATE INDEX C_CN_CHILDREN_ID_CHD_14_PIDM ON C_CN_CHILDREN_BY_ID (CHILD_14_PIDM) ;
  CREATE INDEX C_CN_CHILDREN_ID_CHD_01_SEQNO ON C_CN_CHILDREN_BY_ID (CHILD_01_SEQNO) ;
  CREATE INDEX C_CN_CHILDREN_ID_CHD_02_SEQNO ON C_CN_CHILDREN_BY_ID (CHILD_02_SEQNO) ;
  CREATE INDEX C_CN_CHILDREN_ID_CHD_03_SEQNO ON C_CN_CHILDREN_BY_ID (CHILD_03_SEQNO) ;
  CREATE INDEX C_CN_CHILDREN_ID_CHD_04_SEQNO ON C_CN_CHILDREN_BY_ID (CHILD_04_SEQNO) ;
  CREATE INDEX C_CN_CHILDREN_ID_CHD_05_SEQNO ON C_CN_CHILDREN_BY_ID (CHILD_05_SEQNO) ;
  CREATE INDEX C_CN_CHILDREN_ID_CHD_06_SEQNO ON C_CN_CHILDREN_BY_ID (CHILD_06_SEQNO) ;
  CREATE INDEX C_CN_CHILDREN_ID_CHD_07_SEQNO ON C_CN_CHILDREN_BY_ID (CHILD_07_SEQNO) ;
  CREATE INDEX C_CN_CHILDREN_ID_CHD_08_SEQNO ON C_CN_CHILDREN_BY_ID (CHILD_08_SEQNO) ;
  CREATE INDEX C_CN_CHILDREN_ID_CHD_09_SEQNO ON C_CN_CHILDREN_BY_ID (CHILD_09_SEQNO) ;
  CREATE INDEX C_CN_CHILDREN_ID_CHD_10_SEQNO ON C_CN_CHILDREN_BY_ID (CHILD_10_SEQNO) ;
  CREATE INDEX C_CN_CHILDREN_ID_CHD_11_SEQNO ON C_CN_CHILDREN_BY_ID (CHILD_11_SEQNO) ;
  CREATE INDEX C_CN_CHILDREN_ID_CHD_12_SEQNO ON C_CN_CHILDREN_BY_ID (CHILD_12_SEQNO) ;
  CREATE INDEX C_CN_CHILDREN_ID_CHD_13_SEQNO ON C_CN_CHILDREN_BY_ID (CHILD_13_SEQNO) ;
  CREATE INDEX C_CN_CHILDREN_ID_CHD_14_SEQNO ON C_CN_CHILDREN_BY_ID (CHILD_14_SEQNO) ;
