--BEGIN
--  dbms_snapshot.REFRESH('C_CN_CHILDREN');
--END;

CREATE MATERIALIZED VIEW LOG ON H_CN_CHILDREN;

CREATE MATERIALIZED VIEW C_CN_CHILDREN refresh FORCE ON demand
AS
  SELECT PIDM
  , BANNER_ID
  , NAME_SORT
  , ENTITY_CODE
  , CHILD_SEQNO
  , CHILD_PIDM
  , CHILD_BANNER_ID
  , CHILD_LAST_NAME
  , CHILD_FIRST_NAME
  , CHILD_MIDDLE_NAME
  , CHILD_NAME_PREFIX
  , CHILD_GENDER
  , CHILD_GENDER_DESC
  , CHILD_DATE_BIRTH
  , (
      CASE
        WHEN CHILD_DATE_DECEASED IS NULL THEN TRUNC((sysdate - CHILD_DATE_BIRTH)/365.25)
        ELSE TRUNC((CHILD_DATE_DECEASED                      - CHILD_DATE_BIRTH)/365.25)
      END) AS CHILD_AGE
  , CHILD_DEAD_IND
  , CHILD_DATE_DECEASED
  , CHILD_ATYP_CODE
  , CHILD_ATYP_DESC
  , CHILD_ACTIVITY_DATE
  , CHILD_XREF_CODE
  , CHILD_XREF_DESC
  , CHILD_COMMENT
  , CHILD_LU_CLASS
  , DISP_WEB_IND
  , OK_FOR_NOTES_IND
  , DISP_NOTES_IND
  , DISP_NOTES_DATE
  , CHILD_USER
  , REVIEWED_IND
  , REVIEWED_USER
  , USER_ID
  , DATA_ORIGIN
  , CHILD_APRCHLD_SEQNO
  , RECORD_START_DATE
  FROM h_cn_children
  WHERE record_end_date IS NULL;
  
    CREATE INDEX "PENTAHO"."C_CN_CHILDREN_IDX" ON "PENTAHO"."C_CN_CHILDREN" (PIDM, CHILD_SEQNO); 
    CREATE INDEX "PENTAHO"."C_CN_CHILDREN_START_DATE" ON "PENTAHO"."C_CN_CHILDREN" (PIDM, CHILD_SEQNO, RECORD_START_DATE);
    
