--BEGIN
--  dbms_snapshot.REFRESH('C_CN_EDUCATION');
--END;

--CREATE MATERIALIZED VIEW LOG ON H_CN_EDUCATION;

CREATE MATERIALIZED VIEW C_CN_EDUCATION refresh FAST ON demand
AS
  SELECT
    PIDM
  , BANNER_ID
  , NAME_SORT
  , ENTITY_CODE
  , EDUC_SEQNO
  , SCHOOL_CODE
  , SCHOOL_DESC
  , SCHOOL_CITY
  , SCHOOL_STATE_CODE
  , SCHOOL_STATE_DESC
  , SCHOOL_ZIPCODE
  , SCHOOL_NATION_CODE
  , SCHOOL_NATION_DESC
  , DEGREE_CODE
  , DEGREE_DESC
  , DEGREE_DATE
  , COLLEGE_CODE
  , COLLEGE_DESC
  , ACTIVITY_DATE
  , DEGREE_YEAR
  , DEGREE_YEAR_BULLETIN
  , CAMPUS_CODE
  , CAMPUS_DESC
  , DEPT_CODE_1
  , DEPT_DESC_1
  , DEPT_CODE_2
  , DEPT_DESC_2
  , COMMENTS
  , MAJOR_COMMENT
  , MAJOR_CODE_1
  , MAJOR_DESC_1
  , MAJOR_CODE_2
  , MAJOR_DESC_2
  , MAJOR_CODE_3
  , MAJOR_DESC_3
  , MAJOR_CODE_4
  , MAJOR_DESC_4
  , MAJR_CODE_MINR_1
  , MINOR_DESC_1
  , MAJR_CODE_MINR_2
  , MINOR_DESC_2
  , MAJR_CODE_CONC_1
  , CONC_DESC_1
  , MAJR_CODE_CONC_2
  , CONC_DESC_2
  , MAJR_CODE_CONC_3
  , CONC_DESC_3
  , HONR_CODE_1
  , HONR_DESC_1
  , HONR_CODE_2
  , HONR_DESC_2
  , HONR_CODE_3
  , HONR_DESC_3
  , HONR_CODE_4
  , HONR_DESC_4
  , HOND_CODE_1
  , HOND_DESC_1
  , HOND_CODE_2
  , HOND_DESC_2
  , HOND_CODE_3
  , HOND_DESC_3
  , HOND_CODE_4
  , HOND_DESC_4
  , OK_FOR_NOTES_IND
  , DISP_NOTES_IND
  , DISP_NOTES_DATE
  , REVIEWED_IND
  , REVIEWED_USER
  , USER_ID
  , DATA_ORIGIN
  , RECORD_START_DATE
  FROM
    h_cn_EDUCATION
  WHERE
    record_end_date IS NULL;
    
    
  CREATE INDEX C_CN_EDUCATION_IDX ON C_CN_EDUCATION (PIDM, EDUC_SEQNO);
  CREATE INDEX C_CN_EDUCATION_BANNER_ID ON C_CN_EDUCATION (BANNER_ID);
  CREATE INDEX C_CN_EDUCATION_NAME_SORT ON C_CN_EDUCATION (NAME_SORT);
  CREATE INDEX C_CN_EDUCATION_ENTITY ON C_CN_EDUCATION (ENTITY_CODE);
  CREATE INDEX C_CN_EDUCATION_SCH_CODE ON C_CN_EDUCATION (SCHOOL_CODE);
  CREATE INDEX C_CN_EDUCATION_STATE_CODE ON C_CN_EDUCATION (SCHOOL_STATE_CODE);
  CREATE INDEX C_CN_EDUCATION_ZIPCODE ON C_CN_EDUCATION (SCHOOL_ZIPCODE);
  CREATE INDEX C_CN_EDUCATION_NATION_CODE ON C_CN_EDUCATION (SCHOOL_NATION_CODE);
  CREATE INDEX C_CN_EDUCATION_DEGREE_CODE ON C_CN_EDUCATION (DEGREE_CODE);
  CREATE INDEX C_CN_EDUCATION_COLLEGE_CODE ON C_CN_EDUCATION (COLLEGE_CODE);
  CREATE INDEX C_CN_EDUCATION_DEGREE_YEAR ON C_CN_EDUCATION (DEGREE_YEAR);
  CREATE INDEX C_CN_EDUCATION_CAMPUS_CODE ON C_CN_EDUCATION (CAMPUS_CODE);
  CREATE INDEX C_CN_EDUCATION_DEPT_CODE_1 ON C_CN_EDUCATION (DEPT_CODE_1);
  CREATE INDEX C_CN_EDUCATION_DEPT_CODE_2 ON C_CN_EDUCATION (DEPT_CODE_2);
  CREATE INDEX C_CN_EDUCATION_MAJOR_CODE_1 ON C_CN_EDUCATION (MAJOR_CODE_1);
  CREATE INDEX C_CN_EDUCATION_MAJOR_CODE_2 ON C_CN_EDUCATION (MAJOR_CODE_2);
  CREATE INDEX C_CN_EDUCATION_MAJOR_CODE_3 ON C_CN_EDUCATION (MAJOR_CODE_3);
  CREATE INDEX C_CN_EDUCATION_MAJOR_CODE_4 ON C_CN_EDUCATION (MAJOR_CODE_4);
  CREATE INDEX C_CN_EDUCATION_MINOR_CODE_1 ON C_CN_EDUCATION (MAJR_CODE_MINR_1);
  CREATE INDEX C_CN_EDUCATION_MINOR_CODE_2 ON C_CN_EDUCATION (MAJR_CODE_MINR_2);
  CREATE INDEX C_CN_EDUCATION_CONC_CODE_1 ON C_CN_EDUCATION (MAJR_CODE_CONC_1);
  CREATE INDEX C_CN_EDUCATION_CONC_CODE_2 ON C_CN_EDUCATION (MAJR_CODE_CONC_2);
  CREATE INDEX C_CN_EDUCATION_CONC_CODE_3 ON C_CN_EDUCATION (MAJR_CODE_CONC_3);
  CREATE INDEX C_CN_EDUCATION_HONR_CODE_1 ON C_CN_EDUCATION (HONR_CODE_1);
  CREATE INDEX C_CN_EDUCATION_HONR_CODE_2 ON C_CN_EDUCATION (HONR_CODE_2);
  CREATE INDEX C_CN_EDUCATION_HONR_CODE_3 ON C_CN_EDUCATION (HONR_CODE_3);
  CREATE INDEX C_CN_EDUCATION_HONR_CODE_4 ON C_CN_EDUCATION (HONR_CODE_4);
  CREATE INDEX C_CN_EDUCATION_HOND_CODE_1 ON C_CN_EDUCATION (HOND_CODE_1);
  CREATE INDEX C_CN_EDUCATION_HOND_CODE_2 ON C_CN_EDUCATION (HOND_CODE_2);
  CREATE INDEX C_CN_EDUCATION_HOND_CODE_3 ON C_CN_EDUCATION (HOND_CODE_3);
  CREATE INDEX C_CN_EDUCATION_HOND_CODE_4 ON C_CN_EDUCATION (HOND_CODE_4);

