--BEGIN
--  dbms_snapshot.REFRESH('C_CN_EMPLOYMENT_PRIMARY');
--END;

CREATE MATERIALIZED VIEW C_CN_EMPLOYMENT_PRIMARY refresh FAST ON demand
AS
  SELECT PIDM
  , BANNER_ID
  , NAME_SORT
  , ENTITY_CODE
  , EMPL_SEQNO
  , EMPR_PIDM
  , EMPR_BANNER_ID
  , EMPR_NAME
  , ACTIVE_IND
  , PRIMARY_IND
  , EMPL_POSITION
  , DATE_START
  , DATE_END
  , SICC_CODE
  , SICC_DESC
  , JOBC_CODE_1
  , JOBC_DESC_1
  , JOBC_CODE_2
  , JOBC_DESC_2
  , JOBC_CODE_3
  , JOBC_DESC_3
  , JOBC_CODE_4
  , JOBC_DESC_4
  , XREF_CODE
  , XREF_DESC
  , EMPL_COMMENT
  , LU_PRIM_IND
  , EMPS_CODE
  , EMPS_DESC
  , WKLY_HOURS
  , ACTIVITY_DATE
  , ATYP_CODE
  , ATYP_DESC
  , ATYP_SEQNO
  , OK_FOR_NOTES_IND
  , DISP_NOTES_IND
  , DISP_NOTES_DATE
  , MG_IND
  , REVIEWED_IND
  , REVIEWED_USER
  , COOP_IND
  , EMPL_USER
  , USER_ID
  , DATA_ORIGIN
  , RECORD_START_DATE
  FROM h_cn_employment
  WHERE record_end_date IS NULL
  AND primary_ind = 'Y';

  CREATE INDEX C_CN_EMPL_PRIMARY_PIDM ON C_CN_EMPLOYMENT_PRIMARY (PIDM) ;
  CREATE INDEX C_CN_EMPL_PRIMARY_BANNER_ID ON C_CN_EMPLOYMENT_PRIMARY (BANNER_ID) ;
  CREATE INDEX C_CN_EMPL_PRIMARY_NAME_SORT ON C_CN_EMPLOYMENT_PRIMARY (NAME_SORT) ;
  CREATE INDEX C_CN_EMPL_PRIMARY_ENTITY_CODE ON C_CN_EMPLOYMENT_PRIMARY (ENTITY_CODE) ;
  CREATE INDEX C_CN_EMPL_PRIMARY_EMPL_SEQNO ON C_CN_EMPLOYMENT_PRIMARY (EMPL_SEQNO) ;
  CREATE INDEX C_CN_EMPL_PRIMARY_EMPR_PIDM ON C_CN_EMPLOYMENT_PRIMARY (EMPR_PIDM) ;
  CREATE INDEX C_CN_EMPL_PRIMARY_EMPR_ID ON C_CN_EMPLOYMENT_PRIMARY (EMPR_BANNER_ID) ;
  CREATE INDEX C_CN_EMPL_PRIMARY_EMPR_NAME ON C_CN_EMPLOYMENT_PRIMARY (EMPR_NAME) ;
  CREATE INDEX C_CN_EMPL_PRIMARY_ACTIVE ON C_CN_EMPLOYMENT_PRIMARY (ACTIVE_IND) ;
  CREATE INDEX C_CN_EMPL_PRIMARY_PRIMARY ON C_CN_EMPLOYMENT_PRIMARY (PRIMARY_IND) ;
  CREATE INDEX C_CN_EMPL_PRIMARY_POSITION ON C_CN_EMPLOYMENT_PRIMARY (EMPL_POSITION) ;
  CREATE INDEX C_CN_EMPL_PRIMARY_JOBC_1 ON C_CN_EMPLOYMENT_PRIMARY (JOBC_CODE_1) ;
  CREATE INDEX C_CN_EMPL_PRIMARY_JOBC_2 ON C_CN_EMPLOYMENT_PRIMARY (JOBC_CODE_2) ;
  CREATE INDEX C_CN_EMPL_PRIMARY_JOBC_3 ON C_CN_EMPLOYMENT_PRIMARY (JOBC_CODE_3) ;
  CREATE INDEX C_CN_EMPL_PRIMARY_JOBC_4 ON C_CN_EMPLOYMENT_PRIMARY (JOBC_CODE_4) ;  
