--BEGIN
  --dbms_snapshot.REFRESH('C_CN_INDICATORS');
--END;

CREATE MATERIALIZED VIEW LOG ON H_CN_INDICATORS;

CREATE MATERIALIZED VIEW C_CN_INDICATORS refresh FAST ON demand
AS
  SELECT PIDM
  ,  BANNER_ID
  ,  NAME_SORT
  ,  ENTITY_CODE
  ,  ALUMNI_IND
  ,  TRUSTEE_CURRENT_IND
  ,  TRUSTEE_FORMER_IND
  ,  TRUSTEE_ALL_IND
  ,  TRUSTEE_SPOUSE_CURRENT_IND
  ,  TRUSTEE_SPOUSE_FORMER_IND
  ,  TRUSTEE_SPOUSE_ALL_IND
  ,  GREEK_IND
  ,  EMPLOYEE_IND
  ,  STAFF_IND
  ,  DAR_STAFF_IND
  ,  FACULTY_IND
  ,  CLOSEST_TERM_STUDENT_IND
  ,  FRESHMAN_IND
  ,  SOPHOMORE_IND
  ,  JUNIOR_IND
  ,  SENIOR_IND
  ,  CLOSEST_TERM_UNDERGRAD_IND
  ,  CLOSEST_TERM_GRADUATE_IND
  ,  CLOSEST_TERM_PARENT_IND
  ,  CLOSEST_TERM_UG_PARENT_IND
  ,  CLOSEST_TERM_GR_PARENT_IND
  ,  CURRENT_YEAR_STUDENT_IND
  ,  CURRENT_YEAR_UNDERGRAD_IND
  ,  CURRENT_YEAR_GRADUATE_IND
  ,  CURRENT_YEAR_PARENT_IND
  ,  CURRENT_YEAR_UG_PARENT_IND
  ,  CURRENT_YEAR_GR_PARENT_IND
  ,  PAST_PARENT_IND
  ,  PAST_UG_PARENT_IND
  ,  PAST_GR_PARENT_IND
  ,  LEGACY_VIA_PARENT_IND
  ,  LEGACY_VIA_G_PARENT_IND
  ,  LEGACY_VIA_GG_PARENT_IND
  ,  LEGACY_VIA_GGG_PARENT_IND
  ,  ALUM_PARENT_OF_LEGACY_IND
  ,  ALUM_G_PARENT_OF_LEGACY_IND
  ,  ALUM_GG_PARENT_OF_LEGACY_IND
  ,  ALUM_GGG_PARENT_OF_LEGACY_IND
  ,  LEADERSHIP_PLAZA_IND
  ,  TOWER_SOCIETY_IND
  ,  T1_PROSPECT_IND
  ,  T1_SPOUSE_IND
  ,  LUAA_BOARD_IND
  ,  YAC_BOARD_IND
  ,  CURRENT_VOLUNTEER_IND
  , RECORD_START_DATE
  FROM h_cn_indicators
  WHERE record_end_date IS NULL; 
  
  CREATE INDEX C_CN_INDC_PIDM ON C_CN_INDICATORS (PIDM) ;
  CREATE INDEX C_CN_INDC_BANNER_ID ON C_CN_INDICATORS (BANNER_ID) ;
  CREATE INDEX C_CN_INDC_NAME_SORT ON C_CN_INDICATORS (NAME_SORT) ;
  CREATE INDEX C_CN_INDC_ENTITY_CODE ON C_CN_INDICATORS (ENTITY_CODE) ;
  CREATE BITMAP INDEX C_CN_INDC_ALUMNI ON C_CN_INDICATORS (ALUMNI_IND) ;
  CREATE BITMAP INDEX C_CN_INDC_TRST_CURR ON C_CN_INDICATORS (TRUSTEE_CURRENT_IND) ;
  CREATE BITMAP INDEX C_CN_INDC_TRST_FRMR ON C_CN_INDICATORS (TRUSTEE_FORMER_IND) ;
  CREATE BITMAP INDEX C_CN_INDC_TRST_ALL ON C_CN_INDICATORS (TRUSTEE_ALL_IND) ;
  CREATE BITMAP INDEX C_CN_INDC_TRST_SPS_CURR ON C_CN_INDICATORS (TRUSTEE_SPOUSE_CURRENT_IND) ;
  CREATE BITMAP INDEX C_CN_INDC_TRST_SPS_FRMR ON C_CN_INDICATORS (TRUSTEE_SPOUSE_FORMER_IND) ;
  CREATE BITMAP INDEX C_CN_INDC_TRST_SPS_ALL ON C_CN_INDICATORS (TRUSTEE_SPOUSE_ALL_IND) ;
  CREATE BITMAP INDEX C_CN_INDC_GREEK ON C_CN_INDICATORS (GREEK_IND) ;
  CREATE BITMAP INDEX C_CN_INDC_EMPLOYEE ON C_CN_INDICATORS (EMPLOYEE_IND) ;
  CREATE BITMAP INDEX C_CN_INDC_STAFF ON C_CN_INDICATORS (STAFF_IND) ;
  CREATE BITMAP INDEX C_CN_INDC_DAR_STAFF ON C_CN_INDICATORS (DAR_STAFF_IND) ;
  CREATE BITMAP INDEX C_CN_INDC_FACULTY ON C_CN_INDICATORS (FACULTY_IND) ;
  CREATE BITMAP INDEX C_CN_INDC_CLSTRM_STDT ON C_CN_INDICATORS (CLOSEST_TERM_STUDENT_IND) ;
  CREATE BITMAP INDEX C_CN_INDC_FRESHMAN ON C_CN_INDICATORS (FRESHMAN_IND) ;
  CREATE BITMAP INDEX C_CN_INDC_SOPHOMORE ON C_CN_INDICATORS (SOPHOMORE_IND) ;
  CREATE BITMAP INDEX C_CN_INDC_JUNIOR ON C_CN_INDICATORS (JUNIOR_IND) ;
  CREATE BITMAP INDEX C_CN_INDC_SENIOR ON C_CN_INDICATORS (SENIOR_IND) ;
  CREATE BITMAP INDEX C_CN_INDC_CLSTRM_UG ON C_CN_INDICATORS (CLOSEST_TERM_UNDERGRAD_IND) ;
  CREATE BITMAP INDEX C_CN_INDC_CLSTRM_GR ON C_CN_INDICATORS (CLOSEST_TERM_GRADUATE_IND) ;
  CREATE BITMAP INDEX C_CN_INDC_CLSTRM_PARN ON C_CN_INDICATORS (CLOSEST_TERM_PARENT_IND) ;
  CREATE BITMAP INDEX C_CN_INDC_CLSTRM_UG_PARN ON C_CN_INDICATORS (CLOSEST_TERM_UG_PARENT_IND) ;
  CREATE BITMAP INDEX C_CN_INDC_CLSTRM_GR_PARN ON C_CN_INDICATORS (CLOSEST_TERM_GR_PARENT_IND) ;
  CREATE BITMAP INDEX C_CN_INDC_CURRYR_STDT ON C_CN_INDICATORS (CURRENT_YEAR_STUDENT_IND) ;
  CREATE BITMAP INDEX C_CN_INDC_CURRYR_UG ON C_CN_INDICATORS (CURRENT_YEAR_UNDERGRAD_IND) ;
  CREATE BITMAP INDEX C_CN_INDC_CURRYR_GR ON C_CN_INDICATORS (CURRENT_YEAR_GRADUATE_IND) ;
  CREATE BITMAP INDEX C_CN_INDC_CURRYR_PARN ON C_CN_INDICATORS (CURRENT_YEAR_PARENT_IND) ;
  CREATE BITMAP INDEX C_CN_INDC_CURRYR_UG_PARN ON C_CN_INDICATORS (CURRENT_YEAR_UG_PARENT_IND) ;
  CREATE BITMAP INDEX C_CN_INDC_CURRYR_GR_PARN ON C_CN_INDICATORS (CURRENT_YEAR_GR_PARENT_IND) ;
  CREATE BITMAP INDEX C_CN_INDC_PAST_PARN ON C_CN_INDICATORS (PAST_PARENT_IND) ;
  CREATE BITMAP INDEX C_CN_INDC_PAST_UG_PARN ON C_CN_INDICATORS (PAST_UG_PARENT_IND) ;
  CREATE BITMAP INDEX C_CN_INDC_PAST_GR_PARN ON C_CN_INDICATORS (PAST_GR_PARENT_IND) ;
  CREATE BITMAP INDEX C_CN_INDC_VIA_PARN ON C_CN_INDICATORS (LEGACY_VIA_PARENT_IND) ;
  CREATE BITMAP INDEX C_CN_INDC_VIA_G_PARN ON C_CN_INDICATORS (LEGACY_VIA_G_PARENT_IND) ;
  CREATE BITMAP INDEX C_CN_INDC_VIA_GG_PARN ON C_CN_INDICATORS (LEGACY_VIA_GG_PARENT_IND) ;
  CREATE BITMAP INDEX C_CN_INDC_VIA_GGG_PARN ON C_CN_INDICATORS (LEGACY_VIA_GGG_PARENT_IND) ;
  CREATE BITMAP INDEX C_CN_INDC_ALUM_PARN ON C_CN_INDICATORS (ALUM_PARENT_OF_LEGACY_IND) ;
  CREATE BITMAP INDEX C_CN_INDC_ALUM_G_PARN ON C_CN_INDICATORS (ALUM_G_PARENT_OF_LEGACY_IND) ;
  CREATE BITMAP INDEX C_CN_INDC_ALUM_GG_PARN ON C_CN_INDICATORS (ALUM_GG_PARENT_OF_LEGACY_IND) ;
  CREATE BITMAP INDEX C_CN_INDC_ALUM_GGG_PARN ON C_CN_INDICATORS (ALUM_GGG_PARENT_OF_LEGACY_IND) ;
  CREATE BITMAP INDEX C_CN_INDC_LEADER_PLZ ON C_CN_INDICATORS (LEADERSHIP_PLAZA_IND) ;
  CREATE BITMAP INDEX C_CN_INDC_TOWER ON C_CN_INDICATORS (TOWER_SOCIETY_IND) ;
  CREATE BITMAP INDEX C_CN_INDC_T1_PRSP ON C_CN_INDICATORS (T1_PROSPECT_IND) ;
  CREATE BITMAP INDEX C_CN_INDC_T1_SPS ON C_CN_INDICATORS (T1_SPOUSE_IND) ;
  CREATE BITMAP INDEX C_CN_INDC_LUAA_BOARD ON C_CN_INDICATORS (LUAA_BOARD_IND) ;
  CREATE BITMAP INDEX C_CN_INDC_YAC_BOARD ON C_CN_INDICATORS (YAC_BOARD_IND) ;
  CREATE BITMAP INDEX C_CN_INDC_VOLUNTEER ON C_CN_INDICATORS (CURRENT_VOLUNTEER_IND) ;


COMMENT ON COLUMN PENTAHO.C_CN_INDICATORS.PIDM IS 'from CN_CONSTITUENT.PIDM';
COMMENT ON COLUMN PENTAHO.C_CN_INDICATORS.BANNER_ID IS 'from CN_CONSTITUENT.BANNER_ID';
COMMENT ON COLUMN PENTAHO.C_CN_INDICATORS.ENTITY_CODE IS 'from CN_CONSTITUENT.ENTITY_CODE';
COMMENT ON COLUMN PENTAHO.C_CN_INDICATORS.NAME_SORT IS 'from CN_CONSTITUENT.NAME_SORT';
COMMENT ON COLUMN PENTAHO.C_CN_INDICATORS.RECORD_START_DATE IS 'Date record was created/changed in Banner';
COMMENT ON COLUMN PENTAHO.C_CN_INDICATORS.ALUMNI_IND IS 'from CN_DONOR_CODES where ALMB = ''Y'' OR ALMX = ''Y'' OR ALMG = ''Y''';
COMMENT ON COLUMN PENTAHO.C_CN_INDICATORS.TRUSTEE_CURRENT_IND IS 'actp_code = ''TRUST'' and accg_code = ''UNIV'' in current FY';
COMMENT ON COLUMN PENTAHO.C_CN_INDICATORS.TRUSTEE_FORMER_IND IS 'actp_code = ''TRUST'' and accg_code = ''UNIV'' in < current FY';
COMMENT ON COLUMN PENTAHO.C_CN_INDICATORS.TRUSTEE_ALL_IND IS 'actp_code = ''TRUST'' and accg_code = ''UNIV'' in any/no FY';
COMMENT ON COLUMN PENTAHO.C_CN_INDICATORS.TRUSTEE_SPOUSE_CURRENT_IND IS 'SPOUSE_PIDM where actp_code = ''TRUST'' and accg_code = ''UNIV'' in current FY';
COMMENT ON COLUMN PENTAHO.C_CN_INDICATORS.TRUSTEE_SPOUSE_FORMER_IND IS 'SPOUSE_PIDM where actp_code = ''TRUST'' and accg_code = ''UNIV'' in < current FY';
COMMENT ON COLUMN PENTAHO.C_CN_INDICATORS.TRUSTEE_SPOUSE_ALL_IND IS 'SPOUSE_PIDM where actp_code = ''TRUST'' and accg_code = ''UNIV'' in any/no FY';
COMMENT ON COLUMN PENTAHO.C_CN_INDICATORS.GREEK_IND IS 'CN_ACTIVITIES.ACTP_CODE = ''FRTY'' or ''SRTY''';
COMMENT ON COLUMN PENTAHO.C_CN_INDICATORS.EMPLOYEE_IND IS 'from APW_EMP_FOR_ADVANCEMENT_DATA1.EA1_EMPL_ECLS_CODE not in (RM,V1,V2)';
COMMENT ON COLUMN PENTAHO.C_CN_INDICATORS.STAFF_IND IS 'employee_ind = ''Y'' and EA1_EMPL_ECLS_CODE <> like ''F%''';
COMMENT ON COLUMN PENTAHO.C_CN_INDICATORS.DAR_STAFF_IND IS 'employee_ind = ''Y'' and EA1_ORGN_CHART_UNIT_CODE = 30';
COMMENT ON COLUMN PENTAHO.C_CN_INDICATORS.FACULTY_IND IS 'employee_ind = ''Y'' and EA1_EMPL_ECLS_CODE like ''F%''';
COMMENT ON COLUMN PENTAHO.C_CN_INDICATORS.CLOSEST_TERM_STUDENT_IND IS 'Any student able to enroll in current term or closest term to current date';
COMMENT ON COLUMN PENTAHO.C_CN_INDICATORS.FRESHMAN_IND IS 'SGBSTDN_LEVL_CODE = ''FR'' for current/closest term';
COMMENT ON COLUMN PENTAHO.C_CN_INDICATORS.SOPHOMORE_IND IS 'SGBSTDN_LEVL_CODE = ''SO'' for current/closest term';
COMMENT ON COLUMN PENTAHO.C_CN_INDICATORS.JUNIOR_IND IS 'SGBSTDN_LEVL_CODE = ''JR'' for current/closest term';
COMMENT ON COLUMN PENTAHO.C_CN_INDICATORS.SENIOR_IND IS 'SGBSTDN_LEVL_CODE = ''SR'' for current/closest term';
COMMENT ON COLUMN PENTAHO.C_CN_INDICATORS.CLOSEST_TERM_UNDERGRAD_IND IS 'Undergraduate student able to enroll in current term or closest term to current date';
COMMENT ON COLUMN PENTAHO.C_CN_INDICATORS.CLOSEST_TERM_GRADUATE_IND IS 'Graduate student able to enroll in current term or closest term to current date';
COMMENT ON COLUMN PENTAHO.C_CN_INDICATORS.CLOSEST_TERM_PARENT_IND IS 'Parent of student where CLOSEST_TERM_STUDENT_IND = ''Y''';
COMMENT ON COLUMN PENTAHO.C_CN_INDICATORS.CLOSEST_TERM_UG_PARENT_IND IS 'Parent of student where CLOSEST_TERM_UNDERGRAD_IND = ''Y''';
COMMENT ON COLUMN PENTAHO.C_CN_INDICATORS.CLOSEST_TERM_GR_PARENT_IND IS 'Parent of student where CLOSEST_TERM_GRADUATE_IND = ''Y''';
COMMENT ON COLUMN PENTAHO.C_CN_INDICATORS.CURRENT_YEAR_STUDENT_IND IS 'Any student able to enroll in any term during current academic year';
COMMENT ON COLUMN PENTAHO.C_CN_INDICATORS.CURRENT_YEAR_UNDERGRAD_IND IS 'Undergraduate student able to enroll in any term during current academic year';
COMMENT ON COLUMN PENTAHO.C_CN_INDICATORS.CURRENT_YEAR_GRADUATE_IND IS 'Graduate student able to enroll in any term during current academic year';
COMMENT ON COLUMN PENTAHO.C_CN_INDICATORS.CURRENT_YEAR_PARENT_IND IS 'Parent of student where CURRENT_YEAR_STUDENT_IND = ''Y''';
COMMENT ON COLUMN PENTAHO.C_CN_INDICATORS.CURRENT_YEAR_UG_PARENT_IND IS 'Parent of student where CURRENT_YEAR_UNDERGRAD_IND = ''Y''';
COMMENT ON COLUMN PENTAHO.C_CN_INDICATORS.CURRENT_YEAR_GR_PARENT_IND IS 'Parent of student where CURRENT_YEAR_GRADUATE_IND = ''Y''';
COMMENT ON COLUMN PENTAHO.C_CN_INDICATORS.PAST_PARENT_IND IS 'Parent of ALMB, ALMX, or ALMG';
COMMENT ON COLUMN PENTAHO.C_CN_INDICATORS.PAST_UG_PARENT_IND IS 'Parent of ALMB, ALMX';
COMMENT ON COLUMN PENTAHO.C_CN_INDICATORS.PAST_GR_PARENT_IND IS 'Parent of ALMG';
COMMENT ON COLUMN PENTAHO.C_CN_INDICATORS.LEGACY_VIA_PARENT_IND IS 'Alumni child of alumni parent';
COMMENT ON COLUMN PENTAHO.C_CN_INDICATORS.LEGACY_VIA_G_PARENT_IND IS 'Alumni grandchild of alumni grandparent';
COMMENT ON COLUMN PENTAHO.C_CN_INDICATORS.LEGACY_VIA_GG_PARENT_IND IS 'Alumni great grandchild of alumni great grandparent';
COMMENT ON COLUMN PENTAHO.C_CN_INDICATORS.LEGACY_VIA_GGG_PARENT_IND IS 'Alumni great great grandchild of alumni great great grandparent';
COMMENT ON COLUMN PENTAHO.C_CN_INDICATORS.ALUM_PARENT_OF_LEGACY_IND IS 'Alumni parent of alumni child';
COMMENT ON COLUMN PENTAHO.C_CN_INDICATORS.ALUM_G_PARENT_OF_LEGACY_IND IS 'Alumni grandparent of alumni grandchild';
COMMENT ON COLUMN PENTAHO.C_CN_INDICATORS.ALUM_GG_PARENT_OF_LEGACY_IND IS 'Alumni great grandparent of alumni great grandchild';
COMMENT ON COLUMN PENTAHO.C_CN_INDICATORS.ALUM_GGG_PARENT_OF_LEGACY_IND IS 'Alumni great great grandparent of alumni great great grandchild';
COMMENT ON COLUMN PENTAHO.C_CN_INDICATORS.LEADERSHIP_PLAZA_IND IS 'from APRDCLB where ATVDCST_DCST_CODE = ''LP''';
COMMENT ON COLUMN PENTAHO.C_CN_INDICATORS.TOWER_SOCIETY_IND IS 'from APRDCLB where ATVDCST_DCST_CODE = ''TW''';
COMMENT ON COLUMN PENTAHO.C_CN_INDICATORS.T1_PROSPECT_IND IS 'from AMRPRRT where APRPRRT_RTGT_CODE = ''U'' and APRPRRT_RATE_CODE = ''T1''';
COMMENT ON COLUMN PENTAHO.C_CN_INDICATORS.T1_SPOUSE_IND IS 'Active spouse where T1_PROSPECT_IND = ''Y''';
COMMENT ON COLUMN PENTAHO.C_CN_INDICATORS.LUAA_BOARD_IND IS 'from D_CN_ACTIVITIES_YEAR where GTVSDAX_INTERNAL_CODE = ''LUAA'' and GTVSDAX_INTERNAL_CODE_GROUP = ''BOARD''';
COMMENT ON COLUMN PENTAHO.C_CN_INDICATORS.YAC_BOARD_IND IS 'from D_CN_ACTIVITIES_YEAR where GTVSDAX_INTERNAL_CODE = ''LUAA'' and GTVSDAX_INTERNAL_CODE_GROUP = ''YAC''';
COMMENT ON COLUMN PENTAHO.C_CN_INDICATORS.CURRENT_VOLUNTEER_IND IS 'from D_CN_ACTIVITIES_YEAR where GTVSDAX_INTERNAL_CODE = ''LUAA'' and GTVSDAX_INTERNAL_CODE_GROUP IN (''DEVVOL'', ''STUDENT'', ''AWARDS'', ''BOARD'', ''CAREER'', ''CLUBS'', ''GREEK'', ''LEHIGH_FUND'', ''OUTREACH'', ''REUNION'', ''SEN_ALUM_COMMITTEE'', ''YAC'', ''AFFINITY'', ''ATHLETIC'', ''AAO'')';
