--BEGIN
  --dbms_snapshot.REFRESH('c_cn_variable_purpose_by_id');
--END;

CREATE MATERIALIZED VIEW LOG ON H_CN_VARIABLE_PURPOSE_BY_ID;

CREATE MATERIALIZED VIEW C_CN_VARIABLE_PURPOSE_BY_ID refresh FAST ON demand
AS
  SELECT PIDM
  ,  BANNER_ID
  ,  NAME_SORT
  ,  ENTITY_CODE
  ,  RECORD_START_DATE
  ,  VIPC_3PA
  ,  VIPC_AFB
  ,  VIPC_AFE
  ,  VIPC_AFM
  ,  VIPC_AI
  ,  VIPC_AOL
  ,  VIPC_APG
  ,  VIPC_BPC
  ,  VIPC_CMR
  ,  VIPC_D11
  ,  VIPC_D12
  ,  VIPC_D13
  ,  VIPC_D14
  ,  VIPC_D15
  ,  VIPC_D20
  ,  VIPC_D30
  ,  VIPC_DOC
  ,  VIPC_DSE
  ,  VIPC_E13
  ,  VIPC_E15
  ,  VIPC_ENG
  ,  VIPC_EZR
  ,  VIPC_FFR
  ,  VIPC_FSI
  ,  VIPC_GAM
  ,  VIPC_GE1
  ,  VIPC_HCM
  ,  VIPC_HED
  ,  VIPC_HGD
  ,  VIPC_HGN
  ,  VIPC_JDS
  ,  VIPC_JSG
  ,  VIPC_L13
  ,  VIPC_L15
  ,  VIPC_LVM
  ,  VIPC_M13
  ,  VIPC_M15
  ,  VIPC_MDP
  ,  VIPC_MLI
  ,  VIPC_MLS
  ,  VIPC_NTO
  ,  VIPC_OCM
  ,  VIPC_P14
  ,  VIPC_P16
  ,  VIPC_PE
  ,  VIPC_PRE
  ,  VIPC_PRL
  ,  VIPC_QWM
  ,  VIPC_RDS
  ,  VIPC_RNC
  ,  VIPC_SPC
  ,  VIPC_SRO
  ,  VIPC_TRJ
  ,  VIPC_U14
  ,  VIPC_U15
  ,  VIPC_UGL
  ,  VIPC_UKP
  ,  VIPC_UND
  ,  VIPC_VC
  ,  VIPC_WEP
  ,  VIPC_WIL
  ,  VIPC_ZDP
  ,  VIPC_MTP
  ,  VIPC_U16
  ,  VIPC_U17
  ,  VIPC_EAT
  FROM h_cn_variable_purpose_by_id
  WHERE record_end_date IS NULL; 

  CREATE INDEX C_CN_VAR_BY_ID_PIDM ON C_CN_VARIABLE_PURPOSE_BY_ID (PIDM) ;
  CREATE INDEX C_CN_VAR_BY_ID_BANNER_ID ON C_CN_VARIABLE_PURPOSE_BY_ID (BANNER_ID) ;
  CREATE INDEX C_CN_VAR_BY_ID_NAME_SORT ON C_CN_VARIABLE_PURPOSE_BY_ID (NAME_SORT) ;
  CREATE INDEX C_CN_VAR_BY_ID_ENTITY_CODE ON C_CN_VARIABLE_PURPOSE_BY_ID (ENTITY_CODE) ;
