/*begin
dbms_snapshot.REFRESH('C_CN_CONSTITUENT');
end;
*/

-- CREATE MATERIALIZED VIEW LOG ON H_CN_CONSTITUENT;

CREATE MATERIALIZED VIEW C_CN_CONSTITUENT refresh force ON demand
AS
  SELECT PIDM
  , BANNER_ID
  , ENTITY_CODE
  , NAME_SORT
  , NAME_FIRST
  , NAME_LAST
  , NAME_MIDDLE
  , NAME_MAIDEN
  , NAME_LEGAL
  , NAME_PREFIX
  , NAME_SUFFIX
  , CONFID_IND
  , USER_ID
  , IMODULES_AUTH_NUMBER
  , VISITOR_NETWORK_ID
  , STOCK_TICKER_ID
  , CLASS_YEAR_PREF
  , DONOR_CODE_PRIMARY
  , DONOR_CODE_DESC
  , DONOR_CODE_STRING
  , GENDER_CODE
  , GENDER_DESC
  , DEAD_IND
  , DATE_DECEASED
  , DATE_BIRTH
  , CASE
      WHEN date_deceased IS NULL THEN TRUNC((sysdate - date_birth)/365.25)
      ELSE TRUNC((date_deceased                      - date_birth)/365.25)
    END AS AGE
  , REUN_CYCLE
  , REUN_CYCLE_START
  , REUN_CYCLE_END
  , MARITAL_STATUS_CODE
  , MARITAL_STATUS_DESC
  , SPOUSE_PIDM
  , SPOUSE_NAME_SORT
  , SPOUSE_DEAD_IND
  , SPOUSE_DEAD_DATE
  , SPOUSE_BANNER_ID
  , SPOUSE_CODE
  , SPOUSE_DESC
  , SPOUSE_CLASS_YEAR_PREF
  , SPOUSE_LAST_NAME
  , SPOUSE_FIRST_NAME
  , SPOUSE_MI
  , SPOUSE_BIRTH_DATE
  , SPOUSE_NAME_PREFIX
  , SPOUSE_NAME_SUFFIX
  , ETHNICITY_CODE
  , ETHNICITY_DESC
  , HISPANIC_CODE
  , HISPANIC_DESC
  , RELIGION_CODE
  , RELIGION_DESC
  , CITIZEN_CODE
  , CITIZEN_DESC
  , AMERICAN_INDIAN_IND
  , ASIAN_IND
  , AFRICAN_AMERICAN_IND
  , NATIVE_PACIFIC_ISLAND_IND
  , CAUCASIAN_IND
  , SPOUSE_DONOR_CODE
  , SPOUSE_DONOR_CODE_DESC
  , SPOUSE_DONOR_CODE_STRING
  , HOUSEHOLD_PIDM
  , HOUSEHOLD_RANK
  , PRIMARY_STAFF_CODE
  , PRIMARY_STAFF_DESC
  , RESEARCH_RATE_TYPE
  , RESEARCH_RATE_CODE
  , RESEARCH_RATE_DESC
  , QUALIFIED_RATE_TYPE
  , QUALIFIED_RATE_CODE
  , QUALIFIED_RATE_DESC
  , SPSE_RESEARCH_RATE_TYPE
  , SPSE_RESEARCH_RATE_CODE
  , SPSE_RESEARCH_RATE_DESC
  , SPSE_QUALIFIED_RATE_TYPE
  , SPSE_QUALIFIED_RATE_CODE
  , SPSE_QUALIFIED_RATE_DESC
  , FIRST_CONS_FY
  , LAST_CONS_FY
  , PREF_COLLEGE_CODE
  , PREF_COLLEGE_DESC
  , RECORD_START_DATE
  FROM h_cn_constituent
  WHERE record_end_date IS NULL;
  
ALTER TABLE 
   C_CN_CONSTITUENT
ADD CONSTRAINT 
   C_CN_CONSTITUENT_PK
PRIMARY KEY (PIDM, RECORD_START_DATE);

   COMMENT ON COLUMN "PENTAHO"."C_CN_CONSTITUENT"."PIDM" IS 'from SPRIDEN_PIDM; Internal identification number of constituent';
   COMMENT ON COLUMN "PENTAHO"."C_CN_CONSTITUENT"."BANNER_ID" IS 'from SPRIDEN_ID; Banner ID (LIN) of constituent';
   COMMENT ON COLUMN "PENTAHO"."C_CN_CONSTITUENT"."ENTITY_CODE" IS '(P) record from APBCONS (Person); (C) record from AOBORGN (Non-Person)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_CONSTITUENT"."NAME_SORT" IS 'from CN_CURRENT_NAMES.NAME_SORT';
   COMMENT ON COLUMN "PENTAHO"."C_CN_CONSTITUENT"."NAME_FIRST" IS 'from SPRIDEN_FIRST_NAME';
   COMMENT ON COLUMN "PENTAHO"."C_CN_CONSTITUENT"."NAME_LAST" IS 'from SPRIDEN_LAST_NAME';
   COMMENT ON COLUMN "PENTAHO"."C_CN_CONSTITUENT"."NAME_MIDDLE" IS 'from SPRIDEN_MI';
   COMMENT ON COLUMN "PENTAHO"."C_CN_CONSTITUENT"."NAME_MAIDEN" IS 'from APBCONS_MAIDEN_LAST_NAME';
   COMMENT ON COLUMN "PENTAHO"."C_CN_CONSTITUENT"."NAME_LEGAL" IS 'from SPBPERS_LEGAL_NAME';
   COMMENT ON COLUMN "PENTAHO"."C_CN_CONSTITUENT"."NAME_PREFIX" IS 'from SPBPERS_NAME_PREFIX';
   COMMENT ON COLUMN "PENTAHO"."C_CN_CONSTITUENT"."NAME_SUFFIX" IS 'from SPBPERS_NAME_SUFFIX';
   COMMENT ON COLUMN "PENTAHO"."C_CN_CONSTITUENT"."CONFID_IND" IS 'from SPBPERS_CONFID_IND (Y/N)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_CONSTITUENT"."USER_ID" IS 'from GORADID_ADDITIONAL_ID where GORADID_ADID_CODE = LNID';
   COMMENT ON COLUMN "PENTAHO"."C_CN_CONSTITUENT"."IMODULES_AUTH_NUMBER" IS 'from GORADID_ADDITIONAL_ID where GORADID_ADID_CODE = IAN' ;
   COMMENT ON COLUMN "PENTAHO"."C_CN_CONSTITUENT"."VISITOR_NETWORK_ID" IS 'from GORADID_ADDITIONAL_ID where GORADID_ADID_CODE = VID';
   COMMENT ON COLUMN "PENTAHO"."C_CN_CONSTITUENT"."STOCK_TICKER_ID" IS 'from GORADID_ADDITIONAL_ID where GORADID_ADID_CODE = TICK (corporations only)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_CONSTITUENT"."CLASS_YEAR_PREF" IS 'from APBCONS_PREF_CLAS';
   COMMENT ON COLUMN "PENTAHO"."C_CN_CONSTITUENT"."DONOR_CODE_PRIMARY" IS 'from APRCATG_DONR_CODE with MIN(ATVDONR_RPT_SEQ_IND)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_CONSTITUENT"."DONOR_CODE_DESC" IS 'Description for DONOR_CODE_PRIMARY';
   COMMENT ON COLUMN "PENTAHO"."C_CN_CONSTITUENT"."DONOR_CODE_STRING" IS 'String list of all APRCATG_DONR_CODE in ATVDONR_RPT_SEQ_IND order separated by commas';
   COMMENT ON COLUMN "PENTAHO"."C_CN_CONSTITUENT"."GENDER_CODE" IS '(M) for Male; (F) for Female; (N) for Unknown';
   COMMENT ON COLUMN "PENTAHO"."C_CN_CONSTITUENT"."GENDER_DESC" IS 'Description for GENDER_CODE';
   COMMENT ON COLUMN "PENTAHO"."C_CN_CONSTITUENT"."DEAD_IND" IS 'from SPBPERS_DEAD_IND (Y/N)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_CONSTITUENT"."DATE_DECEASED" IS 'from SPBPERS_DEAD_DATE';
   COMMENT ON COLUMN "PENTAHO"."C_CN_CONSTITUENT"."DATE_BIRTH" IS 'from SPBPERS_BIRTH_DATE';
   COMMENT ON COLUMN "PENTAHO"."C_CN_CONSTITUENT"."REUN_CYCLE" IS 'For ALMB/X - 5-yr reunion cycle alum is currently in (5, 10, 15 etc.)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_CONSTITUENT"."REUN_CYCLE_START" IS 'For ALMB/X - Year alum began reunion cycle (last reunion year "1)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_CONSTITUENT"."REUN_CYCLE_END" IS 'For ALMB/X - Year alum ends current reunion cycle (next reunion year)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_CONSTITUENT"."MARITAL_STATUS_CODE" IS 'from SPBPERS_MRTL_CODE';
   COMMENT ON COLUMN "PENTAHO"."C_CN_CONSTITUENT"."MARITAL_STATUS_DESC" IS 'Description for MARITAL_STATUS_CODE';
   COMMENT ON COLUMN "PENTAHO"."C_CN_CONSTITUENT"."SPOUSE_PIDM" IS 'APRCSPS_PIDM where APRCSPS_MARS_IND = ''A''';
   COMMENT ON COLUMN "PENTAHO"."C_CN_CONSTITUENT"."SPOUSE_NAME_SORT" IS 'NAME_SORT where PIDM = SPOUSE_PIDM';
   COMMENT ON COLUMN "PENTAHO"."C_CN_CONSTITUENT"."SPOUSE_DEAD_IND" IS 'DEAD_IND where PIDM = SPOUSE_PIDM';
   COMMENT ON COLUMN "PENTAHO"."C_CN_CONSTITUENT"."SPOUSE_DEAD_DATE" IS 'DEAD_DATE where PIDM = SPOUSE_PIDM';
   COMMENT ON COLUMN "PENTAHO"."C_CN_CONSTITUENT"."SPOUSE_BANNER_ID" IS 'BANNER ID where PIDM = SPOUSE_PIDM';
   COMMENT ON COLUMN "PENTAHO"."C_CN_CONSTITUENT"."SPOUSE_CODE" IS 'APRXREF_XREF_CODE of spouse where ATVXREF_SPOUSE_IND = ''Y''';
   COMMENT ON COLUMN "PENTAHO"."C_CN_CONSTITUENT"."SPOUSE_DESC" IS 'Description of SPOUSE_CODE';
   COMMENT ON COLUMN "PENTAHO"."C_CN_CONSTITUENT"."SPOUSE_CLASS_YEAR_PREF" IS 'CLASS_YEAR_PREF where PIDM = SPOUSE_PIDM';
   COMMENT ON COLUMN "PENTAHO"."C_CN_CONSTITUENT"."SPOUSE_LAST_NAME" IS 'NAME_LAST where PIDM = SPOUSE_PIDM';
   COMMENT ON COLUMN "PENTAHO"."C_CN_CONSTITUENT"."SPOUSE_FIRST_NAME" IS 'NAME_FIRST where PIDM = SPOUSE_PIDM';
   COMMENT ON COLUMN "PENTAHO"."C_CN_CONSTITUENT"."SPOUSE_MI" IS 'NAME_MI where PIDM = SPOUSE_PIDM';
   COMMENT ON COLUMN "PENTAHO"."C_CN_CONSTITUENT"."SPOUSE_BIRTH_DATE" IS 'DATE_BIRTH where PIDM = SPOUSE_PIDM';
   COMMENT ON COLUMN "PENTAHO"."C_CN_CONSTITUENT"."SPOUSE_NAME_PREFIX" IS 'NAME_PREFIX where PIDM = SPOUSE_PIDM';
   COMMENT ON COLUMN "PENTAHO"."C_CN_CONSTITUENT"."SPOUSE_NAME_SUFFIX" IS 'NAME_SUFFIX where PIDM = SPOUSE_PIDM';
   COMMENT ON COLUMN "PENTAHO"."C_CN_CONSTITUENT"."ETHNICITY_CODE" IS 'from SPBPERS_ETHN_CODE';
   COMMENT ON COLUMN "PENTAHO"."C_CN_CONSTITUENT"."ETHNICITY_DESC" IS 'Description for ETHNICITY_CODE';
   COMMENT ON COLUMN "PENTAHO"."C_CN_CONSTITUENT"."HISPANIC_CODE" IS 'from SPBPERS_ETHN_CDE';
   COMMENT ON COLUMN "PENTAHO"."C_CN_CONSTITUENT"."HISPANIC_DESC" IS 'Description for HISPANIC_CODE';
   COMMENT ON COLUMN "PENTAHO"."C_CN_CONSTITUENT"."RELIGION_CODE" IS 'from SPBPERS_RELG_CODE';
   COMMENT ON COLUMN "PENTAHO"."C_CN_CONSTITUENT"."RELIGION_DESC" IS 'Description for RELIGION_CODE';
   COMMENT ON COLUMN "PENTAHO"."C_CN_CONSTITUENT"."CITIZEN_CODE" IS 'from SPBPERS_CITZ_CODE';
   COMMENT ON COLUMN "PENTAHO"."C_CN_CONSTITUENT"."CITIZEN_DESC" IS 'Description for CITIZEN_CODE';
   COMMENT ON COLUMN "PENTAHO"."C_CN_CONSTITUENT"."AMERICAN_INDIAN_IND" IS 'Has GORPRAC_RACE_CDE = 1 (American Indian or Alaskan Native)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_CONSTITUENT"."ASIAN_IND" IS 'Has GORPRAC_RACE_CDE = 2 (Asian)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_CONSTITUENT"."AFRICAN_AMERICAN_IND" IS 'Has GORPRAC_RACE_CDE = 3 (Black or African American)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_CONSTITUENT"."NATIVE_PACIFIC_ISLAND_IND" IS 'Has GORPRAC_RACE_CDE = 4 (Native Hawaiian and Other Pacific Islander)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_CONSTITUENT"."CAUCASIAN_IND" IS 'Has GORPRAC_RACE_CDE = 5 (White)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_CONSTITUENT"."SPOUSE_DONOR_CODE" IS 'DONOR_CODE_PRIMARY where PIDM = SPOUSE_PIDM';
   COMMENT ON COLUMN "PENTAHO"."C_CN_CONSTITUENT"."HOUSEHOLD_PIDM" IS 'Combined PIDM for primary donor and spouse in numerical order of pidm';
   COMMENT ON COLUMN "PENTAHO"."C_CN_CONSTITUENT"."HOUSEHOLD_RANK" IS 'Rank within household group;  Rank = 1 where RTGT_CODE = D';
   COMMENT ON COLUMN "PENTAHO"."C_CN_CONSTITUENT"."PRIMARY_STAFF_CODE" IS 'Primary staff assigned to donor; AMRSTAF_IDEN_CODE where AMRSTAF_STFT_CODE = PRIM and sysdate between AMRSTAF_START_DATE and AMRSTAF_END_DATE';
   COMMENT ON COLUMN "PENTAHO"."C_CN_CONSTITUENT"."PRIMARY_STAFF_DESC" IS 'Name of primary staff assigned';
   COMMENT ON COLUMN "PENTAHO"."C_CN_CONSTITUENT"."RESEARCH_RATE_TYPE" IS 'AMRPRRT_RTGT_CODE = D or S';
   COMMENT ON COLUMN "PENTAHO"."C_CN_CONSTITUENT"."RESEARCH_RATE_CODE" IS 'AMRPRRT_RATE_CODE where AMRPRRT_RTGT_CODE = D or S';
   COMMENT ON COLUMN "PENTAHO"."C_CN_CONSTITUENT"."RESEARCH_RATE_DESC" IS 'ATVRATE_DESC where AMRPRRT_RTGT_CODE = D or S';
   COMMENT ON COLUMN "PENTAHO"."C_CN_CONSTITUENT"."QUALIFIED_RATE_TYPE" IS 'AMRPRRT_RTGT_CODE = Q or T';
   COMMENT ON COLUMN "PENTAHO"."C_CN_CONSTITUENT"."QUALIFIED_RATE_CODE" IS 'AMRPRRT_RATE_CODE where AMRPRRT_RTGT_CODE = Q or T';
   COMMENT ON COLUMN "PENTAHO"."C_CN_CONSTITUENT"."QUALIFIED_RATE_DESC" IS 'ATVRATE_DESC where AMRPRRT_RTGT_CODE = Q or T';
   COMMENT ON COLUMN "PENTAHO"."C_CN_CONSTITUENT"."SPSE_RESEARCH_RATE_TYPE" IS 'AMRPRRT_RTGT_CODE of spouse = D or S';
   COMMENT ON COLUMN "PENTAHO"."C_CN_CONSTITUENT"."SPSE_RESEARCH_RATE_CODE" IS 'AMRPRRT_RATE_CODE of spouse where AMRPRRT_RTGT_CODE = D or S';
   COMMENT ON COLUMN "PENTAHO"."C_CN_CONSTITUENT"."SPSE_RESEARCH_RATE_DESC" IS 'ATVRATE_DESC where of spouse AMRPRRT_RTGT_CODE = D or S';
   COMMENT ON COLUMN "PENTAHO"."C_CN_CONSTITUENT"."SPSE_QUALIFIED_RATE_TYPE" IS 'AMRPRRT_RTGT_CODE of spouse = Q or T';
   COMMENT ON COLUMN "PENTAHO"."C_CN_CONSTITUENT"."SPSE_QUALIFIED_RATE_CODE" IS 'AMRPRRT_RATE_CODE of spouse where AMRPRRT_RTGT_CODE = Q or T';
   COMMENT ON COLUMN "PENTAHO"."C_CN_CONSTITUENT"."SPSE_QUALIFIED_RATE_DESC" IS 'ATVRATE_DESC of spouse where AMRPRRT_RTGT_CODE = Q or T';
   COMMENT ON COLUMN "PENTAHO"."C_CN_CONSTITUENT"."FIRST_CONS_FY" IS 'First constituent year based on lowest of (class year-4), first gift fiscal year, or APBCONS(AOBORGN)_CREATE_DATE';
   COMMENT ON COLUMN "PENTAHO"."C_CN_CONSTITUENT"."LAST_CONS_FY" IS 'Last constituent year based on highest of fiscal year of death, last gift fiscal year, or SPBPERS_ACTIVITY_DATE';
   COMMENT ON COLUMN "PENTAHO"."C_CN_CONSTITUENT"."PREF_COLLEGE_CODE" IS 'from APBCONS_COLL_CODE_PREF';
   COMMENT ON COLUMN "PENTAHO"."C_CN_CONSTITUENT"."PREF_COLLEGE_DESC" IS 'Description of PREF_COLLEGE_CODE';
   COMMENT ON COLUMN "PENTAHO"."C_CN_CONSTITUENT"."SPOUSE_CLASS_YEAR_PREF" IS 'CLASS_YEAR_PREF where PIDM = SPOUSE_PIDM';
   COMMENT ON COLUMN "PENTAHO"."C_CN_CONSTITUENT"."SPOUSE_DONOR_CODE_DESC" IS 'DONOR_CODE_DESC where PIDM = SPOUSE_PIDM';
   COMMENT ON COLUMN "PENTAHO"."C_CN_CONSTITUENT"."SPOUSE_DONOR_CODE_STRING" IS 'DONOR_CODE_STRING where PIDM = SPOUSE_PIDM';

  CREATE INDEX "PENTAHO"."C_CN_CONSTITUENT_BANNER_ID" ON "PENTAHO"."C_CN_CONSTITUENT" ("BANNER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERSPACE" ;

  CREATE INDEX "PENTAHO"."C_CN_CONSTITUENT_CLASS_YEAR" ON "PENTAHO"."C_CN_CONSTITUENT" ("CLASS_YEAR_PREF") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERSPACE" ;

  CREATE INDEX "PENTAHO"."C_CN_CONSTITUENT_DONOR_CODE" ON "PENTAHO"."C_CN_CONSTITUENT" ("DONOR_CODE_PRIMARY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERSPACE" ;

  CREATE INDEX "PENTAHO"."C_CN_CONSTITUENT_ENTITY_CODE" ON "PENTAHO"."C_CN_CONSTITUENT" ("ENTITY_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERSPACE" ;

  CREATE INDEX "PENTAHO"."C_CN_CONSTITUENT_ENTITY_ID" ON "PENTAHO"."C_CN_CONSTITUENT" ("BANNER_ID", "ENTITY_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERSPACE" ;

  CREATE UNIQUE INDEX "PENTAHO"."C_CN_CONSTITUENT_IDENTITY" ON "PENTAHO"."C_CN_CONSTITUENT" ("PIDM", "BANNER_ID", "ENTITY_CODE", "NAME_SORT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERSPACE" ;

  CREATE UNIQUE INDEX "PENTAHO"."C_CN_CONSTITUENT_NAME_ID" ON "PENTAHO"."C_CN_CONSTITUENT" ("PIDM", "BANNER_ID", "NAME_FIRST", "NAME_LAST") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERSPACE" ;

  CREATE INDEX "PENTAHO"."C_CN_CONSTITUENT_NAME_SORT" ON "PENTAHO"."C_CN_CONSTITUENT" ("NAME_SORT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERSPACE" ;

  CREATE INDEX "PENTAHO"."C_CN_CONSTITUENT_PERS" ON "PENTAHO"."C_CN_CONSTITUENT" ("NAME_FIRST", "NAME_MIDDLE", "NAME_PREFIX", "NAME_LAST", "ENTITY_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERSPACE" ;

  CREATE UNIQUE INDEX "PENTAHO"."C_CN_CONSTITUENT_PIDM_ID" ON "PENTAHO"."C_CN_CONSTITUENT" ("PIDM", "BANNER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERSPACE" ;

  CREATE INDEX "PENTAHO"."C_CN_CONSTITUENT_SPOUSE_PIDM" ON "PENTAHO"."C_CN_CONSTITUENT" ("SPOUSE_PIDM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERSPACE" ;

  CREATE INDEX "PENTAHO"."C_CN_CONSTITUENT_STAFF" ON "PENTAHO"."C_CN_CONSTITUENT" ("PRIMARY_STAFF_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERSPACE" ;