--BEGIN
  --dbms_snapshot.REFRESH('c_cn_special_purpose');
--END;

CREATE MATERIALIZED VIEW LOG ON H_CN_SPECIAL_PURPOSE;

CREATE MATERIALIZED VIEW C_CN_SPECIAL_PURPOSE refresh FAST ON demand
AS
  SELECT PIDM
  , BANNER_ID
  , NAME_SORT
  , ENTITY_CODE
  , PRTP_CODE
  , PRTP_DESC
  , PRCD_CODE
  , PRCD_DESC
  , DATE_START
  , PRTP_COMMENT
  , ACTIVITY_DATE
  , USER_ID
  , DATA_ORIGIN
  , RECORD_START_DATE
  FROM h_cn_SPECIAL_PURPOSE
  WHERE record_end_date IS NULL; 
  
  CREATE INDEX C_CN_SPECIAL_PIDM ON C_CN_SPECIAL_PURPOSE (PIDM) ;
  CREATE INDEX C_CN_SPECIAL_BANNER_ID ON C_CN_SPECIAL_PURPOSE (BANNER_ID) ;
  CREATE INDEX C_CN_SPECIAL_NAME_SORT ON C_CN_SPECIAL_PURPOSE (NAME_SORT) ;
  CREATE INDEX C_CN_SPECIAL_ENTITY_CODE ON C_CN_SPECIAL_PURPOSE (ENTITY_CODE) ;
  CREATE INDEX C_CN_SPECIAL_PRTP_CODE ON C_CN_SPECIAL_PURPOSE (PRTP_CODE) ;
  CREATE INDEX C_CN_SPECIAL_PRCD_CODE ON C_CN_SPECIAL_PURPOSE (PRCD_CODE) ;
