/*
BEGIN
  dbms_snapshot.REFRESH('C_CN_DONOR_CODES');
END;
*/
-- CREATE MATERIALIZED VIEW LOG ON H_CN_DONOR_CODES;
 
CREATE MATERIALIZED VIEW C_CN_DONOR_CODES refresh fast ON demand
AS
  SELECT PIDM
  , BANNER_ID
  , ENTITY_CODE
  , NAME_SORT
  , RECORD_START_DATE
  , DONOR_CODE_PRIMARY
  , ALMB
  , ALMX
  , ALMG
  , ALMH
  , STDG
  , STDT
  , FRGV
  , PARN
  , PART
  , PARL
  , PARX
  , DONT
  , WIDW
  , FACL
  , STAF
  , ZSUB
  , EMER
  , FFAC
  , RETS
  , FSTA
  , SPSE
  , SPST
  , RELA
  , FRND
  , ACAD
  , MEDI
  , ESTE
  , ESTF
  , ESTN
  , DAF
  , FDNA
  , FDNC
  , FDNF
  , FDNL
  , ASSN
  , CORP
  , FRCN
  , GOVR
  , RELG
  , OTHR
  , "SYS"
  , CONT
  FROM h_cn_donor_codes
  WHERE record_end_date IS NULL;
  
  
     COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_CODES"."PIDM" IS 'from CN_CONSTITUENT.PIDM';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_CODES"."BANNER_ID" IS 'from CN_CONSTITUENT.BANNER_ID';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_CODES"."ENTITY_CODE" IS 'from CN_CONSTITUENT.ENTITY_CODE';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_CODES"."NAME_SORT" IS 'from CN_CONSTITUENT.NAME_SORT';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_CODES"."DONOR_CODE_PRIMARY" IS 'from APRCATG_DONR_CODE with MIN(ATVDONR_RPT_SEQ_IND)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_CODES"."ALMB" IS 'DONR_CODE = ALMB / Alum - Undergraduate (Y/N)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_CODES"."ALMX" IS 'DONR_CODE = ALMX / Alum - Non-degreed (Y/N)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_CODES"."ALMG" IS 'DONR_CODE = ALMG / Alum - Graduate (Y/N)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_CODES"."ALMH" IS 'DONR_CODE = ALMH / Alum - Honorary (Y/N)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_CODES"."STDG" IS 'DONR_CODE = STDG / Student - Graduate (Y/N)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_CODES"."STDT" IS 'DONR_CODE = STDT / Student - Undergraduate (Y/N)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_CODES"."FRGV" IS 'DONR_CODE = FRGV / Alum - Global Village (Y/N)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_CODES"."PARN" IS 'DONR_CODE = PARN / Parent (Y/N)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_CODES"."PART" IS 'DONR_CODE = PART / Parent of Transfer Student (Y/N)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_CODES"."PARL" IS 'DONR_CODE = PARL / Parent of Student Who Left (Y/N)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_CODES"."PARX" IS 'DONR_CODE = PARX / Grandparent (Y/N)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_CODES"."DONT" IS 'DONR_CODE = DONT / DO NOT CONTACT OR ACCEPT GIFTS (Y/N)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_CODES"."WIDW" IS 'DONR_CODE = WIDW / Widow/Widower of Alum (Y/N)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_CODES"."FACL" IS 'DONR_CODE = FACL / Faculty (Y/N)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_CODES"."STAF" IS 'DONR_CODE = STAF / Staff (Y/N)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_CODES"."ZSUB" IS 'DONR_CODE = ZSUB / Zoellner Subscriber (Y/N)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_CODES"."EMER" IS 'DONR_CODE = EMER / Faculty Emeriti (Y/N)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_CODES"."FFAC" IS 'DONR_CODE = FFAC / Former Faculty (Y/N)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_CODES"."RETS" IS 'DONR_CODE = RETS / Retired Staff (Y/N)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_CODES"."FSTA" IS 'DONR_CODE = FSTA / Former Staff (Y/N)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_CODES"."SPSE" IS 'DONR_CODE = SPSE / Spouse/Partner of Alum (Y/N)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_CODES"."SPST" IS 'DONR_CODE = SPST / Spouse/Partner of Fac/Staff (Y/N)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_CODES"."RELA" IS 'DONR_CODE = RELA / Relative of Alum (Y/N)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_CODES"."FRND" IS 'DONR_CODE = FRND / Friend (Y/N)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_CODES"."ACAD" IS 'DONR_CODE = ACAD / RCEAS Contact - Academic (Y/N)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_CODES"."MEDI" IS 'DONR_CODE = MEDI / RCEAS Contact - Media (Y/N)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_CODES"."ESTE" IS 'DONR_CODE = ESTE / Estate - Alum/Alum Widow(er) (Y/N)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_CODES"."ESTF" IS 'DONR_CODE = ESTF / Estate - Friend (Y/N)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_CODES"."ESTN" IS 'DONR_CODE = ESTN / Estate - Non-Person (Y/N)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_CODES"."DAF" IS 'DONR_CODE = DAF  / Donor Advised Fund (Y/N)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_CODES"."FDNA" IS 'DONR_CODE = FDNA / Foundation - Independent (Y/N)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_CODES"."FDNC" IS 'DONR_CODE = FDNC / Foundation - Corporate (Y/N)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_CODES"."FDNF" IS 'DONR_CODE = FDNF / Foundation - Family and Trust (Y/N)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_CODES"."FDNL" IS 'DONR_CODE = FDNL / Foundation - Local (Y/N)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_CODES"."ASSN" IS 'DONR_CODE = ASSN / Association (Y/N)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_CODES"."CORP" IS 'DONR_CODE = CORP / Corporation (Y/N)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_CODES"."FRCN" IS 'DONR_CODE = FRCN / Fund Raising Consortia (Y/N)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_CODES"."GOVR" IS 'DONR_CODE = GOVR / Government (Y/N)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_CODES"."RELG" IS 'DONR_CODE = RELG / Religious Organization (Y/N)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_CODES"."OTHR" IS 'DONR_CODE = OTHR / Other Organization (Y/N)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_CODES"."SYS" IS 'DONR_CODE = SYS  / System (e.g. non-person) (Y/N)';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_CODES"."RECORD_START_DATE" IS 'Date record was created/changed in Banner';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_CODES"."CONT" IS 'DONR_CODE = CONT / Contact associated with constituent (Y/N)';
   
   
  CREATE INDEX "PENTAHO"."C_CN_DONOR_CODES_BANNER_ID" ON "PENTAHO"."C_CN_DONOR_CODES" ("BANNER_ID") ;
  CREATE INDEX "PENTAHO"."C_CN_DONOR_CODES_ENTITY_CODE" ON "PENTAHO"."C_CN_DONOR_CODES" ("ENTITY_CODE") ;
  CREATE INDEX "PENTAHO"."C_CN_DONOR_CODES_IDENTITY" ON "PENTAHO"."C_CN_DONOR_CODES" ("PIDM", "BANNER_ID", "ENTITY_CODE", "NAME_SORT") ;
  CREATE INDEX "PENTAHO"."C_CN_DONOR_CODES_IDX" ON "PENTAHO"."C_CN_DONOR_CODES" ("PIDM") ;
  CREATE INDEX "PENTAHO"."C_CN_DONOR_CODES_PRIMARY_CODE" ON "PENTAHO"."C_CN_DONOR_CODES" ("DONOR_CODE_PRIMARY") ;
