--BEGIN
--dbms_snapshot.REFRESH('C_CN_EXCLUSIONS');
--END;

CREATE MATERIALIZED VIEW LOG ON H_CN_ACTIVITIES_YEAR;

CREATE MATERIALIZED VIEW C_CN_ACTIVITIES_YEAR refresh FAST ON demand
AS
  SELECT
    PIDM
  , BANNER_ID
  , NAME_SORT
  , ENTITY_CODE
  , ACTIVITY_CODE
  , ACTIVITY_DESC
  , ACTIVITY_YEAR
  , ACTIVITY_DATE
  , BANNER_USER_ID
  , RECORD_START_DATE
  FROM
    h_cn_activities_year
  WHERE
    record_end_date IS NULL;

  CREATE UNIQUE INDEX "C_CN_ACTIVITIES_YEAR_PK" ON "C_CN_ACTIVITIES_YEAR" ("PIDM", "ACTIVITY_CODE", "ACTIVITY_YEAR");
  CREATE INDEX "C_CN_ACTIVITIES_YEAR_PIDM" ON "C_CN_ACTIVITIES_YEAR" ("PIDM");
  CREATE INDEX "C_CN_ACTIVITIES_YEAR_ID" ON "C_CN_ACTIVITIES_YEAR" ("BANNER_ID");
  CREATE INDEX "C_CN_ACTIVITIES_YEAR_CODE" ON "C_CN_ACTIVITIES_YEAR" ("ACTIVITY_CODE");
  CREATE INDEX "C_CN_ACTIVITIES_YEAR_YEAR" ON "C_CN_ACTIVITIES_YEAR" ("ACTIVITY_YEAR");

