--BEGIN
  --dbms_snapshot.REFRESH('C_CN_EXCLUSIONS');
--END;

CREATE MATERIALIZED VIEW LOG ON H_CN_EXCLUSIONS_BY_ID;

CREATE MATERIALIZED VIEW C_CN_EXCLUSIONS_BY_ID refresh FAST ON demand
AS
  SELECT PIDM
  , BANNER_ID
  , NAME_SORT
  , ENTITY_CODE
  , RECORD_START_DATE
  , TRUMP_IND
  , EXCL_DEC
  , EXCL_DNS
  , EXCL_HLD
  , EXCL_I1
  , EXCL_I10
  , EXCL_I12
  , EXCL_I14
  , EXCL_I15
  , EXCL_I16
  , EXCL_I17
  , EXCL_I18
  , EXCL_I19
  , EXCL_I20
  , EXCL_I21
  , EXCL_I22
  , EXCL_I23
  , EXCL_I24
  , EXCL_I25
  , EXCL_I27
  , EXCL_I28
  , EXCL_I29
  , EXCL_I30
  , EXCL_I31
  , EXCL_I32
  , EXCL_I33
  , EXCL_I34
  , EXCL_I35
  , EXCL_I36
  , EXCL_I37
  , EXCL_I38
  , EXCL_I39
  , EXCL_I4
  , EXCL_I40
  , EXCL_I41
  , EXCL_I42
  , EXCL_I43
  , EXCL_I44
  , EXCL_I45
  , EXCL_I46
  , EXCL_I47
  , EXCL_I48
  , EXCL_I49
  , EXCL_I50
  , EXCL_I51
  , EXCL_I52
  , EXCL_I53
  , EXCL_I54
  , EXCL_I55
  , EXCL_I56
  , EXCL_I57
  , EXCL_I58
  , EXCL_I59
  , EXCL_I60
  , EXCL_I61
  , EXCL_I62
  , EXCL_I63
  , EXCL_I64
  , EXCL_I65
  , EXCL_I66
  , EXCL_I67
  , EXCL_I68
  , EXCL_I69
  , EXCL_I70
  , EXCL_I71
  , EXCL_I72
  , EXCL_INL
  , EXCL_INR
  , EXCL_NAB
  , EXCL_NAC
  , EXCL_NAD
  , EXCL_NAE
  , EXCL_NAM
  , EXCL_NAT
  , EXCL_NAU
  , EXCL_NEM
  , EXCL_NES
  , EXCL_NIT
  , EXCL_NLP
  , EXCL_NMA
  , EXCL_NMG
  , EXCL_NML
  , EXCL_NOC
  , EXCL_NPC
  , EXCL_NRC
  , EXCL_NRM
  , EXCL_NTM
  , EXCL_NZC
  , EXCL_NZE
  , EXCL_NZM
  , EXCL_NZP
  , EXCL_RPD
  , EXCL_ZZZ
  , EXCL_I73
  FROM h_cn_exclusions_by_id
  WHERE record_end_date IS NULL; 
  
  CREATE UNIQUE INDEX C_CN_EXCLUSIONS_ID_BANNER_ID ON C_CN_EXCLUSIONS_BY_ID (BANNER_ID);
  CREATE INDEX C_CN_EXCLUSIONS_ID_NAME_SORT ON C_CN_EXCLUSIONS_BY_ID (NAME_SORT);
  CREATE INDEX C_CN_EXCLUSIONS_ID_ENTITY_CODE ON C_CN_EXCLUSIONS_BY_ID (ENTITY_CODE);
  CREATE UNIQUE INDEX C_CN_EXCLUSIONS_ID_START_DATE ON C_CN_EXCLUSIONS_BY_ID (PIDM, RECORD_START_DATE);
