--BEGIN
  --dbms_snapshot.REFRESH('C_CN_CONTACT_PREF');
--END;

CREATE MATERIALIZED VIEW LOG ON H_CN_CONTACT_PREF;

CREATE MATERIALIZED VIEW C_CN_CONTACT_PREF refresh FAST ON demand
AS
  SELECT  PIDM
  , BANNER_ID
  , NAME_SORT
  , ENTITY_CODE
  , PREF_ATYP_CODE
  , PREF_ATYP_DESC
  , PREF_DATE_FROM
  , PREF_DATE_TO
  , PREF_STREET1
  , PREF_STREET2
  , PREF_STREET3
  , PREF_CITY
  , PREF_STATE_CODE
  , PREF_STATE_DESC
  , PREF_ZIP9
  , PREF_ZIP5
  , PREF_COUNTY_CODE
  , PREF_COUNTY_DESC
  , PREF_NATION_CODE
  , PREF_NATION_DESC
  , PREF_STREET_COMB
  , PREF_CSZN_COMB
  , PREF_GEOREGION_CODE
  , PREF_GEOREGION_DESC
  , PREF_SUPEREGION
  , EMAIL_PREF_CODE
  , EMAIL_PREF_DESC
  , EMAIL_PREF_ADDRESS
  , EMAIL_LEHIGH
  , EMAIL_HOME
  , EMAIL_BUSINESS
  , TELE_PREF_CODE
  , TELE_PREF_DESC
  , TELE_PREF_NUMBER
  , TELE_HOME
  , TELE_CELL
  , TELE_BUSINESS
  , HOME_ATYP_CODE
  , HOME_ATYP_DESC
  , HOME_DATE_FROM
  , HOME_DATE_TO
  , HOME_STREET1
  , HOME_STREET2
  , HOME_STREET3
  , HOME_CITY
  , HOME_STATE_CODE
  , HOME_STATE_DESC
  , HOME_ZIP9
  , HOME_ZIP5
  , HOME_COUNTY_CODE
  , HOME_COUNTY_DESC
  , HOME_NATION_CODE
  , HOME_NATION_DESC
  , HOME_STREET_COMB
  , HOME_CSZN_COMB
  , HOME_GEOREGION_CODE
  , HOME_GEOREGION_DESC
  , HOME_SUPEREGION
  , BUSINESS_ATYP_CODE
  , BUSINESS_ATYP_DESC
  , BUSINESS_DATE_FROM
  , BUSINESS_DATE_TO
  , BUSINESS_STREET1
  , BUSINESS_STREET2
  , BUSINESS_STREET3
  , BUSINESS_CITY
  , BUSINESS_STATE_CODE
  , BUSINESS_STATE_DESC
  , BUSINESS_ZIP9
  , BUSINESS_ZIP5
  , BUSINESS_COUNTY_CODE
  , BUSINESS_COUNTY_DESC
  , BUSINESS_NATION_CODE
  , BUSINESS_NATION_DESC
  , BUSINESS_STREET_COMB
  , BUSINESS_CSZN_COMB
  , BUSINESS_GEOREGION_CODE
  , BUSINESS_GEOREGION_DESC
  , BUSINESS_SUPEREGION
  , RECORD_START_DATE
  FROM h_cn_contact_pref
  WHERE record_end_date IS NULL; 
  
  CREATE INDEX C_CN_CONTACT_PREF_ATYP ON C_CN_CONTACT_PREF (PREF_ATYP_CODE);
  CREATE UNIQUE INDEX C_CN_CONTACT_PREF_BANNER_ID ON C_CN_CONTACT_PREF (BANNER_ID);
  CREATE INDEX C_CN_CONTACT_PREF_CSZ5_PREF ON C_CN_CONTACT_PREF (PREF_CITY, PREF_STATE_CODE, PREF_ZIP5);
  CREATE INDEX C_CN_CONTACT_PREF_CSZ9_PREF ON C_CN_CONTACT_PREF (PREF_CITY, PREF_STATE_CODE, PREF_ZIP9);
  CREATE INDEX C_CN_CONTACT_PREF_CSZN_PREF ON C_CN_CONTACT_PREF (PREF_CSZN_COMB);
  CREATE INDEX C_CN_CONTACT_PREF_EMAIL_BU ON C_CN_CONTACT_PREF (EMAIL_BUSINESS);
  CREATE INDEX C_CN_CONTACT_PREF_EMAIL_CODE ON C_CN_CONTACT_PREF (EMAIL_PREF_CODE);
  CREATE INDEX C_CN_CONTACT_PREF_EMAIL_HO ON C_CN_CONTACT_PREF (EMAIL_HOME);
  CREATE INDEX C_CN_CONTACT_PREF_EMAIL_LU ON C_CN_CONTACT_PREF (EMAIL_LEHIGH);
  CREATE INDEX C_CN_CONTACT_PREF_EMAIL_PREF ON C_CN_CONTACT_PREF (EMAIL_PREF_ADDRESS);
  CREATE INDEX C_CN_CONTACT_PREF_ENTITY_CODE ON C_CN_CONTACT_PREF (ENTITY_CODE);
  CREATE INDEX C_CN_CONTACT_PREF_GEOR_PREF ON C_CN_CONTACT_PREF (PREF_GEOREGION_CODE);
  CREATE INDEX C_CN_CONTACT_PREF_NAME_SORT ON C_CN_CONTACT_PREF (NAME_SORT);
  CREATE INDEX C_CN_CONTACT_PREF_NATION_PREF ON C_CN_CONTACT_PREF (PREF_NATION_CODE, PREF_NATION_DESC);
  CREATE INDEX C_CN_CONTACT_PREF_SUPER_PREF ON C_CN_CONTACT_PREF (PREF_SUPEREGION);
  CREATE UNIQUE INDEX C_CN_CONTACT_PREF_TELE_BU ON C_CN_CONTACT_PREF (PIDM, TELE_BUSINESS);
  CREATE UNIQUE INDEX C_CN_CONTACT_PREF_TELE_CL ON C_CN_CONTACT_PREF (PIDM, TELE_CELL);
  CREATE UNIQUE INDEX C_CN_CONTACT_PREF_TELE_CODE ON C_CN_CONTACT_PREF (PIDM, PREF_ATYP_CODE);
  CREATE UNIQUE INDEX C_CN_CONTACT_PREF_TELE_HO ON C_CN_CONTACT_PREF (PIDM, TELE_HOME);
  CREATE UNIQUE INDEX C_CN_CONTACT_PREF_TELE_PREF ON C_CN_CONTACT_PREF (PIDM, TELE_PREF_NUMBER);



 