--BEGIN
--dbms_snapshot.REFRESH('C_CN_EMAIL');
--END;

CREATE MATERIALIZED VIEW LOG ON H_CN_ADDRESSES;

CREATE MATERIALIZED VIEW C_CN_ADDRESSES refresh fast ON demand
AS
  SELECT PIDM
  , BANNER_ID
  , NAME_SORT
  , ENTITY_CODE
  , ATYP_CODE
  , ATYP_DESC
  , SEQ_NO
  , ACTIVE_IND
  , PREF_BY_TYPE_IND
  , PREF_BY_ID_IND
  , DATE_FROM
  , DATE_TO
  , STREET_LINE1
  , STREET_LINE2
  , STREET_LINE3
  , STREET_LINE4
  , CITY
  , STATE_CODE
  , STATE_DESC
  , ZIP_CODE
  , COUNTY_CODE
  , COUNTY_DESC
  , NATION_CODE
  , NATION_DESC
  , STREET_COMB
  , CSZN_COMB
  , GEOREGION_CODE
  , GEOREGION_DESC
  , SUPEREGION
  , STATUS_IND
  , ACTIVITY_DATE
  , SOURCE_CODE
  , DELIVERY_POINT
  , CORRECTION_DIGIT
  , CARRIER_ROUTE
  , GST_TAX_ID
  , USER_ID
  , REVIEWED_IND
  , REVIEWED_USER
  , DATA_ORIGIN
  , PREF_RANK_BY_TYPE
  , PREF_RANK_BY_ID
  , RECORD_START_DATE
  FROM h_cn_addresses
  WHERE record_end_date IS NULL;


  CREATE INDEX "PENTAHO"."C_CN_ADDRESSES_ACTIVE_IND" ON "PENTAHO"."C_CN_ADDRESSES" ("ACTIVE_IND") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERSPACE" ;

  CREATE INDEX "PENTAHO"."C_CN_ADDRESSES_ENTITY_CODE" ON "PENTAHO"."C_CN_ADDRESSES" ("ENTITY_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERSPACE" ;

  CREATE INDEX "PENTAHO"."C_CN_ADDRESSES_GEOREGION" ON "PENTAHO"."C_CN_ADDRESSES" ("GEOREGION_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERSPACE" ;

  CREATE INDEX "PENTAHO"."C_CN_ADDRESSES_ID" ON "PENTAHO"."C_CN_ADDRESSES" ("BANNER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERSPACE" ;

  CREATE INDEX "PENTAHO"."C_CN_ADDRESSES_IDX" ON "PENTAHO"."C_CN_ADDRESSES" ("PIDM", "ATYP_CODE", "SEQ_NO", "STATUS_IND") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERSPACE" ;

  CREATE INDEX "PENTAHO"."C_CN_ADDRESSES_NAME_SORT" ON "PENTAHO"."C_CN_ADDRESSES" ("NAME_SORT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERSPACE" ;

  CREATE INDEX "PENTAHO"."C_CN_ADDRESSES_NATION" ON "PENTAHO"."C_CN_ADDRESSES" ("NATION_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERSPACE" ;

  CREATE INDEX "PENTAHO"."C_CN_ADDRESSES_PREF_ID" ON "PENTAHO"."C_CN_ADDRESSES" ("PREF_BY_ID_IND") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERSPACE" ;

  CREATE INDEX "PENTAHO"."C_CN_ADDRESSES_PREF_TYPE" ON "PENTAHO"."C_CN_ADDRESSES" ("PREF_BY_TYPE_IND") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERSPACE" ;

  CREATE INDEX "PENTAHO"."C_CN_ADDRESSES_SEQ_NO" ON "PENTAHO"."C_CN_ADDRESSES" ("SEQ_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERSPACE" ;

  CREATE INDEX "PENTAHO"."C_CN_ADDRESSES_STATE" ON "PENTAHO"."C_CN_ADDRESSES" ("STATE_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERSPACE" ;

  CREATE INDEX "PENTAHO"."C_CN_ADDRESSES_STATUS" ON "PENTAHO"."C_CN_ADDRESSES" ("STATUS_IND") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERSPACE" ;

  CREATE INDEX "PENTAHO"."C_CN_ADDRESSES_SUPEREGION" ON "PENTAHO"."C_CN_ADDRESSES" ("SUPEREGION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERSPACE" ;

  CREATE INDEX "PENTAHO"."C_CN_ADDRESSES_ZIP" ON "PENTAHO"."C_CN_ADDRESSES" ("ZIP_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERSPACE" ;