--BEGIN
  --dbms_snapshot.REFRESH('c_cn_georegion_by_id');
--END;

CREATE MATERIALIZED VIEW LOG ON H_CN_GEOREGION_BY_ID;

CREATE MATERIALIZED VIEW C_CN_GEOREGION_BY_ID refresh FAST ON demand
AS
  SELECT  PIDM
  ,  BANNER_ID
  ,  NAME_SORT
  ,  ENTITY_CODE
  ,  PREF_GEOREGION_CODE
  ,  RECORD_START_DATE
  ,  GEO_ALSK
  ,  GEO_ARIZ
  ,  GEO_ARKS
  ,  GEO_ATLA
  ,  GEO_AUST
  ,  GEO_BALT
  ,  GEO_BAMA
  ,  GEO_BOST
  ,  GEO_CCMA
  ,  GEO_CEFL
  ,  GEO_CENJ
  ,  GEO_CENY
  ,  GEO_CHAR
  ,  GEO_CHIC
  ,  GEO_CINC
  ,  GEO_COLA
  ,  GEO_COLU
  ,  GEO_COSC
  ,  GEO_CTVA
  ,  GEO_DAFW
  ,  GEO_DELA
  ,  GEO_FFCT
  ,  GEO_GUAM
  ,  GEO_HAWI
  ,  GEO_HOME
  ,  GEO_IDAH
  ,  GEO_INDY
  ,  GEO_INTL
  ,  GEO_IOWA
  ,  GEO_KASA
  ,  GEO_KENT
  ,  GEO_LGIS
  ,  GEO_MAIN
  ,  GEO_MICH
  ,  GEO_MIFL
  ,  GEO_MILT
  ,  GEO_MISS
  ,  GEO_MONT
  ,  GEO_NDAK
  ,  GEO_NEBR
  ,  GEO_NELV
  ,  GEO_NEPA
  ,  GEO_NERE
  ,  GEO_NEWH
  ,  GEO_NMEX
  ,  GEO_NOFL
  ,  GEO_NOLA
  ,  GEO_NONJ
  ,  GEO_NONY
  ,  GEO_NOOH
  ,  GEO_NWPA
  ,  GEO_NYNY
  ,  GEO_OKLA
  ,  GEO_ORCY
  ,  GEO_PAFL
  ,  GEO_PAOR
  ,  GEO_PAWA
  ,  GEO_PBGH
  ,  GEO_PHIL
  ,  GEO_PRCO
  ,  GEO_RDNC
  ,  GEO_RHIS
  ,  GEO_ROCH
  ,  GEO_ROCK
  ,  GEO_SAND
  ,  GEO_SARA
  ,  GEO_SDAK
  ,  GEO_SEPA
  ,  GEO_SFBY
  ,  GEO_SFLA
  ,  GEO_SOAZ
  ,  GEO_SOCA
  ,  GEO_SONJ
  ,  GEO_SONY
  ,  GEO_STLU
  ,  GEO_SUSQ
  ,  GEO_SVHH
  ,  GEO_SWFL
  ,  GEO_TBFL
  ,  GEO_TCFL
  ,  GEO_TENM
  ,  GEO_TENN
  ,  GEO_TEXS
  ,  GEO_TWIN
  ,  GEO_UTAH
  ,  GEO_VERT
  ,  GEO_VIRG
  ,  GEO_VRIS
  ,  GEO_WADC
  ,  GEO_WCAR
  ,  GEO_WECH
  ,  GEO_WENY
  ,  GEO_WISC
  ,  GEO_WVIR
  ,  GEO_WYOM
  FROM h_cn_georegion_by_id
  WHERE record_end_date IS NULL; 

  CREATE INDEX C_CN_GEOREGION_BY_ID_PIDM ON C_CN_GEOREGION_BY_ID (PIDM) ;
  CREATE INDEX C_CN_GEOREGION_BY_ID_BANNER_ID ON C_CN_GEOREGION_BY_ID (BANNER_ID) ;
  CREATE INDEX C_CN_GEOREGION_BY_ID_NAME_SORT ON C_CN_GEOREGION_BY_ID (NAME_SORT) ;
  CREATE INDEX C_CN_GEOREGION_BY_ID_ENTITY ON C_CN_GEOREGION_BY_ID (ENTITY_CODE) ;
  CREATE INDEX C_CN_GEOREGION_BY_ID_PREF_CODE ON C_CN_GEOREGION_BY_ID (PREF_GEOREGION_CODE) ;
