/*BEGIN
  dbms_snapshot.REFRESH('C_CN_CURRENT_NAMES');
END;
*/

--CREATE MATERIALIZED VIEW LOG ON H_CN_CURRENT_NAMES;

CREATE MATERIALIZED VIEW C_CN_CURRENT_NAMES refresh fast ON demand
AS
  SELECT PIDM
, BANNER_ID
, ENTITY_CODE
, NAME_SORT
, NAME_PREFIX
, FIRST_NAME
, MIDDLE_NAME
, LAST_NAME
, NAME_SUFFIX
, NICKNAME
, MAIDEN_NAME
, INFORMAL_SALU
, FORMAL_SALU
, COMBINED_INFORMAL_SALU
, COMBINED_FORMAL_SALU
, TOWR_SALUTATION
, INFORMAL_ADDRESS_NAME
, FORMAL_ADDRESS_NAME
, COMBINED_INFORMAL_ADDRESS_NAME
, COMBINED_FORMAL_ADDRESS_NAME
, ANNUAL_REPORT_NAME
, ANNUAL_REPORT_SUFFIX
, NAME_TAG_NAME
, NAME_TAG_FIRST_NAME
, NAME_TAG_MIDDLE_NAME
, NAME_TAG_LAST_NAME
, NAME_TAG_SUFFIX
, GIFT_SOCIETY_NAME
, AP_SOCIETY_NAME
, CY_SOCIETY_NAME
, LP_SOCIETY_NAME
, TW_SOCIETY_NAME
, ZG_SOCIETY_NAME
, ZI_SOCIETY_NAME
, JBPC_SALUTATION
, JBPF_SALUTATION
, RECORD_START_DATE
  FROM H_CN_CURRENT_NAMES
  WHERE record_end_date IS NULL; 
  
ALTER TABLE 
   C_CN_CURRENT_NAMES
ADD CONSTRAINT 
   C_CN_CURRENT_NAMES_PK
PRIMARY KEY (PIDM, RECORD_START_DATE);

  CREATE INDEX "PENTAHO"."C_CN_CURRENT_NAMES_BANNER_ID" ON "PENTAHO"."C_CN_CURRENT_NAMES" ("BANNER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERSPACE" ;

  CREATE INDEX "PENTAHO"."C_CN_CURRENT_NAMES_ENTITY" ON "PENTAHO"."C_CN_CURRENT_NAMES" ("ENTITY_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERSPACE" ;

  CREATE INDEX "PENTAHO"."C_CN_CURRENT_NAMES_IDX" ON "PENTAHO"."C_CN_CURRENT_NAMES" ("PIDM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERSPACE" ;

  CREATE INDEX "PENTAHO"."C_CN_CURRENT_NAMES_NAME_SORT" ON "PENTAHO"."C_CN_CURRENT_NAMES" ("NAME_SORT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 167 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERSPACE" ;




