--BEGIN
  --dbms_snapshot.REFRESH('c_cn_variable_purpose');
--END;

--CREATE MATERIALIZED VIEW LOG ON H_CN_VARIABLE_PURPOSE;

CREATE MATERIALIZED VIEW C_CN_VARIABLE_PURPOSE refresh FAST ON demand
AS
  SELECT PIDM
  ,  BANNER_ID
  ,  NAME_SORT
  ,  ENTITY_CODE
  ,  VIPC_CODE
  ,  VIPC_DESC
  ,  ACTIVITY_DATE
  ,  USER_ID
  ,  DATA_ORIGIN
  ,  RECORD_START_DATE
  FROM h_cn_variable_purpose
  WHERE record_end_date IS NULL; 

  CREATE INDEX C_CN_VARIABLE_BANNER_ID ON C_CN_VARIABLE_PURPOSE (BANNER_ID) ;
  CREATE INDEX C_CN_VARIABLE_ENTITY_CODE ON C_CN_VARIABLE_PURPOSE (ENTITY_CODE) ;
  CREATE INDEX C_CN_VARIABLE_NAME_SORT ON C_CN_VARIABLE_PURPOSE (NAME_SORT) ;
  CREATE INDEX C_CN_VARIABLE_PIDM ON C_CN_VARIABLE_PURPOSE (PIDM) ;
  CREATE INDEX C_CN_VARIABLE_VIPC_CODE ON C_CN_VARIABLE_PURPOSE (VIPC_CODE) ;
