--BEGIN
  --dbms_snapshot.REFRESH('C_CN_EXCLUSIONS');
--END;

CREATE MATERIALIZED VIEW LOG ON H_CN_ACTIVITIES;

CREATE MATERIALIZED VIEW C_CN_ACTIVITIES refresh FAST ON demand
AS
  SELECT PIDM
  , BANNER_ID
  , NAME_SORT
  , ENTITY_CODE
  , ACTIVITY_CODE
  , ACTIVITY_DESC
  , ACTP_CODE
  , ACTP_DESC
  , ACCG_CODE
  , ACCG_DESC
  , ACTIVITY_COMMENT
  , ACTIVITY_DATE
  , USER_ID
  , DATA_ORIGIN
  , ACTIVITY_GROUP
  , MIN_YEAR
  , MAX_YEAR
  , YEAR_COUNT
  , ACTIVITY_GROUP_CODE
  , ACTIVITY_GROUP_DESC
  , VOLUNTEER_GROUP_CODE
  , VOLUNTEER_GROUP_DESC
  , CURRENT_YEAR_IND
  , RECORD_START_DATE
  FROM h_cn_activities
  WHERE record_end_date IS NULL; 
  
  CREATE INDEX C_CN_ACTIVITIES_BANNER_ID ON C_CN_ACTIVITIES (BANNER_ID);
  CREATE INDEX C_CN_ACTIVITIES_NAME_SORT ON C_CN_ACTIVITIES (NAME_SORT);
  CREATE INDEX C_CN_ACTIVITIES_ENTITY_CODE ON C_CN_ACTIVITIES (ENTITY_CODE);
  CREATE INDEX C_CN_ACTIVITIES_ACTP_CODE ON C_CN_ACTIVITIES (ACTP_CODE);
  CREATE INDEX C_CN_ACTIVITIES_ACCG_CODE ON C_CN_ACTIVITIES (ACCG_CODE);
  CREATE INDEX C_CN_ACTIVITIES_MIN_YEAR ON C_CN_ACTIVITIES (MIN_YEAR);
  CREATE INDEX C_CN_ACTIVITIES_MAX_YEAR ON C_CN_ACTIVITIES (MAX_YEAR);
