/*BEGIN
  dbms_snapshot.REFRESH('C_CN_DONOR_STATUS');
END;
*/

CREATE MATERIALIZED VIEW LOG ON H_CN_DONOR_STATUS;

CREATE MATERIALIZED VIEW C_CN_DONOR_STATUS REFRESH FAST ON DEMAND
AS
  SELECT PIDM
, BANNER_ID
, NAME_SORT
, ENTITY_CODE
, record_start_date
, reporting_year
, donor_status
, years_since
, LAST_CASH_CREDIT_YEAR
, LAST_CASH_CREDIT_DATE
, LAST_CASH_CREDIT_NUMBER
, LAST_CASH_CREDIT_DESG_CODE
, LAST_CASH_CREDIT_DESG_DESC
, LAST_CASH_CREDIT_AMOUNT
, FIRST_CASH_CREDIT_YEAR
, FIRST_CASH_CREDIT_DATE
, FIRST_CASH_CREDIT_NUMBER
, FIRST_CASH_CREDIT_DESG_CODE
, FIRST_CASH_CREDIT_DESG_DESC
, FIRST_CASH_CREDIT_AMOUNT
, LARGEST_CASH_CREDIT_YEAR
, LARGEST_CASH_CREDIT_DATE
, LARGEST_CASH_CREDIT_NUMBER
, LARGEST_CASH_CREDIT_DESG_CODE
, LARGEST_CASH_CREDIT_DESG_DESC
, LARGEST_CASH_CREDIT_AMOUNT
, LAST_PLDG_CREDIT_YEAR
, LAST_PLDG_CREDIT_DATE
, LAST_PLDG_CREDIT_NUMBER
, LAST_PLDG_CREDIT_DESG_CODE
, LAST_PLDG_CREDIT_DESG_DESC
, LAST_PLDG_CREDIT_AMOUNT
, FIRST_PLDG_CREDIT_YEAR
, FIRST_PLDG_CREDIT_DATE
, FIRST_PLDG_CREDIT_NUMBER
, FIRST_PLDG_CREDIT_DESG_CODE
, FIRST_PLDG_CREDIT_DESG_DESC
, FIRST_PLDG_CREDIT_AMOUNT
, LARGEST_PLDG_CREDIT_YEAR
, LARGEST_PLDG_CREDIT_DATE
, LARGEST_PLDG_CREDIT_NUMBER
, LARGEST_PLDG_CREDIT_DESG_CODE
, LARGEST_PLDG_CREDIT_DESG_DESC
, LARGEST_PLDG_CREDIT_AMOUNT
, APS_donor_status
, APS_LEVEL_CODE
, APS_LEVEL_DESC
, APS_years_since
, APS_LAST_YEAR
, APS_LAST_LEVEL_CODE
, APS_LAST_LEVEL_DESC
, SM_donor_status
, SM_LEVEL_CODE
, SM_LEVEL_DESC
, SM_years_since
, SM_LAST_YEAR
, SM_LAST_LEVEL_CODE
, SM_LAST_LEVEL_DESC
  FROM h_cn_donor_status
  WHERE record_end_date IS NULL;

ALTER TABLE 
   C_CN_DONOR_STATUS
ADD CONSTRAINT 
   C_CN_DONOR_STATUS_PK
PRIMARY KEY (PIDM, REPORTING_YEAR, RECORD_START_DATE);

   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS"."PIDM" IS 'from CN_CONSTITUENT.PIDM';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS"."BANNER_ID" IS 'from CN_CONSTITUENT.BANNER_ID';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS"."NAME_SORT" IS 'from CN_CONSTITUENT.NAME_SORT';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS"."ENTITY_CODE" IS 'from CN_CONSTITUENT.ENTITY_CODE';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS"."REPORTING_YEAR" IS 'Fiscal Year (FY) of reporting row';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS"."DONOR_STATUS" IS 'Donor status as of close of previous business day';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS"."YEARS_SINCE" IS 'Number of fiscal years since last gift';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS"."LAST_CASH_CREDIT_YEAR" IS 'FY of most recent gift made';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS"."LAST_CASH_CREDIT_DATE" IS 'Date of most recent gift made';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS"."LAST_CASH_CREDIT_NUMBER" IS 'Gift number of most recent gift made';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS"."LAST_CASH_CREDIT_DESG_CODE" IS 'Designation code of most recent gift made';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS"."LAST_CASH_CREDIT_DESG_DESC" IS 'Designation name of most recent gift made';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS"."LAST_CASH_CREDIT_AMOUNT" IS 'Amount of most recent gift made';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS"."FIRST_CASH_CREDIT_YEAR" IS 'FY of first gift recorded in Banner';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS"."FIRST_CASH_CREDIT_DATE" IS 'Date of first gift recorded in Banner';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS"."FIRST_CASH_CREDIT_NUMBER" IS 'Gift number of first gift recorded in Banner';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS"."FIRST_CASH_CREDIT_DESG_CODE" IS 'Designation code of first gift recorded in Banner';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS"."FIRST_CASH_CREDIT_DESG_DESC" IS 'Designation name of first gift recorded in Banner';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS"."FIRST_CASH_CREDIT_AMOUNT" IS 'Amount of first gift recorded in Banner';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS"."LARGEST_CASH_CREDIT_YEAR" IS 'FY of largest single gift recorded';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS"."LARGEST_CASH_CREDIT_DATE" IS 'Date of largest single gift recorded';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS"."LARGEST_CASH_CREDIT_NUMBER" IS 'Gift number of largest single gift recorded';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS"."LARGEST_CASH_CREDIT_DESG_CODE" IS 'Designation code of largest single gift recorded';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS"."LARGEST_CASH_CREDIT_DESG_DESC" IS 'Designation name of largest single gift recorded';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS"."LARGEST_CASH_CREDIT_AMOUNT" IS 'Amount of largest single gift recorded';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS"."LAST_PLDG_CREDIT_YEAR" IS 'FY of most recent pledge recorded';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS"."LAST_PLDG_CREDIT_DATE" IS 'Date of most recent pledge recorded';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS"."LAST_PLDG_CREDIT_NUMBER" IS 'Pledge number of most recent pledge recorded';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS"."LAST_PLDG_CREDIT_DESG_CODE" IS 'Designation code of most recent pledge recorded';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS"."LAST_PLDG_CREDIT_DESG_DESC" IS 'Designation name of most recent pledge recorded';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS"."LAST_PLDG_CREDIT_AMOUNT" IS 'Amount of most recent pledge recorded';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS"."FIRST_PLDG_CREDIT_YEAR" IS 'FY of first pledge recorded in Banner';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS"."FIRST_PLDG_CREDIT_DATE" IS 'Date of first pledge recorded in Banner';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS"."FIRST_PLDG_CREDIT_NUMBER" IS 'Pledge number of first pledge recorded in Banner';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS"."FIRST_PLDG_CREDIT_DESG_CODE" IS 'Designation code of first pledge recorded in Banner';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS"."FIRST_PLDG_CREDIT_DESG_DESC" IS 'Designation name of first pledge recorded in Banner';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS"."FIRST_PLDG_CREDIT_AMOUNT" IS 'Amount of first pledge recorded in Banner';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS"."LARGEST_PLDG_CREDIT_YEAR" IS 'FY of largest single pledge recorded';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS"."LARGEST_PLDG_CREDIT_DATE" IS 'Date of largest single pledge recorded';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS"."LARGEST_PLDG_CREDIT_NUMBER" IS 'Pledge number of largest single pledge recorded';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS"."LARGEST_PLDG_CREDIT_DESG_CODE" IS 'Designation code of largest single pledge recorded';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS"."LARGEST_PLDG_CREDIT_DESG_DESC" IS 'Designation name of largest single pledge recorded';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS"."LARGEST_PLDG_CREDIT_AMOUNT" IS 'Amount of largest single pledge recorded';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS"."APS_DONOR_STATUS" IS 'APS Donor status as of close of previous business day';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS"."APS_YEARS_SINCE" IS 'Number of years since last in Asa Packer Society';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS"."APS_LAST_YEAR" IS 'Last fiscal year of APS membership';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS"."APS_LAST_LEVEL_CODE" IS 'APS Level code when last in APS Society';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS"."APS_LAST_LEVEL_DESC" IS 'APS Level name when last in APS Society';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS"."SM_DONOR_STATUS" IS 'SM Donor status as of close of previous business day -- begins where DCNP_CODE >= 02';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS"."SM_YEARS_SINCE" IS 'Number of years since last in South Mtn Society';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS"."SM_LAST_YEAR" IS 'Last fiscal year of SM membership';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS"."SM_LAST_LEVEL_CODE" IS 'SM Level code when last in SM Society -- excludes 01';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS"."SM_LAST_LEVEL_DESC" IS 'SM Level name when last in SM Society -- excludes Year One';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS"."APS_LEVEL_CODE" IS 'Current APS level code';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS"."APS_LEVEL_DESC" IS 'Current APS level description';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS"."SM_LEVEL_CODE" IS 'Current South Mountain level code';
   COMMENT ON COLUMN "PENTAHO"."C_CN_DONOR_STATUS"."SM_LEVEL_DESC" IS 'Current South Mountain level description';
  
  CREATE INDEX "PENTAHO"."C_CN_DONOR_STATUS_APS_STATUS" ON "PENTAHO"."C_CN_DONOR_STATUS" ("APS_DONOR_STATUS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERSPACE" ;

  CREATE INDEX "PENTAHO"."C_CN_DONOR_STATUS_BANNER_ID" ON "PENTAHO"."C_CN_DONOR_STATUS" ("BANNER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERSPACE" ;

  CREATE INDEX "PENTAHO"."C_CN_DONOR_STATUS_DONOR_STATUS" ON "PENTAHO"."C_CN_DONOR_STATUS" ("DONOR_STATUS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERSPACE" ;

  CREATE INDEX "PENTAHO"."C_CN_DONOR_STATUS_ENTITY_CODE" ON "PENTAHO"."C_CN_DONOR_STATUS" ("ENTITY_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERSPACE" ;

  CREATE UNIQUE INDEX "PENTAHO"."C_CN_DONOR_STATUS_IDENTITY" ON "PENTAHO"."C_CN_DONOR_STATUS" ("PIDM", "BANNER_ID", "NAME_SORT", "ENTITY_CODE", "REPORTING_YEAR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERSPACE" ;

  CREATE INDEX "PENTAHO"."C_CN_DONOR_STATUS_NAME_SORT" ON "PENTAHO"."C_CN_DONOR_STATUS" ("NAME_SORT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERSPACE" ;

  CREATE INDEX "PENTAHO"."C_CN_DONOR_STATUS_SM_STATUS" ON "PENTAHO"."C_CN_DONOR_STATUS" ("SM_DONOR_STATUS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERSPACE" ;
  
  