--BEGIN
  --dbms_snapshot.REFRESH('c_cn_mail_code_by_id');
--END;

CREATE MATERIALIZED VIEW LOG ON H_CN_MAIL_CODE_BY_ID;

CREATE MATERIALIZED VIEW C_CN_MAIL_CODE_BY_ID refresh FAST ON demand
AS
  SELECT  PIDM
  ,  BANNER_ID
  ,  NAME_SORT
  ,  ENTITY_CODE
  ,  RECORD_START_DATE
  ,  MAIL_AAT
  ,  MAIL_ABR
  ,  MAIL_ACU
  ,  MAIL_ADE
  ,  MAIL_AF6
  ,  MAIL_ALB
  ,  MAIL_ATB
  ,  MAIL_ATT
  ,  MAIL_AW6
  ,  MAIL_BAN
  ,  MAIL_BER
  ,  MAIL_BLN
  ,  MAIL_BMV
  ,  MAIL_BVN
  ,  MAIL_BVO
  ,  MAIL_CAS
  ,  MAIL_CBA
  ,  MAIL_CNF
  ,  MAIL_CPM
  ,  MAIL_CRE
  ,  MAIL_ENG
  ,  MAIL_ENT
  ,  MAIL_FYI
  ,  MAIL_GLU
  ,  MAIL_HCC
  ,  MAIL_HCF
  ,  MAIL_ICA
  ,  MAIL_ICH
  ,  MAIL_ICO
  ,  MAIL_IFR
  ,  MAIL_IGE
  ,  MAIL_IHK
  ,  MAIL_IIN
  ,  MAIL_IIT
  ,  MAIL_IJA
  ,  MAIL_IKO
  ,  MAIL_IMA
  ,  MAIL_IME
  ,  MAIL_IN2
  ,  MAIL_IN3
  ,  MAIL_IN4
  ,  MAIL_INV
  ,  MAIL_IPE
  ,  MAIL_ISI
  ,  MAIL_ISP
  ,  MAIL_ISW
  ,  MAIL_ITA
  ,  MAIL_ITH
  ,  MAIL_ITU
  ,  MAIL_IUK
  ,  MAIL_IVE
  ,  MAIL_JNL
  ,  MAIL_LUD
  ,  MAIL_LWA
  ,  MAIL_LWB
  ,  MAIL_LWD
  ,  MAIL_LWF
  ,  MAIL_LWS
  ,  MAIL_LWX
  ,  MAIL_LWY
  ,  MAIL_LWZ
  ,  MAIL_MYL
  ,  MAIL_PGD
  ,  MAIL_PGP
  ,  MAIL_POP
  ,  MAIL_RE2
  ,  MAIL_REE
  ,  MAIL_REM
  ,  MAIL_RES
  ,  MAIL_SAV
  ,  MAIL_TWR
  ,  MAIL_B01
  ,  MAIL_B02
  ,  MAIL_B03
  ,  MAIL_B04
  ,  MAIL_B05
  ,  MAIL_B06
  ,  MAIL_B07
  ,  MAIL_B08
  ,  MAIL_B09
  ,  MAIL_B10
  ,  MAIL_B11
  ,  MAIL_B12
  ,  MAIL_B13
  ,  MAIL_B14
  ,  MAIL_B15
  ,  MAIL_B16
  ,  MAIL_B17
  ,  MAIL_B18
  ,  MAIL_B19
  ,  MAIL_B20
  ,  MAIL_B21
  ,  MAIL_B22
  ,  MAIL_B23
  FROM h_cn_mail_code_by_id
  WHERE record_end_date IS NULL; 

  CREATE INDEX C_CN_MAIL_CODE_BY_ID_PIDM ON C_CN_MAIL_CODE_BY_ID (PIDM) ;
  CREATE INDEX C_CN_MAIL_CODE_BY_ID_BANNER_ID ON C_CN_MAIL_CODE_BY_ID (BANNER_ID) ;
  CREATE INDEX C_CN_MAIL_CODE_BY_ID_NAME_SORT ON C_CN_MAIL_CODE_BY_ID (NAME_SORT) ;
  CREATE INDEX C_CN_MAIL_CODE_BY_ID_ENTITY ON C_CN_MAIL_CODE_BY_ID (ENTITY_CODE) ;
