--BEGIN
  --dbms_snapshot.REFRESH('c_cn_mail_code');
--END;

CREATE MATERIALIZED VIEW LOG ON H_CN_MAIL_CODE;

CREATE MATERIALIZED VIEW C_CN_MAIL_CODE refresh FAST ON demand
AS
  SELECT PIDM
  , BANNER_ID
  , NAME_SORT
  , ENTITY_CODE
  , MAIL_CODE
  , MAIL_DESC
  , ATYP_CODE
  , ATYP_DESC
  , DATE_START
  , ACTIVITY_DATE
  , MAIL_USER
  , USER_ID
  , DATA_ORIGIN
  , RECORD_START_DATE
  FROM h_cn_MAIL_CODE
  WHERE record_end_date IS NULL; 
  
  CREATE INDEX C_CN_MAIL_CODE_PIDM ON C_CN_MAIL_CODE (PIDM) ;
  CREATE INDEX C_CN_MAIL_CODE_BANNER_ID ON C_CN_MAIL_CODE (BANNER_ID) ;
  CREATE INDEX C_CN_MAIL_CODE_NAME_SORT ON C_CN_MAIL_CODE (NAME_SORT) ;
  CREATE INDEX C_CN_MAIL_CODE_ENTITY_CODE ON C_CN_MAIL_CODE (ENTITY_CODE) ;
  CREATE INDEX C_CN_MAIL_CODE_MAIL_CODE ON C_CN_MAIL_CODE (MAIL_CODE) ;
  CREATE INDEX C_CN_MAIL_CODE_ATYP_CODE ON C_CN_MAIL_CODE (ATYP_CODE) ;
