/*BEGIN
  dbms_snapshot.REFRESH('c_cn_mg_org_info');
END;
*/

--CREATE MATERIALIZED VIEW LOG ON H_CN_MG_ORG_INFO;

CREATE MATERIALIZED VIEW C_CN_MG_ORG_INFO refresh FAST ON demand
AS
  SELECT PIDM
  , BANNER_ID
  , NAME_SORT
  , ENTITY_CODE
  , MATCH_PCT
  , MATCH_ORG_MAX
  , MATCH_PERSON_MAX
  , MG_PIDM
  , OTH_ED_MG_IND
  , STATE_ASSOC_MG_IND
  , DESG_MG_IND
  , MDIS_CODE
  , MDIS_MM
  , MDIS_DD
  , MDIS_DEADLINE_MM
  , MDIS_DEADLINE_DD
  , DUPL_MG_IND
  , MG_ACK_IND
  , MGMT_MG_IND
  , MATCH_PERS_INST_YR
  , MATCH_ORG_CEILING_YR
  , MATCH_ORG_EMPL_YR
  , MATCH_MINIMUM
  , YEAR_MG
  , MG_LOAD_UPDATE_DATE
  , MG_LOAD_SOURCE
  , MG_RECEIPT_IND
  , MATCH_MAXIMUM
  , MG_LOAD_ID
  , RECORD_START_DATE
  FROM H_CN_MG_ORG_INFO
  WHERE record_end_date IS NULL;

  CREATE INDEX C_CN_MG_ORG_INFO_PIDM ON C_CN_MG_ORG_INFO (PIDM) ;
  CREATE INDEX C_CN_MG_ORG_INFO_BANNER_ID ON C_CN_MG_ORG_INFO (BANNER_ID) ;
  CREATE INDEX C_CN_MG_ORG_INFO_NAME_SORT ON C_CN_MG_ORG_INFO (NAME_SORT) ;
  CREATE INDEX C_CN_MG_ORG_INFO_ENTITY ON C_CN_MG_ORG_INFO (ENTITY_CODE) ;
