/*
BEGIN
  dbms_snapshot.REFRESH('c_gi_designations');
END;
*/

 CREATE MATERIALIZED VIEW LOG ON h_gi_designations;


CREATE MATERIALIZED VIEW c_gi_designations refresh fast ON demand
AS
  SELECT DESIGNATION_CODE
  , DESIGNATION_NAME
  , ENDOWMENT_IND
  , CAPITAL_IND
  , CURRENT_USE_IND
  , ZOELLNER_IND
  , ATHLETICS_IND
  , GL_NO_CREDIT
  , RESTR_IND
  , COLL_CODE
  , COLL_DESC
  , CFAE_TYPE_CODE
  , CFAE_CODE
  , CFAE_DESC
  , OUTRIGHT_GIFT_SUM
  , MG_PMT_SUM
  , PLEDGE_PMT_SUM
  , COUNTABLE_PLEDGE_SUM
  , PLEDGE_PAID_SUM
  , PLEDGE_BALANCE_SUM
  , NOT_COUNTABLE_PLEDGE_SUM
  , TESTAMENTARY_COMMITMENT_SUM
  , CASH_CREDIT_SUM
  , COMMITMENT_CREDIT_SUM
  , COAS_CODE
  , ACCI_CODE
  , FUND_CODE
  , FUND_DESC
  , ORGN_CODE
  , ACCT_CODE
  , PROG_CODE
  , ACTV_CODE
  , LOCN_CODE
  , DSTP_CODE
  , DSTP_DESC
  , DSTA_CODE
  , DSTA_DESC
  , DGRP_CODE
  , DGRP_DESC
  , DEPT_CODE
  , DEPT_DESC
  , LU_DESG_CLASS
  , COAS_CODE_PYMNT
  , ACCI_CODE_PYMNT
  , FUND_CODE_PYMNT
  , ORGN_CODE_PYMNT
  , ACCT_CODE_PYMNT
  , PROG_CODE_PYMNT
  , BANNER_USER
  , DESG_START_DATE
  , DESG_END_DATE
  , ACTIVITY_DATE
  , USER_ID
  , DATA_ORIGIN
  , ALERT_ACT_IND
  , ALERT_TEXT
  , record_start_date
  FROM h_gi_designations
  WHERE record_end_date IS NULL;


  CREATE INDEX "PENTAHO"."C_GI_DESIGNATIONS_ACCI_CODE" ON "PENTAHO"."C_GI_DESIGNATIONS" ("ACCI_CODE") ;
  CREATE INDEX "PENTAHO"."C_GI_DESIGNATIONS_ATHL_IND" ON "PENTAHO"."C_GI_DESIGNATIONS" ("ATHLETICS_IND") ;
  CREATE INDEX "PENTAHO"."C_GI_DESIGNATIONS_CAP_IND" ON "PENTAHO"."C_GI_DESIGNATIONS" ("CAPITAL_IND") ;
  CREATE INDEX "PENTAHO"."C_GI_DESIGNATIONS_CFAE_CODE" ON "PENTAHO"."C_GI_DESIGNATIONS" ("CFAE_CODE") ;
  CREATE INDEX "PENTAHO"."C_GI_DESIGNATIONS_CFAE_TYPE" ON "PENTAHO"."C_GI_DESIGNATIONS" ("CFAE_TYPE_CODE") ;
  CREATE INDEX "PENTAHO"."C_GI_DESIGNATIONS_COAS" ON "PENTAHO"."C_GI_DESIGNATIONS" ("COAS_CODE") ;
  CREATE INDEX "PENTAHO"."C_GI_DESIGNATIONS_COLL_CODE" ON "PENTAHO"."C_GI_DESIGNATIONS" ("COLL_CODE") ;
  CREATE INDEX "PENTAHO"."C_GI_DESIGNATIONS_CUR_IND" ON "PENTAHO"."C_GI_DESIGNATIONS" ("CURRENT_USE_IND") ;
  CREATE INDEX "PENTAHO"."C_GI_DESIGNATIONS_DEPT_CODE" ON "PENTAHO"."C_GI_DESIGNATIONS" ("DEPT_CODE") ;
  CREATE INDEX "PENTAHO"."C_GI_DESIGNATIONS_ENDOW_IND" ON "PENTAHO"."C_GI_DESIGNATIONS" ("ENDOWMENT_IND") ;
  CREATE INDEX "PENTAHO"."C_GI_DESIGNATIONS_FUND_CODE" ON "PENTAHO"."C_GI_DESIGNATIONS" ("FUND_CODE") ;
  CREATE INDEX "PENTAHO"."C_GI_DESIGNATIONS_CODE" ON "PENTAHO"."C_GI_DESIGNATIONS" ("DESIGNATION_CODE") ;
  CREATE INDEX "PENTAHO"."C_GI_DESIGNATIONS_RESTR_IND" ON "PENTAHO"."C_GI_DESIGNATIONS" ("RESTR_IND") ;
  CREATE INDEX "PENTAHO"."C_GI_DESIGNATIONS_ZOEL_IND" ON "PENTAHO"."C_GI_DESIGNATIONS" ("ZOELLNER_IND") ;
