/*BEGIN
dbms_snapshot.REFRESH('C_GI_CREDIT_DETAIL');
END;
*/

-- CREATE MATERIALIZED VIEW LOG ON H_GI_CREDIT_DETAIL;

CREATE MATERIALIZED VIEW C_GI_CREDIT_DETAIL refresh fast ON demand
AS
  SELECT PIDM
  , BANNER_ID
  , ENTITY_CODE
  , NAME_SORT
  , RECORD_CODE
  , RECORD_DESC
  , GIFT_NUM
  , PLEDGE_NUM
  , FISCAL_YEAR
  , CAMPAIGN_CODE
  , CAMPAIGN_DESC
  , DESIGNATION_CODE
  , DESIGNATION_DESC
  , TRANSACTION_TYPE
  , TRANSACTION_TYPE_DESC
  , PLEDGE_STATUS
  , PLEDGE_STATUS_DESC
  , ENTRY_DATE
  , ACTIVITY_DATE
  , OUTRIGHT_GIFT
  , MG_PMT
  , PLEDGE_PMT
  , COUNTABLE_PLEDGE
  , PLEDGE_PAID_TOTAL
  , PLEDGE_BALANCE
  , NOT_COUNTABLE_PLEDGE
  , NOT_COUNTABLE_PLEDGE_BALANCE
  , MEMO_OUTRIGHT_GIFT
  , MEMO_MG_PMT
  , MEMO_PLEDGE_PMT
  , MEMO_COUNT_PLEDGE
  , MEMO_PLEDGE_PAID_TOTAL
  , MEMO_PLEDGE_BALANCE
  , MEMO_NOT_COUNT_PLEDGE
  , MEMO_NOT_COUNT_PLEDGE_BALANCE
  , THIRD_PARTY_PMT
  , TESTAMENTARY_COMMIT_CREDIT
  , CASH_CREDIT_PERSON
  , CASH_CREDIT_TRANSACTION
  , COMMITMENT_CREDIT_PERSON
  , COMMITMENT_CREDIT_TRANSACTION
  , CLASS_CODE_1
  , CLASS_CODE_2
  , CLASS_CODE_3
  , CLASS_DESC_1
  , CLASS_DESC_2
  , CLASS_DESC_3
  , COMPCAMP_CODE
  , COMPCAMP_DESC
  , TRANSACTION_DATE
  , VEHICLE_CODE
  , VEHICLE_DESC
  , MG_TOTAL_COUNT
  , MG_TOTAL_AMOUNT
  , MG_UNPAID_COUNT
  , MG_UNPAID_AMOUNT
  , MG_PAID_COUNT
  , MG_PAID_AMOUNT
  , MATCHED_GIFT_NUM
  , MATCHING_GIFT_NUM
  , TRANSACTION_CATEGORY
  , TRANSACTION_AMOUNT
  , TRANSACTION_PLEDGE_BALANCE
  , TRANSACTION_PLEDGE_TOTAL
  , TRANSACTION_COMMENT
  , MEMO_FROM_PIDM
  , MEMO_FROM_BANNER_ID
  , MEMO_FROM_ENTITY_CODE
  , MEMO_FROM_NAME_SORT
  , MEMO_THIRD_PARTY_PMT
  , THIRD_PARTY_FROM_PIDM
  , THIRD_PARTY_FROM_BANNER_ID
  , THIRD_PARTY_FROM_ENTITY_CODE
  , THIRD_PARTY_FROM_NAME_SORT
  , RECORD_START_DATE
  FROM h_gi_credit_detail
  WHERE record_end_date IS NULL;

  
  CREATE INDEX C_GI_CREDIT_DETAIL_BANNER_ID ON C_GI_CREDIT_DETAIL (BANNER_ID) ;
  CREATE INDEX C_GI_CREDIT_DETAIL_CAMPAIGN ON C_GI_CREDIT_DETAIL (CAMPAIGN_CODE) ;
  CREATE INDEX C_GI_CREDIT_DETAIL_DESIGNATION ON C_GI_CREDIT_DETAIL (DESIGNATION_CODE) ;
  CREATE INDEX C_GI_CREDIT_DETAIL_FY ON C_GI_CREDIT_DETAIL (FISCAL_YEAR) ;
  CREATE INDEX C_GI_CREDIT_DETAIL_GIFT_NUM ON C_GI_CREDIT_DETAIL (GIFT_NUM) ;
  CREATE INDEX C_GI_CREDIT_DETAIL_PLEDGE_NUM ON C_GI_CREDIT_DETAIL (PLEDGE_NUM) ;
  CREATE INDEX C_GI_CREDIT_DETAIL_RECORD_CODE ON C_GI_CREDIT_DETAIL (RECORD_CODE) ;
  CREATE INDEX C_GI_CREDIT_DETAIL_START_DATE ON C_GI_CREDIT_DETAIL (RECORD_START_DATE) ;
  
   COMMENT ON COLUMN "PENTAHO"."C_GI_CREDIT_DETAIL"."PIDM" IS 'from CN_CONSTITUENT.PIDM';
   COMMENT ON COLUMN "PENTAHO"."C_GI_CREDIT_DETAIL"."BANNER_ID" IS 'from CN_CONSTITUENT.BANNER_ID';
   COMMENT ON COLUMN "PENTAHO"."C_GI_CREDIT_DETAIL"."ENTITY_CODE" IS 'from CN_CONSTITUENT.ENTITY_CODE';
   COMMENT ON COLUMN "PENTAHO"."C_GI_CREDIT_DETAIL"."NAME_SORT" IS 'from CN_CONSTITUENT.NAME_SORT';
   COMMENT ON COLUMN "PENTAHO"."C_GI_CREDIT_DETAIL"."RECORD_CODE" IS 'C = hard cash credit; P = hard pledge credit; CC = soft/memo cash credit; PC = soft/memo pledge credit';
   COMMENT ON COLUMN "PENTAHO"."C_GI_CREDIT_DETAIL"."RECORD_DESC" IS 'Description for RECORD_CODE';
   COMMENT ON COLUMN "PENTAHO"."C_GI_CREDIT_DETAIL"."GIFT_NUM" IS 'from AGRGDES_GIFT_NO';
   COMMENT ON COLUMN "PENTAHO"."C_GI_CREDIT_DETAIL"."PLEDGE_NUM" IS 'from AGRPDES_PLEDGE_NO';
   COMMENT ON COLUMN "PENTAHO"."C_GI_CREDIT_DETAIL"."FISCAL_YEAR" IS 'from AGBGIFT_FISC_CODE or from AGBPLDG_FISC_CODE';
   COMMENT ON COLUMN "PENTAHO"."C_GI_CREDIT_DETAIL"."CAMPAIGN_CODE" IS 'from AGRGDES_CAMPAIGN or from AGRPDES_CAMPAIGN';
   COMMENT ON COLUMN "PENTAHO"."C_GI_CREDIT_DETAIL"."CAMPAIGN_DESC" IS 'Description for CAMPAIGN_CODE';
   COMMENT ON COLUMN "PENTAHO"."C_GI_CREDIT_DETAIL"."DESIGNATION_CODE" IS 'from AGRGDES_DESG or from AGRPDES_DESG';
   COMMENT ON COLUMN "PENTAHO"."C_GI_CREDIT_DETAIL"."DESIGNATION_DESC" IS 'Description for DESIGNATION_CODE';
   COMMENT ON COLUMN "PENTAHO"."C_GI_CREDIT_DETAIL"."TRANSACTION_TYPE" IS 'from AGBGIFT_GIFT_CODE or from AGBPLDG_PLDG_CODE';
   COMMENT ON COLUMN "PENTAHO"."C_GI_CREDIT_DETAIL"."TRANSACTION_TYPE_DESC" IS 'Description for TRANSACTION_TYPE';
   COMMENT ON COLUMN "PENTAHO"."C_GI_CREDIT_DETAIL"."TRANSACTION_CATEGORY" IS 'Gift category (Outright Gift, MG Payment, Pledge Payment, Countable Pledge, Non-Countable Pledge, Memo Outright Gift, Memo MG Payment, Memo Pledge Payment, Memo Countable Pledge, Memo Non-Countable Pledge, Third Party Payment)';
   COMMENT ON COLUMN "PENTAHO"."C_GI_CREDIT_DETAIL"."TRANSACTION_AMOUNT" IS 'Total amount of this transaction regardless of category';
   COMMENT ON COLUMN "PENTAHO"."C_GI_CREDIT_DETAIL"."TRANSACTION_PLEDGE_BALANCE" IS 'Total pledge balanace of this transaction regardless of category';
   COMMENT ON COLUMN "PENTAHO"."C_GI_CREDIT_DETAIL"."TRANSACTION_PLEDGE_TOTAL" IS 'Total pledge amount of this transaction regardless of category';
   COMMENT ON COLUMN "PENTAHO"."C_GI_CREDIT_DETAIL"."TRANSACTION_COMMENT" IS 'from AGBGIFT_COMMENT or from AGBPLDG_COMMENT';
   COMMENT ON COLUMN "PENTAHO"."C_GI_CREDIT_DETAIL"."PLEDGE_STATUS" IS 'from AGBPLDG_PSTA_CODE';
   COMMENT ON COLUMN "PENTAHO"."C_GI_CREDIT_DETAIL"."PLEDGE_STATUS_DESC" IS 'Description for PLEDGE_STATUS';
   COMMENT ON COLUMN "PENTAHO"."C_GI_CREDIT_DETAIL"."ENTRY_DATE" IS 'from AGBGIFT_ENTRY_DATE or from AGBPLDG_ENTRY_DATE';
   COMMENT ON COLUMN "PENTAHO"."C_GI_CREDIT_DETAIL"."ACTIVITY_DATE" IS 'from AGBGIFT_ACTIVITY_DATE or from AGBPLDG_ACTIVITY_DATE';
   COMMENT ON COLUMN "PENTAHO"."C_GI_CREDIT_DETAIL"."OUTRIGHT_GIFT" IS 'Amount directly given by a donor where no pledge was recorded and <> MG and <> 3PP ';
   COMMENT ON COLUMN "PENTAHO"."C_GI_CREDIT_DETAIL"."MG_PMT" IS 'Amount given by organization where gift was a match to another donors original gift or pledge pmt (gift_type = MG)';
   COMMENT ON COLUMN "PENTAHO"."C_GI_CREDIT_DETAIL"."PLEDGE_PMT" IS 'Amount paid on a pledge not by a 3rd party';
   COMMENT ON COLUMN "PENTAHO"."C_GI_CREDIT_DETAIL"."COUNTABLE_PLEDGE" IS 'Amount promised by a donor that is counted in advancement reported totals (exclude uncountable testamentary pledges)';
   COMMENT ON COLUMN "PENTAHO"."C_GI_CREDIT_DETAIL"."PLEDGE_PAID_TOTAL" IS 'Total amount paid to date on pledge';
   COMMENT ON COLUMN "PENTAHO"."C_GI_CREDIT_DETAIL"."PLEDGE_BALANCE" IS 'Current amount remaining on pledge (COUNTABLE_PLEDGE-PLEDGE_PAID_TOTAL)';
   COMMENT ON COLUMN "PENTAHO"."C_GI_CREDIT_DETAIL"."NOT_COUNTABLE_PLEDGE" IS 'Amount promised by a donor that is not counted in advancement reported totals (ie, uncountable testamentary pledges)';
   COMMENT ON COLUMN "PENTAHO"."C_GI_CREDIT_DETAIL"."MEMO_OUTRIGHT_GIFT" IS 'Amount memod to a donor where no pledge was recorded and <> MG memo and <> 3PP';
   COMMENT ON COLUMN "PENTAHO"."C_GI_CREDIT_DETAIL"."MEMO_MG_PMT" IS 'Amount memod to a donor where the cash was a match from a company';
   COMMENT ON COLUMN "PENTAHO"."C_GI_CREDIT_DETAIL"."MEMO_PLEDGE_PMT" IS 'Amount memod to a donor where a pledge was recorded. <> MG memo';
   COMMENT ON COLUMN "PENTAHO"."C_GI_CREDIT_DETAIL"."MEMO_COUNT_PLEDGE" IS 'Amount memod to a donor for a pledge that is counted in advancement reported totals (exclude uncountable testamentary pledges)';
   COMMENT ON COLUMN "PENTAHO"."C_GI_CREDIT_DETAIL"."MEMO_PLEDGE_PAID_TOTAL" IS 'Amount memod to donor paid to date on pledge';
   COMMENT ON COLUMN "PENTAHO"."C_GI_CREDIT_DETAIL"."MEMO_PLEDGE_BALANCE" IS 'Current memod amount remaining on pledge (MEMO_COUNT_PLEDGE-MEMO_PLEDGE_PAID_TOTAL)';
   COMMENT ON COLUMN "PENTAHO"."C_GI_CREDIT_DETAIL"."MEMO_NOT_COUNT_PLEDGE" IS 'Amount memod to a donor for a pledge that is not counted in advancement reported totals (ie, uncountable testamentary pledges)';
   COMMENT ON COLUMN "PENTAHO"."C_GI_CREDIT_DETAIL"."THIRD_PARTY_PMT" IS 'Amount paid on a pledge by a 3rd party';
   COMMENT ON COLUMN "PENTAHO"."C_GI_CREDIT_DETAIL"."TESTAMENTARY_COMMIT_CREDIT" IS 'See logic for Tower Society Data Sheet survey / PG01';
   COMMENT ON COLUMN "PENTAHO"."C_GI_CREDIT_DETAIL"."CASH_CREDIT_PERSON" IS 'OUTRIGHT_GIFT + MG_PMT + PLEDGE_PMT + MEMO_OUTRIGHT_GIFT + MEMO_PLEDGE_PMT + THIRD_PARTY_PMT';
   COMMENT ON COLUMN "PENTAHO"."C_GI_CREDIT_DETAIL"."CASH_CREDIT_TRANSACTION" IS 'OUTRIGHT_GIFT + MG_PMT + PLEDGE_PMT';
   COMMENT ON COLUMN "PENTAHO"."C_GI_CREDIT_DETAIL"."COMMITMENT_CREDIT_PERSON" IS 'OUTRIGHT_GIFT + MG_PMT + COUNTABLE_PLEDGE + NOT_COUNTABLE_PLEDGE + MEMO_OUTRIGHT_GIFT + MEMO_MG_PMT + MEMO_COUNT_PLEDGE + MEMO_NOT_COUNT_PLEDGE';
   COMMENT ON COLUMN "PENTAHO"."C_GI_CREDIT_DETAIL"."COMMITMENT_CREDIT_TRANSACTION" IS 'OUTRIGHT_GIFT + MG_PMT + COUNTABLE_PLEDGE + MEMO_OUTRIGHT_GIFT + MEMO_MG_PMT + MEMO_COUNT_PLEDGE';
   COMMENT ON COLUMN "PENTAHO"."C_GI_CREDIT_DETAIL"."CLASS_CODE_1" IS 'from AGBGIFT_GCLS_CODE or from AGBPLDG_PCLS_CODE';
   COMMENT ON COLUMN "PENTAHO"."C_GI_CREDIT_DETAIL"."CLASS_CODE_2" IS 'from AGBGIFT_GCLS_CODE_2 or from AGBPLDG_PCLS_CODE_2';
   COMMENT ON COLUMN "PENTAHO"."C_GI_CREDIT_DETAIL"."CLASS_CODE_3" IS 'from AGBGIFT_GCLS_CODE_3 or from AGBPLDG_PCLS_CODE_3';
   COMMENT ON COLUMN "PENTAHO"."C_GI_CREDIT_DETAIL"."CLASS_DESC_1" IS 'Description for CLASS_CODE_1';
   COMMENT ON COLUMN "PENTAHO"."C_GI_CREDIT_DETAIL"."CLASS_DESC_2" IS 'Description for CLASS_CODE_2';
   COMMENT ON COLUMN "PENTAHO"."C_GI_CREDIT_DETAIL"."CLASS_DESC_3" IS 'Description for CLASS_CODE_3';
   COMMENT ON COLUMN "PENTAHO"."C_GI_CREDIT_DETAIL"."COMPCAMP_CODE" IS 'A code indicating which Comprehensive Campaign this gift is attached to.';
   COMMENT ON COLUMN "PENTAHO"."C_GI_CREDIT_DETAIL"."COMPCAMP_DESC" IS 'Description of COMPCAMP_CODE';
   COMMENT ON COLUMN "PENTAHO"."C_GI_CREDIT_DETAIL"."TRANSACTION_DATE" IS 'from AGBGIFT_GIFT_DATE or from AGBPLDG_PLEDGE_DATE';
   COMMENT ON COLUMN "PENTAHO"."C_GI_CREDIT_DETAIL"."VEHICLE_CODE" IS 'from AGBGIFT_PGVE_CODE or from AGBPLDG_PGVE_CODE';
   COMMENT ON COLUMN "PENTAHO"."C_GI_CREDIT_DETAIL"."VEHICLE_DESC" IS 'Description for VEHICLE_CODE';
   COMMENT ON COLUMN "PENTAHO"."C_GI_CREDIT_DETAIL"."MG_TOTAL_COUNT" IS 'Total number of matched gifts this donor gift is attached to (both PAID and UNPAID)';
   COMMENT ON COLUMN "PENTAHO"."C_GI_CREDIT_DETAIL"."MG_TOTAL_AMOUNT" IS 'Total dollar amount anticipated from matched gifts (both PAID and UNPAID)';
   COMMENT ON COLUMN "PENTAHO"."C_GI_CREDIT_DETAIL"."MG_UNPAID_COUNT" IS 'Total number of matched gifts this donor gift is attached to (UNPAID only)';
   COMMENT ON COLUMN "PENTAHO"."C_GI_CREDIT_DETAIL"."MG_UNPAID_AMOUNT" IS 'Total dollar amount anticipated from matched gifts (UNPAID only)';
   COMMENT ON COLUMN "PENTAHO"."C_GI_CREDIT_DETAIL"."MG_PAID_COUNT" IS 'Total number of matched gifts this donor gift is attached to (PAID only)';
   COMMENT ON COLUMN "PENTAHO"."C_GI_CREDIT_DETAIL"."MG_PAID_AMOUNT" IS 'Total dollar amount received from matched gifts (PAID only)';
   COMMENT ON COLUMN "PENTAHO"."C_GI_CREDIT_DETAIL"."MATCHED_GIFT_NUM" IS 'Original gift number from donor that MG paid on. MULTI indicates more than one gift is included in match';
   COMMENT ON COLUMN "PENTAHO"."C_GI_CREDIT_DETAIL"."MATCHING_GIFT_NUM" IS 'Gift number of the MG companys gift. MULTI indicates gift was matched by more than one company';
   COMMENT ON COLUMN "PENTAHO"."C_GI_CREDIT_DETAIL"."MEMO_FROM_PIDM" IS 'PIDM of memod or memoing entity; NULL if multiple entries';
   COMMENT ON COLUMN "PENTAHO"."C_GI_CREDIT_DETAIL"."MEMO_FROM_BANNER_ID" IS 'BANNER_ID of memod or memoing entity; NULL if multiple entries';
   COMMENT ON COLUMN "PENTAHO"."C_GI_CREDIT_DETAIL"."MEMO_FROM_ENTITY_CODE" IS 'ENTITY_CODE of memod or memoing entity; NULL if multiple entries';
   COMMENT ON COLUMN "PENTAHO"."C_GI_CREDIT_DETAIL"."MEMO_FROM_NAME_SORT" IS 'NAME_SORT of memod or memoing entity; MULTIPLE if multiple entries';
   COMMENT ON COLUMN "PENTAHO"."C_GI_CREDIT_DETAIL"."NOT_COUNTABLE_PLEDGE_BALANCE" IS 'Current amount remaining on pledge (NOT_COUNTABLE_PLEDGE-PLEDGE_PAID_TOTAL)';
   COMMENT ON COLUMN "PENTAHO"."C_GI_CREDIT_DETAIL"."MEMO_NOT_COUNT_PLEDGE_BALANCE" IS 'Current memod amount remaining on pledge (MEMO_NOT_COUNT_PLEDGE-MEMO_PLEDGE_PAID_TOTAL)';
   COMMENT ON COLUMN "PENTAHO"."C_GI_CREDIT_DETAIL"."MEMO_THIRD_PARTY_PMT" IS 'Amount of third party payment credited to this donor';
   COMMENT ON COLUMN "PENTAHO"."C_GI_CREDIT_DETAIL"."THIRD_PARTY_FROM_PIDM" IS 'PIDM of payer of THIRD_PARTY_PMT';
   COMMENT ON COLUMN "PENTAHO"."C_GI_CREDIT_DETAIL"."THIRD_PARTY_FROM_BANNER_ID" IS 'BANNER_ID of payer of THIRD_PARTY_PMT';
   COMMENT ON COLUMN "PENTAHO"."C_GI_CREDIT_DETAIL"."THIRD_PARTY_FROM_ENTITY_CODE" IS 'ENTITY_CODE of payer of THIRD_PARTY_PMT';
   COMMENT ON COLUMN "PENTAHO"."C_GI_CREDIT_DETAIL"."THIRD_PARTY_FROM_NAME_SORT" IS 'NAME_SORT of payer of THIRD_PARTY_PMT';
   COMMENT ON MATERIALIZED VIEW "PENTAHO"."C_GI_CREDIT_DETAIL"  IS 'snapshot table for snapshot PENTAHO.C_GI_CREDIT_DETAIL';

