/*
BEGIN
dbms_snapshot.REFRESH('c_rm_ratings');
END;
*/

CREATE MATERIALIZED VIEW LOG ON h_rm_ratings;

CREATE MATERIALIZED VIEW c_rm_ratings refresh fast ON demand
AS
  SELECT PIDM
  , BANNER_ID
  , ENTITY_CODE
  , NAME_SORT
  , PRIMARY_IND
  , RATE_TYPE_CODE
  , RATE_TYPE_DESC
  , RATING_CODE
  , RATING_DESC
  , SCREENING_CODE
  , SCREENING_DESC
  , RATER_PIDM
  , RATER_BANNER_ID
  , RATER_NAME
  , RATER_USER_ID
  , RATING_PIDM
  , RATING_BANNER_ID
  , RATING_NAME
  , RATE_EFF_FROM_DATE
  , RATE_EFF_TO_DATE
  , ACTIVITY_DATE
  , BANNER_USER
  , BANNER_USERID
  , ROW_KEY
  , RECORD_START_DATE
  FROM h_rm_ratings
  WHERE record_end_date IS NULL;

  CREATE INDEX C_RM_RATINGS_PIDM ON C_RM_RATINGS (PIDM) ;
  CREATE INDEX C_RM_RATINGS_BANNER_ID ON C_RM_RATINGS (BANNER_ID) ;
  CREATE INDEX C_RM_RATINGS_NAME_SORT ON C_RM_RATINGS (NAME_SORT) ;
  CREATE INDEX C_RM_RATINGS_ENTITY_CODE ON C_RM_RATINGS (ENTITY_CODE) ;
  CREATE INDEX C_RM_RATINGS_RTGT ON C_RM_RATINGS (RATE_TYPE_CODE) ;
  CREATE INDEX C_RM_RATINGS_RATE ON C_RM_RATINGS (RATING_CODE) ;
  CREATE INDEX C_RM_RATINGS_RSCR ON C_RM_RATINGS (SCREENING_CODE) ;
  CREATE INDEX C_RM_RATINGS_RATER ON C_RM_RATINGS (RATER_PIDM) ;
  CREATE INDEX C_RM_RATINGS_USER ON C_RM_RATINGS (RATER_USER_ID) ;
  CREATE INDEX C_RM_RATINGS_RATING_PIDM ON C_RM_RATINGS (RATING_PIDM) ;
