--BEGIN
--  dbms_snapshot.REFRESH('C_RM_CONTACTS');
--END;

 CREATE MATERIALIZED VIEW LOG ON H_RM_CONTACTS;

CREATE MATERIALIZED VIEW C_RM_CONTACTS refresh FAST ON demand
AS
  SELECT PIDM
  , BANNER_ID
  , NAME_SORT
  , ENTITY_CODE
  , REFERENCE_NUM
  , IDEN_CODE
  , CONTACT_TYPE_CODE
  , CONTACT_TYPE_DESC
  , PROJECT_CODE_1
  , PROJECT_DESC_1
  , PROJECT_CODE_2
  , PROJECT_DESC_2
  , PROJECT_CODE_3
  , PROJECT_DESC_3
  , PROJECT_CODE_4
  , PROJECT_DESC_4
  , CONFID_IND
  , IDEN_CODE_ASSIGNED
  , CONTACT_DESC
  , CALL_REPORT
  , CONTACT_DATE
  , CREATE_TICKLER_IND
  , TICKLER_MESSAGE
  , TICKLER_DATE
  , TICKLER_STATUS
  , ASK_AMOUNT_1
  , ASK_AMOUNT_2
  , ASK_AMOUNT_3
  , ASK_AMOUNT_4
  , MOVE_CODE
  , MOVE_DESC
  , MOVE_SEQNO
  , PROPOSAL_CODE
  , PROPOSAL_DESC
  , PROPOSAL_SEQNO
  , CREATE_DATE
  , ACTIVITY_DATE
  , BANNER_USER_ID
  , DATA_ORIGIN
  , RECORD_START_DATE
  FROM h_rm_contacts
  WHERE record_end_date IS NULL;

  CREATE INDEX C_RM_CONTACTS_PIDM ON C_RM_CONTACTS (PIDM) ;
  CREATE INDEX C_RM_CONTACTS_BANNER_ID ON C_RM_CONTACTS (BANNER_ID) ;
  CREATE INDEX C_RM_CONTACTS_NAME ON C_RM_CONTACTS (NAME_SORT) ;
  CREATE INDEX C_RM_CONTACTS_REFNO ON C_RM_CONTACTS (REFERENCE_NUM) ;
  CREATE INDEX C_RM_CONTACTS_ENTITY ON C_RM_CONTACTS (ENTITY_CODE) ;
  CREATE INDEX C_RM_CONTACTS_CODE1 ON C_RM_CONTACTS (PROJECT_CODE_1) ;
  CREATE INDEX C_RM_CONTACTS_CODE2 ON C_RM_CONTACTS (PROJECT_CODE_2) ;
  CREATE INDEX C_RM_CONTACTS_CODE3 ON C_RM_CONTACTS (PROJECT_CODE_3) ;
  CREATE INDEX C_RM_CONTACTS_CODE4 ON C_RM_CONTACTS (PROJECT_CODE_4) ;
