/*
BEGIN
dbms_snapshot.REFRESH('c_rm_staff_assignments');
END;
*/

 CREATE MATERIALIZED VIEW LOG ON h_rm_staff_assignments;

CREATE MATERIALIZED VIEW c_rm_staff_assignments refresh fast ON demand
AS
  SELECT PIDM
  , BANNER_ID
  , NAME_SORT
  , ENTITY_CODE
  , PRIMARY_IND
  , ACTIVE_IND
  , STAFF_TYPE_CODE
  , STAFF_TYPE_DESC
  , STAFF_IDEN_CODE
  , STAFF_USER_ID
  , STAFF_PIDM
  , STAFF_BANNER_ID
  , STAFF_NAME
  , STAFF_EMAIL
  , STAFF_CURRENT_TEAM
  , SOLICITOR_IND
  , EFF_FROM_DATE
  , EFF_TO_DATE
  , ACTIVITY_DATE
  , BANNER_STATUS_IND
  , BANNER_USER
  , BANNER_USERID
  , RECORD_START_DATE
  FROM h_rm_staff_assignments
  WHERE record_end_date IS NULL;
  
  CREATE INDEX C_RM_STAFF_ASSIGNMENTS_PIDM ON C_RM_STAFF_ASSIGNMENTS (PIDM) ;
  CREATE INDEX C_RM_STAFF_ASSIGNMENTS_ID ON C_RM_STAFF_ASSIGNMENTS (BANNER_ID) ;
  CREATE INDEX C_RM_STAFF_ASSIGNMENTS_NAME ON C_RM_STAFF_ASSIGNMENTS (NAME_SORT) ;
  CREATE INDEX C_RM_STAFF_ASSIGNMENTS_ENTITY ON C_RM_STAFF_ASSIGNMENTS (ENTITY_CODE) ;
  CREATE INDEX C_RM_STAFF_ASSIGNMENTS_PRIMARY ON C_RM_STAFF_ASSIGNMENTS (PRIMARY_IND) ;
  CREATE INDEX C_RM_STAFF_ASSIGNMENTS_ACTIVE ON C_RM_STAFF_ASSIGNMENTS (ACTIVE_IND) ;
  CREATE INDEX C_RM_STAFF_ASSIGNMENTS_TYPE ON C_RM_STAFF_ASSIGNMENTS (STAFF_TYPE_CODE) ;
  CREATE INDEX C_RM_STAFF_ASSIGNMENTS_STAFFID ON C_RM_STAFF_ASSIGNMENTS (STAFF_IDEN_CODE) ;
  CREATE INDEX C_RM_STAFF_ASSIGNMENTS_STFPIDM ON C_RM_STAFF_ASSIGNMENTS (STAFF_PIDM) ;
  CREATE INDEX C_RM_STAFF_ASSIGNMENTS_STFLIN ON C_RM_STAFF_ASSIGNMENTS (STAFF_BANNER_ID) ;

  

