--BEGIN
--  dbms_snapshot.REFRESH('C_RM_PROJECTS');
--END;

CREATE MATERIALIZED VIEW LOG ON H_RM_PROJECTS;

CREATE MATERIALIZED VIEW C_RM_PROJECTS refresh FAST ON demand
AS
  SELECT PIDM
  ,BANNER_ID
  ,NAME_SORT
  ,ENTITY_CODE
  ,PROJECT_CODE
  ,PROJECT_DESC
  ,CAMPAIGN_GROUP
  ,PROJECT_GROUP
  ,PROJECT_AVAILABLE_IND
  ,GIVING_VEHICLE_CODE
  ,GIVING_VEHICLE_DESC
  ,TARGET_ASK_AMOUNT
  ,TARGET_ASK_DATE
  ,PROSPECT_STATUS_CODE
  ,PROSPECT_STATUS_DESC
  ,PROSPECT_STATUS_DATE
  ,PROJECT_TEXT
  ,PROJ_EFF_FROM_DATE
  ,PROJ_EFF_TO_DATE
  ,EXPECTED_CLOSE_AMOUNT
  ,LAST_CONTACT_IDEN_CODE
  ,LAST_CONTACT_IDEN_CODE_ASSGN
  ,LAST_CONTACT_TYPE_CODE
  ,LAST_CONTACT_TYPE_DESC
  ,LAST_CONTACT_DATE
  ,LAST_CONTACT_DESC
  ,LAST_CONTACT_CALL_REPORT
  ,LAST_CONTACT_ASK_AMOUNT
  ,LAST_CONTACT_MOVE_CODE
  ,LAST_CONTACT_MOVE_DESC
  ,LAST_CONTACT_REF_NUM
  ,LAST_ASK_IDEN_CODE
  ,LAST_ASK_IDEN_CODE_ASSGN
  ,LAST_ASK_TYPE_CODE
  ,LAST_ASK_TYPE_DESC
  ,LAST_ASK_DATE
  ,LAST_ASK_DESC
  ,LAST_ASK_CALL_REPORT
  ,LAST_ASK_ASK_AMOUNT
  ,LAST_ASK_MOVE_CODE
  ,LAST_ASK_MOVE_DESC
  ,LAST_ASK_REF_NUM
  ,ACTIVITY_DATE
  ,BANNER_USER
  ,BANNER_USERID
  ,DATA_ORIGIN
  ,RECORD_START_DATE
  FROM h_rm_projects
  WHERE record_end_date IS NULL ;
  
  CREATE INDEX C_RM_PROJECTS_PIDM ON C_RM_PROJECTS (PIDM) ;
  CREATE INDEX C_RM_PROJECTS_BANNER_ID ON C_RM_PROJECTS (BANNER_ID) ;
  CREATE INDEX C_RM_PROJECTS_NAME ON C_RM_PROJECTS (NAME_SORT) ;
  CREATE INDEX C_RM_PROJECTS_ENTITY ON C_RM_PROJECTS (ENTITY_CODE) ;
  CREATE INDEX C_RM_PROJECTS_CODE ON C_RM_PROJECTS (PROJECT_CODE) ;
  CREATE INDEX C_RM_PROJECTS_CAMP_GRP ON C_RM_PROJECTS (CAMPAIGN_GROUP) ;
  CREATE INDEX C_RM_PROJECTS_PROJ_GRP ON C_RM_PROJECTS (PROJECT_GROUP) ;
  CREATE INDEX C_RM_PROJECTS_AVAIL ON C_RM_PROJECTS (PROJECT_AVAILABLE_IND) ;
