/*
BEGIN
dbms_snapshot.REFRESH('c_rm_ratings_active_by_id');
END;
*/

CREATE MATERIALIZED VIEW LOG ON h_rm_ratings_active_by_id;

CREATE MATERIALIZED VIEW c_rm_ratings_active_by_id refresh fast ON demand
AS
  SELECT PIDM
  , BANNER_ID
  , NAME_SORT
  , ENTITY_CODE
  , C_TYPE_DESC
  , C_RATING_CODE
  , C_RATING_DESC
  , C_SCREENING_CODE
  , C_SCREENING_DESC
  , C_RATER_PIDM
  , C_RATER_BANNER_ID
  , C_RATER_NAME
  , C_RATER_USER_ID
  , C_RATING_PIDM
  , C_RATING_BANNER_ID
  , C_RATING_NAME
  , C_EFF_FROM_DATE
  , C_EFF_TO_DATE
  , D_TYPE_DESC
  , D_RATING_CODE
  , D_RATING_DESC
  , D_SCREENING_CODE
  , D_SCREENING_DESC
  , D_RATER_PIDM
  , D_RATER_BANNER_ID
  , D_RATER_NAME
  , D_RATER_USER_ID
  , D_RATING_PIDM
  , D_RATING_BANNER_ID
  , D_RATING_NAME
  , D_EFF_FROM_DATE
  , D_EFF_TO_DATE
  , F_TYPE_DESC
  , F_RATING_CODE
  , F_RATING_DESC
  , F_SCREENING_CODE
  , F_SCREENING_DESC
  , F_RATER_PIDM
  , F_RATER_BANNER_ID
  , F_RATER_NAME
  , F_RATER_USER_ID
  , F_RATING_PIDM
  , F_RATING_BANNER_ID
  , F_RATING_NAME
  , F_EFF_FROM_DATE
  , F_EFF_TO_DATE
  , G_TYPE_DESC
  , G_RATING_CODE
  , G_RATING_DESC
  , G_SCREENING_CODE
  , G_SCREENING_DESC
  , G_RATER_PIDM
  , G_RATER_BANNER_ID
  , G_RATER_NAME
  , G_RATER_USER_ID
  , G_RATING_PIDM
  , G_RATING_BANNER_ID
  , G_RATING_NAME
  , G_EFF_FROM_DATE
  , G_EFF_TO_DATE
  , H_TYPE_DESC
  , H_RATING_CODE
  , H_RATING_DESC
  , H_SCREENING_CODE
  , H_SCREENING_DESC
  , H_RATER_PIDM
  , H_RATER_BANNER_ID
  , H_RATER_NAME
  , H_RATER_USER_ID
  , H_RATING_PIDM
  , H_RATING_BANNER_ID
  , H_RATING_NAME
  , H_EFF_FROM_DATE
  , H_EFF_TO_DATE
  , J_TYPE_DESC
  , J_RATING_CODE
  , J_RATING_DESC
  , J_SCREENING_CODE
  , J_SCREENING_DESC
  , J_RATER_PIDM
  , J_RATER_BANNER_ID
  , J_RATER_NAME
  , J_RATER_USER_ID
  , J_RATING_PIDM
  , J_RATING_BANNER_ID
  , J_RATING_NAME
  , J_EFF_FROM_DATE
  , J_EFF_TO_DATE
  , K_TYPE_DESC
  , K_RATING_CODE
  , K_RATING_DESC
  , K_SCREENING_CODE
  , K_SCREENING_DESC
  , K_RATER_PIDM
  , K_RATER_BANNER_ID
  , K_RATER_NAME
  , K_RATER_USER_ID
  , K_RATING_PIDM
  , K_RATING_BANNER_ID
  , K_RATING_NAME
  , K_EFF_FROM_DATE
  , K_EFF_TO_DATE
  , M_TYPE_DESC
  , M_RATING_CODE
  , M_RATING_DESC
  , M_SCREENING_CODE
  , M_SCREENING_DESC
  , M_RATER_PIDM
  , M_RATER_BANNER_ID
  , M_RATER_NAME
  , M_RATER_USER_ID
  , M_RATING_PIDM
  , M_RATING_BANNER_ID
  , M_RATING_NAME
  , M_EFF_FROM_DATE
  , M_EFF_TO_DATE
  , N_TYPE_DESC
  , N_RATING_CODE
  , N_RATING_DESC
  , N_SCREENING_CODE
  , N_SCREENING_DESC
  , N_RATER_PIDM
  , N_RATER_BANNER_ID
  , N_RATER_NAME
  , N_RATER_USER_ID
  , N_RATING_PIDM
  , N_RATING_BANNER_ID
  , N_RATING_NAME
  , N_EFF_FROM_DATE
  , N_EFF_TO_DATE
  , O_TYPE_DESC
  , O_RATING_CODE
  , O_RATING_DESC
  , O_SCREENING_CODE
  , O_SCREENING_DESC
  , O_RATER_PIDM
  , O_RATER_BANNER_ID
  , O_RATER_NAME
  , O_RATER_USER_ID
  , O_RATING_PIDM
  , O_RATING_BANNER_ID
  , O_RATING_NAME
  , O_EFF_FROM_DATE
  , O_EFF_TO_DATE
  , P_TYPE_DESC
  , P_RATING_CODE
  , P_RATING_DESC
  , P_SCREENING_CODE
  , P_SCREENING_DESC
  , P_RATER_PIDM
  , P_RATER_BANNER_ID
  , P_RATER_NAME
  , P_RATER_USER_ID
  , P_RATING_PIDM
  , P_RATING_BANNER_ID
  , P_RATING_NAME
  , P_EFF_FROM_DATE
  , P_EFF_TO_DATE
  , Q_TYPE_DESC
  , Q_RATING_CODE
  , Q_RATING_DESC
  , Q_SCREENING_CODE
  , Q_SCREENING_DESC
  , Q_RATER_PIDM
  , Q_RATER_BANNER_ID
  , Q_RATER_NAME
  , Q_RATER_USER_ID
  , Q_RATING_PIDM
  , Q_RATING_BANNER_ID
  , Q_RATING_NAME
  , Q_EFF_FROM_DATE
  , Q_EFF_TO_DATE
  , R_TYPE_DESC
  , R_RATING_CODE
  , R_RATING_DESC
  , R_SCREENING_CODE
  , R_SCREENING_DESC
  , R_RATER_PIDM
  , R_RATER_BANNER_ID
  , R_RATER_NAME
  , R_RATER_USER_ID
  , R_RATING_PIDM
  , R_RATING_BANNER_ID
  , R_RATING_NAME
  , R_EFF_FROM_DATE
  , R_EFF_TO_DATE
  , S_TYPE_DESC
  , S_RATING_CODE
  , S_RATING_DESC
  , S_SCREENING_CODE
  , S_SCREENING_DESC
  , S_RATER_PIDM
  , S_RATER_BANNER_ID
  , S_RATER_NAME
  , S_RATER_USER_ID
  , S_RATING_PIDM
  , S_RATING_BANNER_ID
  , S_RATING_NAME
  , S_EFF_FROM_DATE
  , S_EFF_TO_DATE
  , T_TYPE_DESC
  , T_RATING_CODE
  , T_RATING_DESC
  , T_SCREENING_CODE
  , T_SCREENING_DESC
  , T_RATER_PIDM
  , T_RATER_BANNER_ID
  , T_RATER_NAME
  , T_RATER_USER_ID
  , T_RATING_PIDM
  , T_RATING_BANNER_ID
  , T_RATING_NAME
  , T_EFF_FROM_DATE
  , T_EFF_TO_DATE
  , U_TYPE_DESC
  , U_RATING_CODE
  , U_RATING_DESC
  , U_SCREENING_CODE
  , U_SCREENING_DESC
  , U_RATER_PIDM
  , U_RATER_BANNER_ID
  , U_RATER_NAME
  , U_RATER_USER_ID
  , U_RATING_PIDM
  , U_RATING_BANNER_ID
  , U_RATING_NAME
  , U_EFF_FROM_DATE
  , U_EFF_TO_DATE
  , V_TYPE_DESC
  , V_RATING_CODE
  , V_RATING_DESC
  , V_SCREENING_CODE
  , V_SCREENING_DESC
  , V_RATER_PIDM
  , V_RATER_BANNER_ID
  , V_RATER_NAME
  , V_RATER_USER_ID
  , V_RATING_PIDM
  , V_RATING_BANNER_ID
  , V_RATING_NAME
  , V_EFF_FROM_DATE
  , V_EFF_TO_DATE
  , W_TYPE_DESC
  , W_RATING_CODE
  , W_RATING_DESC
  , W_SCREENING_CODE
  , W_SCREENING_DESC
  , W_RATER_PIDM
  , W_RATER_BANNER_ID
  , W_RATER_NAME
  , W_RATER_USER_ID
  , W_RATING_PIDM
  , W_RATING_BANNER_ID
  , W_RATING_NAME
  , W_EFF_FROM_DATE
  , W_EFF_TO_DATE
  , X_TYPE_DESC
  , X_RATING_CODE
  , X_RATING_DESC
  , X_SCREENING_CODE
  , X_SCREENING_DESC
  , X_RATER_PIDM
  , X_RATER_BANNER_ID
  , X_RATER_NAME
  , X_RATER_USER_ID
  , X_RATING_PIDM
  , X_RATING_BANNER_ID
  , X_RATING_NAME
  , X_EFF_FROM_DATE
  , X_EFF_TO_DATE
  , Y_TYPE_DESC
  , Y_RATING_CODE
  , Y_RATING_DESC
  , Y_SCREENING_CODE
  , Y_SCREENING_DESC
  , Y_RATER_PIDM
  , Y_RATER_BANNER_ID
  , Y_RATER_NAME
  , Y_RATER_USER_ID
  , Y_RATING_PIDM
  , Y_RATING_BANNER_ID
  , Y_RATING_NAME
  , Y_EFF_FROM_DATE
  , Y_EFF_TO_DATE
  , Z_TYPE_DESC
  , Z_RATING_CODE
  , Z_RATING_DESC
  , Z_SCREENING_CODE
  , Z_SCREENING_DESC
  , Z_RATER_PIDM
  , Z_RATER_BANNER_ID
  , Z_RATER_NAME
  , Z_RATER_USER_ID
  , Z_RATING_PIDM
  , Z_RATING_BANNER_ID
  , Z_RATING_NAME
  , Z_EFF_FROM_DATE
  , Z_EFF_TO_DATE
  , RECORD_START_DATE
  FROM h_rm_ratings_active_by_id
  WHERE record_end_date IS NULL;

  CREATE INDEX C_RM_RATINGS_BYID_PIDM ON C_RM_RATINGS_ACTIVE_BY_ID (PIDM) ;
  CREATE INDEX C_RM_RATINGS_BYID_BANNER_ID ON C_RM_RATINGS_ACTIVE_BY_ID (BANNER_ID) ;
  CREATE INDEX C_RM_RATINGS_BYID_NAME_SORT ON C_RM_RATINGS_ACTIVE_BY_ID (NAME_SORT) ;
  CREATE INDEX C_RM_RATINGS_BYID_ENTITY_CODE ON C_RM_RATINGS_ACTIVE_BY_ID (ENTITY_CODE) ;
  CREATE INDEX C_RM_RATINGS_BYID_C_RATE ON C_RM_RATINGS_ACTIVE_BY_ID (C_RATING_CODE) ;
  CREATE INDEX C_RM_RATINGS_BYID_D_RATE ON C_RM_RATINGS_ACTIVE_BY_ID (D_RATING_CODE) ;
  CREATE INDEX C_RM_RATINGS_BYID_F_RATE ON C_RM_RATINGS_ACTIVE_BY_ID (F_RATING_CODE) ;
  CREATE INDEX C_RM_RATINGS_BYID_G_RATE ON C_RM_RATINGS_ACTIVE_BY_ID (G_RATING_CODE) ;
  CREATE INDEX C_RM_RATINGS_BYID_H_RATE ON C_RM_RATINGS_ACTIVE_BY_ID (H_RATING_CODE) ;
  CREATE INDEX C_RM_RATINGS_BYID_J_RATE ON C_RM_RATINGS_ACTIVE_BY_ID (J_RATING_CODE) ;
  CREATE INDEX C_RM_RATINGS_BYID_K_RATE ON C_RM_RATINGS_ACTIVE_BY_ID (K_RATING_CODE) ;
  CREATE INDEX C_RM_RATINGS_BYID_M_RATE ON C_RM_RATINGS_ACTIVE_BY_ID (M_RATING_CODE) ;
  CREATE INDEX C_RM_RATINGS_BYID_N_RATE ON C_RM_RATINGS_ACTIVE_BY_ID (N_RATING_CODE) ;
  CREATE INDEX C_RM_RATINGS_BYID_O_RATE ON C_RM_RATINGS_ACTIVE_BY_ID (O_RATING_CODE) ;
  CREATE INDEX C_RM_RATINGS_BYID_P_RATE ON C_RM_RATINGS_ACTIVE_BY_ID (P_RATING_CODE) ;
  CREATE INDEX C_RM_RATINGS_BYID_Q_RATE ON C_RM_RATINGS_ACTIVE_BY_ID (Q_RATING_CODE) ;
  CREATE INDEX C_RM_RATINGS_BYID_R_RATE ON C_RM_RATINGS_ACTIVE_BY_ID (R_RATING_CODE) ;
  CREATE INDEX C_RM_RATINGS_BYID_S_RATE ON C_RM_RATINGS_ACTIVE_BY_ID (S_RATING_CODE) ;
  CREATE INDEX C_RM_RATINGS_BYID_T_RATE ON C_RM_RATINGS_ACTIVE_BY_ID (T_RATING_CODE) ;
  CREATE INDEX C_RM_RATINGS_BYID_U_RATE ON C_RM_RATINGS_ACTIVE_BY_ID (U_RATING_CODE) ;
  CREATE INDEX C_RM_RATINGS_BYID_V_RATE ON C_RM_RATINGS_ACTIVE_BY_ID (V_RATING_CODE) ;
  CREATE INDEX C_RM_RATINGS_BYID_W_RATE ON C_RM_RATINGS_ACTIVE_BY_ID (W_RATING_CODE) ;
  CREATE INDEX C_RM_RATINGS_BYID_X_RATE ON C_RM_RATINGS_ACTIVE_BY_ID (X_RATING_CODE) ;
  CREATE INDEX C_RM_RATINGS_BYID_Y_RATE ON C_RM_RATINGS_ACTIVE_BY_ID (Y_RATING_CODE) ;
  CREATE INDEX C_RM_RATINGS_BYID_Z_RATE ON C_RM_RATINGS_ACTIVE_BY_ID (Z_RATING_CODE) ;
  CREATE INDEX C_RM_RATINGS_BYID_C_RSCR ON C_RM_RATINGS_ACTIVE_BY_ID (C_SCREENING_CODE) ;
  CREATE INDEX C_RM_RATINGS_BYID_D_RSCR ON C_RM_RATINGS_ACTIVE_BY_ID (D_SCREENING_CODE) ;
  CREATE INDEX C_RM_RATINGS_BYID_F_RSCR ON C_RM_RATINGS_ACTIVE_BY_ID (F_SCREENING_CODE) ;
  CREATE INDEX C_RM_RATINGS_BYID_G_RSCR ON C_RM_RATINGS_ACTIVE_BY_ID (G_SCREENING_CODE) ;
  CREATE INDEX C_RM_RATINGS_BYID_H_RSCR ON C_RM_RATINGS_ACTIVE_BY_ID (H_SCREENING_CODE) ;
  CREATE INDEX C_RM_RATINGS_BYID_J_RSCR ON C_RM_RATINGS_ACTIVE_BY_ID (J_SCREENING_CODE) ;
  CREATE INDEX C_RM_RATINGS_BYID_K_RSCR ON C_RM_RATINGS_ACTIVE_BY_ID (K_SCREENING_CODE) ;
  CREATE INDEX C_RM_RATINGS_BYID_M_RSCR ON C_RM_RATINGS_ACTIVE_BY_ID (M_SCREENING_CODE) ;
  CREATE INDEX C_RM_RATINGS_BYID_N_RSCR ON C_RM_RATINGS_ACTIVE_BY_ID (N_SCREENING_CODE) ;
  CREATE INDEX C_RM_RATINGS_BYID_O_RSCR ON C_RM_RATINGS_ACTIVE_BY_ID (O_SCREENING_CODE) ;
  CREATE INDEX C_RM_RATINGS_BYID_P_RSCR ON C_RM_RATINGS_ACTIVE_BY_ID (P_SCREENING_CODE) ;
  CREATE INDEX C_RM_RATINGS_BYID_Q_RSCR ON C_RM_RATINGS_ACTIVE_BY_ID (Q_SCREENING_CODE) ;
  CREATE INDEX C_RM_RATINGS_BYID_R_RSCR ON C_RM_RATINGS_ACTIVE_BY_ID (R_SCREENING_CODE) ;
  CREATE INDEX C_RM_RATINGS_BYID_S_RSCR ON C_RM_RATINGS_ACTIVE_BY_ID (S_SCREENING_CODE) ;
  CREATE INDEX C_RM_RATINGS_BYID_T_RSCR ON C_RM_RATINGS_ACTIVE_BY_ID (T_SCREENING_CODE) ;
  CREATE INDEX C_RM_RATINGS_BYID_U_RSCR ON C_RM_RATINGS_ACTIVE_BY_ID (U_SCREENING_CODE) ;
  CREATE INDEX C_RM_RATINGS_BYID_V_RSCR ON C_RM_RATINGS_ACTIVE_BY_ID (V_SCREENING_CODE) ;
  CREATE INDEX C_RM_RATINGS_BYID_W_RSCR ON C_RM_RATINGS_ACTIVE_BY_ID (W_SCREENING_CODE) ;
  CREATE INDEX C_RM_RATINGS_BYID_X_RSCR ON C_RM_RATINGS_ACTIVE_BY_ID (X_SCREENING_CODE) ;
  CREATE INDEX C_RM_RATINGS_BYID_Y_RSCR ON C_RM_RATINGS_ACTIVE_BY_ID (Y_SCREENING_CODE) ;
  CREATE INDEX C_RM_RATINGS_BYID_Z_RSCR ON C_RM_RATINGS_ACTIVE_BY_ID (Z_SCREENING_CODE) ;
