--BEGIN
--  dbms_snapshot.REFRESH('C_RM_CONTACTS_BY_PROJECT');
--END;
-- CREATE MATERIALIZED VIEW LOG ON H_RM_CONTACTS_BY_PROJECT;
CREATE MATERIALIZED VIEW C_RM_CONTACTS_BY_PROJECT refresh FAST ON demand
AS
  SELECT PIDM
  , BANNER_ID
  , NAME_SORT
  , ENTITY_CODE
  , REFERENCE_NUM
  , IDEN_CODE
  , CONTACT_TYPE_CODE
  , CONTACT_TYPE_DESC
  , PROJECT_CODE
  , PROJECT_DESC
  , PROJECT_NUMBER
  , LAST_CONTACT_IND
  , LAST_ASK_IND
  , CONFID_IND
  , CAMPAIGN_GROUP
  , PROJECT_GROUP
  , PROJECT_AVAILABLE_IND
  , IDEN_CODE_ASSIGNED
  , CONTACT_DESC
  , CALL_REPORT
  , CONTACT_DATE
  , CREATE_TICKLER_IND
  , TICKLER_MESSAGE
  , TICKLER_DATE
  , TICKLER_STATUS
  , ASK_AMOUNT
  , EXPECTED_CLOSE_AMOUNT
  , MOVE_CODE
  , MOVE_DESC
  , MOVE_SEQNO
  , PROPOSAL_CODE
  , PROPOSAL_DESC
  , PROPOSAL_SEQNO
  , CREATE_DATE
  , ACTIVITY_DATE
  , BANNER_USER_ID
  , DATA_ORIGIN
  , RECORD_START_DATE
  FROM h_rm_contacts_by_project
  WHERE record_end_date IS NULL
  ORDER BY pidm
  , reference_num
  , project_code
  , project_number;
  
-- INDEXES for MATERIALIZED VIEW

  CREATE INDEX C_RM_CONT_PROJ_PIDM ON C_RM_CONTACTS_BY_PROJECT (PIDM) ;
  CREATE INDEX C_RM_CONT_PROJ_BANNER_ID ON C_RM_CONTACTS_BY_PROJECT (BANNER_ID) ;
  CREATE INDEX C_RM_CONT_PROJ_NAME ON C_RM_CONTACTS_BY_PROJECT (NAME_SORT) ;
  CREATE INDEX C_RM_CONT_PROJ_REFNO ON C_RM_CONTACTS_BY_PROJECT (REFERENCE_NUM) ;
  CREATE INDEX C_RM_CONT_PROJ_ENTITY ON C_RM_CONTACTS_BY_PROJECT (ENTITY_CODE) ;
  CREATE INDEX C_RM_CONT_PROJ_CODE ON C_RM_CONTACTS_BY_PROJECT (PROJECT_CODE) ;
  CREATE INDEX C_RM_CONT_PROJ_NUM ON C_RM_CONTACTS_BY_PROJECT (PROJECT_NUMBER) ;
  CREATE INDEX C_RM_CONT_PROJ_LAST_CONT ON C_RM_CONTACTS_BY_PROJECT (LAST_CONTACT_IND) ;
  CREATE INDEX C_RM_CONT_PROJ_LAST_ASK ON C_RM_CONTACTS_BY_PROJECT (LAST_ASK_IND) ;
