CREATE VIEW C_VA_GTVSDAX
AS
  SELECT GTVSDAX_EXTERNAL_CODE
, GTVSDAX_INTERNAL_CODE
, GTVSDAX_REPORTING_DATE
, GTVSDAX_TRANSLATION_CODE
, GTVSDAX_INTERNAL_CODE_SEQNO
, GTVSDAX_INTERNAL_CODE_GROUP
, GTVSDAX_DESC
, GTVSDAX_SYSREQ_IND
, GTVSDAX_ACTIVITY_DATE
, GTVSDAX_USER_ID
, GTVSDAX_SYSI_CODE
, GTVSDAX_CONCEPT
, GTVSDAX_COMMENTS
  FROM H_VA_GTVSDAX
  WHERE record_end_date IS NULL; 
